cit_runner to print error message if test load failed
Summary:
in some cases when unittest loader fail to load the test cases, the output is ambiguous like this:
```
tests.fby3.unittest.loader._FailedTest.test_power_util
```
so we know the cit_runner fail to load the test but we don't know exact the reason.
I think it will be helpful to expose the error message from the unittest.defaultTestLoader to speed up the debug process

Test Plan:
If cit_runner fail to load the test, it will print out the error message: (updated, code will exist once hit error)
```
root@sled2402-oob:/usr/local/bin/tests2# python cit_runner.py --list-tests --platform fby3
Failed to import test module: test_power_util
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/usr/local/bin/tests2/tests/fby3/test_power_util.py", line 20, in <module>
    from common.base_power_util_test import BasePowerUtilTest
  File "/usr/local/bin/tests2/common/base_power_util_test.py", line 68
    pattern = rf"^Powering fru.*to {} state.*$"
             ^
SyntaxError: f-string: empty expression not allowed
```

cit_runner still execute correctly after this change:
```
root@sled2402-oob:/usr/local/bin/tests2# python cit_runner.py --platform fby3 --run-test tests.fby3.test_power_util.PowerUtilTest
test_12V_slot_cycle (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] cycle ... ok
test_12V_slot_off (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] 12V-off ... ok
test_12V_slot_on (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] 12V-on ... ok
test_show_slot_status (tests.fby3.test_power_util.PowerUtilTest)
test power-util can show slot status ... ok
test_slot_cycle (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] cycle ... test_slot_off (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] off ... ok
test_slot_on (tests.fby3.test_power_util.PowerUtilTest)
test power-util [slot] on ... ok
...

----------------------------------------------------------------------
Ran 8 tests in 559.776s

Reviewed By: benwei13

Differential Revision: D27349794

fbshipit-source-id: bd9c3addf6