fbgc: support log-util (#1256)
Summary:
fbgc: support log-util
Support log-util.
FRU related functions are used to print the usage and determine invalid command.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1256

Test Plan:
Build and test PASS on AST2600-A1 EVB.
1. Add fake log to test log-util print/clear
root@bmc-oob:~# log-util all --print
2020 Oct 14 01:19:38 log-util: User cleared all logs
0    all      2020-10-14 01:19:56    ipmid            plat_fruid_init() Failed to copy /sys/bus/i2c/devices/4-0050/eeprom to /tmp/fruid_uic.bin
root@bmc-oob:~# date
Wed Oct 14 01:20:10 PDT 2020
root@bmc-oob:~# log-util all --print --json
{
    "Logs": [
        {
            "APP_NAME": "ipmid",
            "FRU#": "0",
            "FRU_NAME": "all",
            "MESSAGE": "plat_fruid_init() Failed to copy /sys/bus/i2c/devices/4-0050/eeprom to /tmp/fruid_uic.bin",
            "TIME_STAMP": "2020-10-14 01:19:56"
        }
    ]
}
root@bmc-oob:~# log-util all --clear
root@bmc-oob:~# log-util all --print
2020 Oct 14 01:19:38 log-util: User cleared all logs
root@bmc-oob:~# log-util test --print
ERROR: ValidationError: fru:  not in {all,bmc,dpb,iocm,nic,scc,server,sys,uic}
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,bmc,dpb,iocm,nic,scc,server,sys,uic} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU

2. Check there are no unexpected error logs in BMC /var/log/messages.

3. Check log is kept after BMC reboot.
root@bmc-oob:~# log-util all --print
0    all      2020-10-15 02:17:27    ipmid            plat_fruid_init() Failed to copy /sys/bus/i2c/devices/6-0054/eeprom to /tmp/fruid_bmc.bin
root@bmc-oob:~# reboot

Broadcast message from root@bmc-oob. (pts/0) (Thu Oct 15 02:17:48 2020):

The system is going down for reboot NOW!
root@bmc-oob:~# Connection to 10.248.41.57 closed by remote host.
Connection to 10.248.41.57 closed.
wiwynn@wiwynn-VirtualBox:~$ ssh root@10.248.41.57
root@10.248.41.57's password:
root@bmc-oob:~# log-util all --print
0    all      2020-10-15 02:17:27    ipmid            plat_fruid_init() Failed to copy /sys/bus/i2c/devices/6-0054/eeprom to /tmp/fruid_bmc.bin

Reviewed By: benwei13

Differential Revision: D24348797

Pulled By: zhdaniel12

fbshipit-source-id: e7db791852