fby3: cwc: block exp power control when slot1 fw update on cwc (#1809)
Summary:
- When fw update of slot1 components is on going,
  changing the power status of slot1 components should be blocked to avoid interrupting the update.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1809

Test Plan:
- Check if changing the power of exp baords on cwc when fw update on slot1 will be blocked - pass

Log:
- 12v cycle top gpv3 when cwc bic update
root@bmc-oob:/tmp# fw-util slot1 --update 2U-cwc 2U_bic Y3BRCWC_E01.bin
slot_id: 1, comp: 2c, intf: 0, img: Y3BRCWC_E01.bin, force: 0
file size = 175250 bytes, slot = 1, intf = 0x15
bytes/per read = 244
updated bic: 5 %
...

root@bmc-oob:~# power-util slot1 2U-top 12V-cycle
12V Power cycling fru 32...
fw update is on going on fru:1...
ERROR: power-util fru[1] [12V_CYCLE] failed

- 12v cycle top gpv3 when top gpv3 vr update
root@bmc-oob:/tmp# fw-util slot1 --update 2U-bot 2U_vr_stby1 CWC_GPV3_P3V3_EVT2_WI_450_V1-24_07212021_1621.txt
slot_id: 1, comp: 4b, intf: 0, img: CWC_GPV3_P3V3_EVT2_WI_450_V1-24_07212021_1621.txt, force: 0
disabling VR fault monitor...
Find the VR device, Vendor=VY(2.3)
Update VR_P3V3_STBY1...remaining writes 255.
Init libusb Successful!
1cc0:0007 (bus 1, device 29) path: 1.3.4.2.3
Manufactured : Texas Instruments
Product : Virtual COM Port
----------------------------------------
...

root@bmc-oob:~# power-util slot1 2U-top 12V-cycle
12V Power cycling fru 32...
fw update is on going on fru:1...
ERROR: power-util fru[1] [12V_CYCLE] failed

Reviewed By: benwei13, peterdelevoryas

Differential Revision: D30739403

Pulled By: GoldenBug

fbshipit-source-id: 483feaf751