fix issue caused by previous diff
Summary: Fix code failing with http.

Test Plan:
before applying the change:
```
➜  rest-api git:(helium) ✗ curl http://fboss8382003-oob.snc1:8080/api

{"Resources": [], "Actions": [], "Information": {"reason": "AttributeError(\"'_SelectorSocketTransport' object has no attribute 'secure'\",)"}}%
```
after applying the change:
```
➜  rest-api git:(helium) ✗ curl http://fboss8382003-oob.snc1:8080/api

{"Actions": [], "Resources": ["bmc", "sensors", "logs", "fans"], "Information": {"version": "v0.2", "Description": "wedge100 RESTful API Entry"}}%
```

Reviewed By: sammyblueeyes

Differential Revision: D22980885

fbshipit-source-id: 918eaaf26c