Fix eeprom test
Summary: Turns out, FC has multiple ways by which eeprom data is populated. Fix in tests to accomodate all

Test Plan:
-> Before when test failed on card:
```
root@fsw003-fc002-oob:/usr/local/bin/tests2# python cit_runner.py --platform galaxy100
test_asset_tag (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_extended_mac_base (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_local_mac (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_location_on_fabric (tests.galaxy100.test_eeprom.EepromTest) ... ERROR
test_odm_pcb (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_name (tests.galaxy100.test_eeprom.EepromTest) ... ERROR
test_product_part_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_serial_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_system_manufacturer (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_version (tests.galaxy100.test_eeprom.EepromTest) ... ok

======================================================================
ERROR: test_location_on_fabric (tests.galaxy100.test_eeprom.EepromTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_eeprom_test.py", line 124, in test_location_on_fabric
    self.assertTrue(found, "Location on Fabric %s not in set %s".format(name, self.location_on_fabric))
UnboundLocalError: local variable 'found' referenced before assignment

======================================================================
ERROR: test_product_name (tests.galaxy100.test_eeprom.EepromTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_eeprom_test.py", line 81, in test_product_name
    self.assertTrue(found, "Product name %s not in set %s".format(name, self.product_name))
UnboundLocalError: local variable 'found' referenced before assignment

----------------------------------------------------------------------
Ran 10 tests in 6.255s
```
Test on FC :
```
-> After fixes on FC
root@fsw003-fc002-oob:/usr/local/bin/tests2# python cit_runner.py --platform galaxy100
test_asset_tag (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_extended_mac_base (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_local_mac (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_location_on_fabric (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_odm_pcb (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_name (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_part_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_serial_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_system_manufacturer (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_version (tests.galaxy100.test_eeprom.EepromTest) ... ok

----------------------------------------------------------------------
Ran 10 tests in 6.158s

OK

from /tmp/cit.log:

On Fabric card skipping test
Finished logging for test_location_on_fabric
```
-> test on LC
```
root@fsw003-lc401-oob:/usr/local/bin/tests2#
root@fsw003-lc401-oob:/usr/local/bin/tests2# python cit_runner.py --platform galaxy100
test_asset_tag (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_extended_mac_base (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_local_mac (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_location_on_fabric (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_odm_pcb (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_name (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_part_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_product_serial_number (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_system_manufacturer (tests.galaxy100.test_eeprom.EepromTest) ... ok
test_version (tests.galaxy100.test_eeprom.EepromTest) ... ok

----------------------------------------------------------------------
Ran 10 tests in 5.994s

OK

from /tmp/cit.log:
Starting cit logging for test_location_on_fabric
Running EEPROM command: ['/usr/bin/weutil']
Wedge EEPROM :
Version: 2
Product Name: GALAXY-LC
Product Part Number: 20-001678
System Assembly Part Number: 134-000036-04
Facebook PCBA Part Number: 132-000036-04
Facebook PCB Part Number: 131-000026-03
ODM PCBA Part Number: R1018G000204
ODM PCBA Serial Number: G024216462083
Product Production State: 3
Product Version: 1
Product Sub-Version: 0
Product Serial Number: F024216505022
Product Asset Tag: 5125183
System Manufacturer: CLS
System Manufacturing Date: 12-22-16
PCB Manufacturer: ISU
Assembled At: CLS
Local MAC: 00:E0:EC:46:0D:83
Extended MAC Base: 00:E0:EC:46:0D:84
Extended MAC Address Size: 128
Location on Fabric: LEFT
CRC8: 0xd5

Finished logging for test_location_on_fabric
```

Reviewed By: sammyblueeyes

Differential Revision: D15345763

fbshipit-source-id: 0eb5a60ce2