test2: interface_test: fix byte/str type mismatches
Summary:
Fixes for d9413be01a1cf5d860c337e186773d1bc4637094.

Observed another instance of this test case failing:
tests.wedge.test_interface.InterfaceTest.test_eth0_v4_interface.  In
this case, obtained the following Python error:

```
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 136, in test_eth0_v4_interface
    self.assertEqual(self.ping_v4(), 0, "Ping test for %s v4 failed".format("eth0"))
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 111, in ping_v4
    ip = self.get_ipv4_address()
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 58, in get_ipv4_address
    + out
TypeError: Can't convert 'bytes' object to str implicitly
```

In the class, `ifname` is already a string and str.encode("utf-8")
returns a bytes object.  This can no longer be concatenated with
str types.  Fix up a few cases where the encode("utf-8") is not needed
for logging, which matches logging / exception code elsewhere in this
file, and instead explicitly cast via the str constructor.

Test Plan:
Manually run code in Python REPL mode on a BMC.

netcastle run.  Hope to observe this test case fail again, with better
debug data and no python error.

Reviewed By: vineelasmile

Differential Revision: D18514533

fbshipit-source-id: c58aaecc59