Fix exception logging info(). Add better exception debug.
Summary:
See task for details.

It's possible this only happens for python 2 systems like in the task, but I'm too tired to check.

Test Plan:
Test exception flow:

```
$ oobgrader --host "2401:db00:1026:3060:ce37:abff:fe09:52e9" --pypartition-tag "d537478"
 --fbpkg-name openbmc.image.wedge40:12 -m scp --wait
```
https://fburl.com/scuba/openbmc_upgrades/99364vm2
```
Unhandled exception raised.
Traceback (most recent call last):
File "/tmp/tmp.a3F2SM/tmp/improve_system.py", line 236, in <module>
    improve_system(logger)
File "/tmp/tmp.a3F2SM/tmp/improve_system.py", line 165, in improve_system
    partitions = system.get_valid_partitions(all_mtds, checksums, logger)
File "/var/volatile/tmp/tmp.a3F2SM/tmp/system.py", line 548, in get_valid_partitions
    partitions = get_partitions(vc, checksums, logger)
File "/var/volatile/tmp/tmp.a3F2SM/tmp/system.py", line 474, in get_partitions
    0x060000, 0x000000, "u-boot", images, checksums, logger
File "/var/volatile/tmp/tmp.a3F2SM/tmp/partition.py", line 181, in __init__
    Partition.__init__(self, size, offset, name, images, logger)
File "/var/volatile/tmp/tmp.a3F2SM/tmp/partition.py", line 86, in __init__
    self.finalize()
File "/var/volatile/tmp/tmp.a3F2SM/tmp/partition.py", line 157, in finalize
    "Could not find MD5 checksums appended to U-Boot partition: %s", repr(e)
TypeError: info() takes exactly 2 arguments (3 given)
```

Fix the bug causing the exception and ensure BMC is flashed:

```
$ oobgrader --host "2401:db00:1026:3060:ce37:abff:fe09:52e9" --pypartition-tag "d952615"
 --fbpkg-name openbmc.image.wedge40:12 -m scp --wait
```

https://fburl.com/scuba/openbmc_upgrades/iqompxo6

After reboot `/proc/mtd` should now be correct. Try flashing again:

```
root@bmc:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00060000 00010000 "u-boot"
mtd1: 00020000 00010000 "env"
mtd2: 00280000 00010000 "kernel"
mtd3: 00c00000 00010000 "rootfs"
mtd4: 01100000 00010000 "data0"
mtd5: 02000000 00010000 "flash0"
```

```
$ oobgrader --host "2401:db00:1026:3060:ce37:abff:fe09:52e9" --pypartition-tag "30f2b3b" --fbpkg-name openbmc.image.wedge40:12 -m scp --wait
```
(oobgrader job failed due to T68253074)
https://fburl.com/scuba/openbmc_upgrades/8lfz6flr

But BMC was still upgraded successfully:
```
$ ssh root@2401:db00:1026:3060:ce37:abff:fe09:52e9
root@2401:db00:1026:3060:ce37:abff:fe09:52e9's password:
Last login: Mon Jun  3 03:40:31 2019 from 2401:db00:1210:c1c4:face:0:66:0
root@bmc-oob:~# cat /etc/issue
OpenBMC Release wedge-v2019.22.0

```

Reviewed By: kawmarco

Differential Revision: D21948382

fbshipit-source-id: 75c5c04199