fuji: tests: fix fan tests
Summary:
This test had some pretty egregious duplication going on, and beyond that it was actually incorrect because some of the tests did not have the fan_id set correctly, so half of the fans never went through the set fan speed test.

This diff simplifies the test significantly, and also speeds up execution from 6 minutes to less than 3 minutes since it doesn't kill and restart the fan service after every individual fan action.

Test Plan:
Old test time:

```
root@fboss317344532-oob:~# time python3.8 /usr/local/bin/tests2/cit_runner.py --run-test tests.fuji.test_fans.FansTest
test_all_fans_read (tests.fuji.test_fans.FansTest)
Test if all fan dump is returning sane data ... ok
test_fan1_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan1_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan2_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan2_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan3_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan3_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan4_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan4_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan5_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan5_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan6_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan6_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan7_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan7_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan8_pwm_set (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok
test_fan8_read (tests.fuji.test_fans.FansTest)
For each fan read and test speed ... ok

----------------------------------------------------------------------
Ran 17 tests in 355.834s

OK

real	5m57.141s
```

New test time:
```
root@fboss317344532-oob:~# time python3.8 /usr/local/bin/tests2/cit_runner.py --run-test tests.fuji.test_fans.FansTest
test_all_fans_read (tests.fuji.test_fans.FansTest)
Test if all fan dump is returning sane data ... ok
test_fans_pwm_set (tests.fuji.test_fans.FansTest) ... ok
test_fans_read (tests.fuji.test_fans.FansTest) ... ok

----------------------------------------------------------------------
Ran 3 tests in 157.710s

OK

real	2m38.918s
```

Error message on failure:
```
root@bmc-oob:/usr/local/bin/tests2# python3.8 cit_runner.py --run-test tests.fuji.test_fans.FansTest.test_fans_read
test_fans_read (tests.fuji.test_fans.FansTest) ...
======================================================================
ERROR: test_fans_read (tests.fuji.test_fans.FansTest) (fan_id=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fuji/test_fans.py", line 77, in test_fans_read
    self.fan_read_test_impl(i)
  File "/usr/local/bin/tests2/tests/fuji/test_fans.py", line 52, in fan_read_test_impl
    raise Exception("test exception if id=3")
Exception: test exception if id=3

----------------------------------------------------------------------
Ran 1 test in 29.810s

FAILED (errors=1)
```

Reviewed By: tao-ren

Differential Revision: D42822663

fbshipit-source-id: c9f5038c4d17cbb06ac7edeb013afb0944a4f729