tests: Fix `pidof -s`
Summary:
The `pidof` used in wedge100, elbert and minipack comes from busybox
and doesn't support the `-s` option that asks it to return at most 1
pid. This causes 2 tests on each platform to fail.

This diff removes the usage of `-s` and implements this in the test manually.

Test Plan:
Fix `pidof -s`

Before:
```
root@fboss308772206-oob:/run/tests2# python cit_runner.py --run-test tests.minipack.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates
test_syslog_restart_no_duplicates (tests.minipack.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates) ... pidof: invalid option -- 's'
BusyBox v1.36.1 () multi-call binary.

Usage: pidof [NAME]...
ERROR

======================================================================
ERROR: test_syslog_restart_no_duplicates (tests.minipack.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_syslog_restart_test.py", line 50, in setUp
    self._ensure_rsyslog_working()
  File "/run/tests2/common/base_syslog_restart_test.py", line 129, in _ensure_rsyslog_working
    self._get_syslog_process_count(), 1, "expected exactly one syslogd process"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/tests2/common/base_syslog_restart_test.py", line 93, in _get_syslog_process_count
    reference_cmdline = self._get_syslog_cmdline()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/tests2/common/base_syslog_restart_test.py", line 111, in _get_syslog_cmdline
    reference_pid = self._get_pid()
                    ^^^^^^^^^^^^^^^
  File "/run/tests2/common/base_syslog_restart_test.py", line 56, in _get_pid
    raise SyslogRestartTestError(
common.base_syslog_restart_test.SyslogRestartTestError: `pidof rsyslogd` returned an empty string, rsyslog daemon doesn't seem to be running.

----------------------------------------------------------------------
Ran 1 test in 0.166s

FAILED (errors=1)
```

After:
```
root@fboss308772206-oob:/run/tests2# python cit_runner.py --run-test tests.minipack.test_syslog_restart.SyslogRestartTest
test_syslog_restart_no_duplicates (tests.minipack.test_syslog_restart.SyslogRestartTest.test_syslog_restart_no_duplicates) ... ok
test_syslog_restart_pid_changed (tests.minipack.test_syslog_restart.SyslogRestartTest.test_syslog_restart_pid_changed) ... ok

----------------------------------------------------------------------
Ran 2 tests in 51.295s

OK
```

Reviewed By: Scott8440

Differential Revision:
D61370141

Privacy Context Container: L1188897

fbshipit-source-id: b9f1ac1795dc143d1a3ecfc6c38438586ac7e5dd