at93cx6_util: Support GPIO number and GPIO shadow name are accpected for SPI pin option (#153)
Summary:
1. Support GPIO number and GPIO shadow name are accpected for SPI pin option
2. Kernel 5.0.3 gpio number is not same as kernel 4.1.51, so we need to add GPIO shadow name for gpio pin argument.

Test Plan :

- ===================== Normal case =====================
- root@bmc-oob:~# source /usr/local/bin/openbmc-utils.sh
- root@bmc-oob:~# devmem_set_bit $(scu_addr 7C) 12
- root@bmc-oob:~# devmem_set_bit $(scu_addr 7C) 13
- root@bmc-oob:~# devmem_set_bit $(scu_addr 80) 15
- root@bmc-oob:~# gpiocli -s BMC_SPI1_CLK set-direction out
- root@bmc-oob:~# gpiocli -s BMC_SPI1_CS0 set-direction out
- root@bmc-oob:~# gpiocli -s BMC_SPI1_MISO set-direction in
- root@bmc-oob:~# gpiocli -s BMC_SPI1_MOSI set-direction out
- root@bmc-oob:~# echo 0 > $SMBCPLD_SYSFS_DIR/spi_1_b0
- root@bmc-oob:~# echo 1 > $SMBCPLD_SYSFS_DIR/spi_1_b1
- root@bmc-oob:~# echo 0 > $SMBCPLD_SYSFS_DIR/spi_1_b2
- root@bmc-oob:~# echo 1 > $SMBCPLD_SYSFS_DIR/cpld_bcm5396_mux_sel
- root@bmc-oob:~# gpiocli -s BMC_BCM5396_MUX_SEL set-direction out
- root@bmc-oob:~# gpiocli -s BMC_BCM5396_MUX_SEL set-value 1
- Use GPIO shadow name :
- root@bmc-oob:~# at93cx6_util_py3.py --cs BMC_SPI1_CS0 --clk BMC_SPI1_CLK --mosi BMC_SPI1_MOSI --miso BMC_SPI1_MISO chip read --file bcm5396
- root@bmc-oob:~# hexdump -C bcm5396
00000000  02 a8 01 50 00 00 00 00  00 00 00 00 00 00 00 00  |...P............|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
- Use GPIO number :
- at93cx6_util_py3.py --cs 68 --clk 69 --mosi 70 --miso 71 chip read --file bcm5396_1
- root@bmc-oob:~# hexdump -C bcm5396_1
00000000  02 a8 01 50 00 00 00 00  00 00 00 00 00 00 00 00  |...P............|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
- Use GPIO default value:
- root@bmc-oob:~# at93cx6_util_py3.py chip read --file bcm5396_2
- root@bmc-oob:~# hexdump -C bcm5396_2
00000000  02 a8 01 50 00 00 00 00  00 00 00 00 00 00 00 00  |...P............|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
- ===================== Error case =====================
- root@bmc-oob:~# at93cx6_util_py3.py --cs BMC_SPI1_CS0 --clk A --mosi B --miso BMC_SPI1_MISO chip read --file bcm5396
Traceback (most recent call last):
  File "/usr/local/bin/at93cx6_util_py3.py", line 259, in <module>
    args.func(args)
  File "/usr/local/bin/at93cx6_util_py3.py", line 169, in read_chip
    chip = get_chip(args)
  File "/usr/local/bin/at93cx6_util_py3.py", line 67, in get_chip
    if is_gpio_valid(cs_num, clk_num, mosi_num, miso_num) is 0:
  File "/usr/local/bin/at93cx6_util_py3.py", line 42, in is_gpio_valid
    raise Exception("CLK value is invalid!")
Exception: CLK value is invalid!

Test on Minipack: pass
Pull Request resolved: https://github.com/facebookexternal/openbmc.accton/pull/153

Reviewed By: tomrepo

Differential Revision: D15521850

fbshipit-source-id: 3082ba2a31