Firmware upgrade test: Fix typo
Summary: Introduced in D61575490

Test Plan:
Original error:
```
Traceback (most recent call last):
  File "/data/sandcastle/boxes/trunk-git-openbmc/tests2/tests/fuji/external_fw_upgrade_test_individual.py", line 95, in test_bic_fw_upgrade
    super().do_external_firmware_upgrade("bic")
  File "/data/sandcastle/boxes/trunk-git-openbmc/tests2/common/base_fw_upgrade_test.py", line 875, in do_external_firmware_upgrade
    self.upgrade_components(components_to_upgrade, logging=G_VERBOSE)
  File "/data/sandcastle/boxes/trunk-git-openbmc/tests2/common/base_fw_upgrade_test.py", line 759, in upgrade_components
    self.upgrade_one_component(component, logging)
  File "/data/sandcastle/boxes/trunk-git-openbmc/tests2/common/base_fw_upgrade_test.py", line 772, in upgrade_one_component
    entity = component["entity"]
NameError: name 'component' is not defined
```

Reviewed By: kimdo8736

Differential Revision: D61728456

fbshipit-source-id: 9a979b28041bfdb0efa6700f99e7b87502af916e