signtool: support time-back signing
Summary:
mimic generate lock image process to support sign image with specified timestamp.

Specify locked or time_back is independent so you can execute
fit-sign --lock and fit-sign --timeback with any order, or just do one dependents on what kind of image you would like to generate.

The requirement is the input image shall be unsigned image,
because fit-sign does not support resign yet.

This change let fit-sign inject timeback property in u-boot fit root node
Then during the sign time, if timeback property exist fit-sign will set
SOURCE_DATE_EPOCH to let mkimage generate the signed image
with timestamp specified by timeback.

Test Plan:
timeback sign process
* Step 1: generate the timeback unsigned image
```
[~/release/fbttn/resgin] ~/openbmc/tools/verified-boot/signing/fit-sign --time-back $(date -d 2020-02-20 +%s) flash-brycecanyon1.unsigned flash-brycecanyon1.timeback
Try loading image meta from image flash-brycecanyon1.unsigned
No image meta found: ValueError('No JSON object could be decoded',)
Signing legacy image
Setting timeback signing, next you need to sign it...
Wrote unsigned timeback firmware: flash-brycecanyon1.timeback
```
* Step 2: selfsign it
```
[~/release/fbttn/resgin] selfsimg flash-brycecanyon1.timeback
Try loading image meta from image flash-brycecanyon1.timeback
No image meta found: ValueError('No JSON object could be decoded',)
Signing legacy image
Extract timeback = 1582185600 from uboot-fit to args.time_back

...
Timestamp:    Thu Feb 20 00:00:00 2020
Wrote signed firmware: flash-brycecanyon1.timeback.signed

```
* optionally use vboot-check check the signed image
```
[~/release/fbttn/resgin] vboot-check flash-brycecanyon1.timeback.signed
Try loading image meta from image flash-brycecanyon1.timeback.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: not set
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

```
Test sign legacy image: 5 tests
1. normal signed image
2. normal locked image
3. timeback signed image
4. timeback locked image ( lock first, then timeback)
5. timeback locked image ( timeback first, then lock)
```
[zhdaniel@devvm4263.ftw0 ~/release/fbttn/resgin] for img in $(ls -rt *.signed) ; do echo; echo "========== $img ========";  vboot-check $img; done

========== flash-brycecanyon1.unsigned.signed ========
Try loading image meta from image flash-brycecanyon1.unsigned.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: not set
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Wed Apr 28 06:21:10 UTC 2021 (0x6088fed6)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Wed Apr 28 06:21:19 UTC 2021 (0x6088fedf)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

========== flash-brycecanyon1.locked.signed ========
Try loading image meta from image flash-brycecanyon1.locked.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: [1]
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Wed Apr 28 06:22:12 UTC 2021 (0x6088ff14)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Wed Apr 28 06:22:21 UTC 2021 (0x6088ff1d)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

========== flash-brycecanyon1.timeback.signed ========
Try loading image meta from image flash-brycecanyon1.timeback.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: not set
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

========== flash-brycecanyon1.timeback.locked.signed ========
Try loading image meta from image flash-brycecanyon1.timeback.locked.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: [1]
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

========== flash-brycecanyon1.locked.timeback.signed ========
Try loading image meta from image flash-brycecanyon1.locked.timeback.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: [1]
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK
[zhdaniel@devvm4263.ftw0 ~/release/fbttn/resgin]

```

Test HSM sign: test the same 5 sign process
```
[~/release/fbgc/resign] ll -rt
total 280160
-rw-r--r-- 1 zhdaniel users 28687154 Apr 27 20:45 flash-grandcanyon.unsigned
-rw-r--r-- 1 zhdaniel users 28687154 Apr 27 20:50 flash-grandcanyon.timeback
-rw-r--r-- 1 zhdaniel users 28687300 Apr 27 20:51 flash-grandcanyon.timeback.signed
-rw-r--r-- 1 zhdaniel users 28687300 Apr 27 22:57 flash-grandcanyon.unsigned.signed
-rw-r--r-- 1 zhdaniel users 28687154 Apr 27 22:59 flash-grandcanyon.locked
-rw-r--r-- 1 zhdaniel users 28687300 Apr 27 22:59 flash-grandcanyon.locked.signed
-rw-r--r-- 1 zhdaniel users 28687154 Apr 27 23:00 flash-grandcanyon.locked.timeback
-rw-r--r-- 1 zhdaniel users 28687300 Apr 27 23:01 flash-grandcanyon.locked.timeback.signed
-rw-r--r-- 1 zhdaniel users 28687154 Apr 27 23:04 flash-grandcanyon.timeback.locked
-rw-r--r-- 1 zhdaniel users 28687300 Apr 27 23:04 flash-grandcanyon.timeback.locked.signed

[ ~/release/fbgc/resign] for img in *.signed; do echo; echo "========== $img ========";  vboot-check $img; done

========== flash-grandcanyon.locked.signed ========
Try loading image meta from image flash-grandcanyon.locked.signed
override args.rom_size: 0x15000 => 0x40000
override args.uboot_fit_offset: 0x80000 => 0x100000
override args.uboot_fit_size: 0x60000 => 0xa0000

spl md5sum: 75e284ed014b5a8bbe88ff52790e46a5: OK
rec-u-boot md5sum: a374a0e5c3c4f30564f412fe2d73d6ca: OK

Lockbit: [1]
SPL FIT offset: 81524
  SPL KEK: key-obmc-compute-kek-0 (sha256,rsa4096) (signs image)

Subordinate timestamp: Fri Oct 09 23:01:05 UTC 2020 (0x5f80ebb1)
Subordinate keys signing key: obmc-compute-kek-0
Subordinate keys hash (sha256): c4f9bdcb2f8a8ba32a60499e38d3d917d4e4d052b8fa12f2530199820b84cb07: OK
  Subordinate: key-obmc-compute-sub-0 (sha256,rsa4096) (signs conf)

U-Boot timestamp: Wed Apr 28 05:59:14 UTC 2021 (0x6088f9b2)
U-Boot configuration signing key: obmc-compute-sub-0
U-Boot hash (sha256): e27b18ff224878be0a8757ec1f9775e756af09bb9cb6ba2a8e4e0e55f77bf49d: OK

Kernel/ramdisk timestamp: Wed Apr 28 05:59:29 UTC 2021 (0x6088f9c1)
Kernel/ramdisk configuration signing key: obmc-compute-sub-0
Kernel hash (sha256): d0a2019d83c02dbd09cff7d606039d8cf5d003f632391b474246534732d697d9: OK
Ramdisk hash (sha256): 8116e547f10dfe0ea950cf4758ba5bdf0c78f71bbf3d7df33508c162c4c5be82: OK

========== flash-grandcanyon.locked.timeback.signed ========
Try loading image meta from image flash-grandcanyon.locked.timeback.signed
override args.rom_size: 0x15000 => 0x40000
override args.uboot_fit_offset: 0x80000 => 0x100000
override args.uboot_fit_size: 0x60000 => 0xa0000

spl md5sum: 75e284ed014b5a8bbe88ff52790e46a5: OK
rec-u-boot md5sum: a374a0e5c3c4f30564f412fe2d73d6ca: OK

Lockbit: [1]
SPL FIT offset: 81524
  SPL KEK: key-obmc-compute-kek-0 (sha256,rsa4096) (signs image)

Subordinate timestamp: Fri Oct 09 23:01:05 UTC 2020 (0x5f80ebb1)
Subordinate keys signing key: obmc-compute-kek-0
Subordinate keys hash (sha256): c4f9bdcb2f8a8ba32a60499e38d3d917d4e4d052b8fa12f2530199820b84cb07: OK
  Subordinate: key-obmc-compute-sub-0 (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: obmc-compute-sub-0
U-Boot hash (sha256): e27b18ff224878be0a8757ec1f9775e756af09bb9cb6ba2a8e4e0e55f77bf49d: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: obmc-compute-sub-0
Kernel hash (sha256): d0a2019d83c02dbd09cff7d606039d8cf5d003f632391b474246534732d697d9: OK
Ramdisk hash (sha256): 8116e547f10dfe0ea950cf4758ba5bdf0c78f71bbf3d7df33508c162c4c5be82: OK

========== flash-grandcanyon.timeback.locked.signed ========
Try loading image meta from image flash-grandcanyon.timeback.locked.signed
override args.rom_size: 0x15000 => 0x40000
override args.uboot_fit_offset: 0x80000 => 0x100000
override args.uboot_fit_size: 0x60000 => 0xa0000

spl md5sum: 75e284ed014b5a8bbe88ff52790e46a5: OK
rec-u-boot md5sum: a374a0e5c3c4f30564f412fe2d73d6ca: OK

Lockbit: [1]
SPL FIT offset: 81524
  SPL KEK: key-obmc-compute-kek-0 (sha256,rsa4096) (signs image)

Subordinate timestamp: Fri Oct 09 23:01:05 UTC 2020 (0x5f80ebb1)
Subordinate keys signing key: obmc-compute-kek-0
Subordinate keys hash (sha256): c4f9bdcb2f8a8ba32a60499e38d3d917d4e4d052b8fa12f2530199820b84cb07: OK
  Subordinate: key-obmc-compute-sub-0 (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: obmc-compute-sub-0
U-Boot hash (sha256): e27b18ff224878be0a8757ec1f9775e756af09bb9cb6ba2a8e4e0e55f77bf49d: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: obmc-compute-sub-0
Kernel hash (sha256): d0a2019d83c02dbd09cff7d606039d8cf5d003f632391b474246534732d697d9: OK
Ramdisk hash (sha256): 8116e547f10dfe0ea950cf4758ba5bdf0c78f71bbf3d7df33508c162c4c5be82: OK

========== flash-grandcanyon.timeback.signed ========
Try loading image meta from image flash-grandcanyon.timeback.signed
override args.rom_size: 0x15000 => 0x40000
override args.uboot_fit_offset: 0x80000 => 0x100000
override args.uboot_fit_size: 0x60000 => 0xa0000

spl md5sum: d7837dd0e80df7a3c8ee173800b73e1f: OK
rec-u-boot md5sum: a374a0e5c3c4f30564f412fe2d73d6ca: OK

Lockbit: not set
SPL FIT offset: 81524
  SPL KEK: key-obmc-compute-kek-0 (sha256,rsa4096) (signs image)

Subordinate timestamp: Fri Oct 09 23:01:05 UTC 2020 (0x5f80ebb1)
Subordinate keys signing key: obmc-compute-kek-0
Subordinate keys hash (sha256): c4f9bdcb2f8a8ba32a60499e38d3d917d4e4d052b8fa12f2530199820b84cb07: OK
  Subordinate: key-obmc-compute-sub-0 (sha256,rsa4096) (signs conf)

U-Boot timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
U-Boot configuration signing key: obmc-compute-sub-0
U-Boot hash (sha256): e27b18ff224878be0a8757ec1f9775e756af09bb9cb6ba2a8e4e0e55f77bf49d: OK

Kernel/ramdisk timestamp: Thu Feb 20 08:00:00 UTC 2020 (0x5e4e3c80)
Kernel/ramdisk configuration signing key: obmc-compute-sub-0
Kernel hash (sha256): d0a2019d83c02dbd09cff7d606039d8cf5d003f632391b474246534732d697d9: OK
Ramdisk hash (sha256): 8116e547f10dfe0ea950cf4758ba5bdf0c78f71bbf3d7df33508c162c4c5be82: OK

========== flash-grandcanyon.unsigned.signed ========
Try loading image meta from image flash-grandcanyon.unsigned.signed
override args.rom_size: 0x15000 => 0x40000
override args.uboot_fit_offset: 0x80000 => 0x100000
override args.uboot_fit_size: 0x60000 => 0xa0000

spl md5sum: d7837dd0e80df7a3c8ee173800b73e1f: OK
rec-u-boot md5sum: a374a0e5c3c4f30564f412fe2d73d6ca: OK

Lockbit: not set
SPL FIT offset: 81524
  SPL KEK: key-obmc-compute-kek-0 (sha256,rsa4096) (signs image)

Subordinate timestamp: Fri Oct 09 23:01:05 UTC 2020 (0x5f80ebb1)
Subordinate keys signing key: obmc-compute-kek-0
Subordinate keys hash (sha256): c4f9bdcb2f8a8ba32a60499e38d3d917d4e4d052b8fa12f2530199820b84cb07: OK
  Subordinate: key-obmc-compute-sub-0 (sha256,rsa4096) (signs conf)

U-Boot timestamp: Wed Apr 28 05:57:33 UTC 2021 (0x6088f94d)
U-Boot configuration signing key: obmc-compute-sub-0
U-Boot hash (sha256): e27b18ff224878be0a8757ec1f9775e756af09bb9cb6ba2a8e4e0e55f77bf49d: OK

Kernel/ramdisk timestamp: Wed Apr 28 05:57:49 UTC 2021 (0x6088f95d)
Kernel/ramdisk configuration signing key: obmc-compute-sub-0
Kernel hash (sha256): d0a2019d83c02dbd09cff7d606039d8cf5d003f632391b474246534732d697d9: OK
Ramdisk hash (sha256): 8116e547f10dfe0ea950cf4758ba5bdf0c78f71bbf3d7df33508c162c4c5be82: OK
[zhdaniel@devvm4263.ftw0 ~/release/fbgc/resign]

```

Test time forward to max 32bit epoch
```
[ ~/release/fbttn/resgin] vboot-check flash-brycecanyon1.locked.ffff.signed
Try loading image meta from image flash-brycecanyon1.locked.ffff.signed
No image meta found: ValueError('No JSON object could be decoded',)
verifying legacy image
Lockbit: [1]
SPL FIT offset: 68040
  SPL KEK: key-kek (sha256,rsa4096) (signs image)

Subordinate timestamp: Thu Jun 13 22:03:04 UTC 2019 (0x5d02c818)
Subordinate keys signing key: kek
Subordinate keys hash (sha256): 0b544f76121771ac064e507d68313747efff3c2c6ad6de5f1b46f5104bbbbbaa: OK
  Subordinate: key-subordinate (sha256,rsa4096) (signs conf)

U-Boot timestamp: Sun Feb 07 06:28:15 UTC 2106 (0xffffffff)
U-Boot configuration signing key: subordinate
U-Boot hash (sha256): ee833067d9222f6689aaeb00dddc130f42d12fc06e16faca86871a493f89a7d8: OK

Kernel/ramdisk timestamp: Sun Feb 07 06:28:15 UTC 2106 (0xffffffff)
Kernel/ramdisk configuration signing key: subordinate
Kernel hash (sha256): 889900c008c5f4666ea534f3213deb2be0728aecdabae18c71e53c94f60c037d: OK
Ramdisk hash (sha256): b1df95a203a58dca6793cf90e35e5fa416ae39e13a68031dc7745ce62b67c4fa: OK

```

Test overflow and underflow
```
[~/release/fbttn/resgin] ~/workspaces/openbmc/tools/verified-boot/signing/fit-sign --time-back -1 flash-brycecanyon1.locked flash-brycecanyon1.locked.ffff
Try loading image meta from image flash-brycecanyon1.locked
No image meta found: ValueError('No JSON object could be decoded',)
Signing legacy image
Traceback (most recent call last):
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 600, in <module>
    sys.exit(main())
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 334, in main
    fdt = inject_timeback(uboot_fit, args.time_back)
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 309, in inject_timeback
    new_prop = pyfdt.FdtPropertyWords('timeback', [timeback])
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/pyfdt/pyfdt.py", line 260, in __init__
    "Invalid word value %d, requires 0 <= number <= 4294967295" % word
Exception: Invalid word value -1, requires 0 <= number <= 4294967295

[~/release/fbttn/resgin] ~/workspaces/openbmc/tools/verified-boot/signing/fit-sign --time-back $(( 0xFFFFFFFF + 1 )) flash-brycecanyon1.locked flash-brycecanyon1.locked.ffff
Try loading image meta from image flash-brycecanyon1.locked
No image meta found: ValueError('No JSON object could be decoded',)
Signing legacy image
Traceback (most recent call last):
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 600, in <module>
    sys.exit(main())
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 334, in main
    fdt = inject_timeback(uboot_fit, args.time_back)
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/fit-sign", line 309, in inject_timeback
    new_prop = pyfdt.FdtPropertyWords('timeback', [timeback])
  File "/data/users/zhdaniel/workspaces/openbmc/tools/verified-boot/signing/pyfdt/pyfdt.py", line 260, in __init__
    "Invalid word value %d, requires 0 <= number <= 4294967295" % word
Exception: Invalid word value 4294967296, requires 0 <= number <= 4294967295

```

Reviewed By: williamspatrick

Differential Revision: D28046678

fbshipit-source-id: aa59eb094d