fby3: Block the 12V-on/off in Class 2 config (#970)
Summary:
- As title, block 12V-on/off in class 2 since this can't be recovered.

-Remove the workaround for skipping the sensor list of class 1 on class 2,
since the sensor list of NIC EXP BMC is declared.

-Remove the unused sensors.
M2A_TEMP device does not support to read the temperature.
P3V3_VOL is not used in DVT stage.

Only support 12V-cycle on class 2.
Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/970

Test Plan:
-build code(pass)
-fail to run `12V-on/off` on class 2(pass)
-run `sensor-util bmc` on class 1/2(pass)

Class 1:
root@bmc-oob:~# power-util slot2 status
Power status for fru 2 : ON
root@bmc-oob:~# power-util slot2 12V-off
12V Powering fru 2 to OFF state...
root@bmc-oob:~# power-util slot2 status
Power status for fru 2 : OFF (12V-OFF)
root@bmc-oob:~# power-util slot2 12V-on
12V Powering fru 2 to ON state...
root@bmc-oob:~# power-util slot2 status
Power status for fru 2 : ON
root@bmc-oob:~# power-util slot2 12V-cycle
12V Power cycling fru 2...
root@bmc-oob:~# power-util slot2 status
Power status for fru 2 : ON
root@bmc-oob:~#

root@bmc-oob:~# sensor-util bmc
BMC_OUTLET_TEMP              (0xEE) :   30.50 C     | (ok)
BMC_INLET_TEMP               (0xED) :   29.50 C     | (ok)
BMC_SENSOR_P5V               (0xF0) :    5.05 Volts | (ok)
BMC_SENSOR_P12V              (0xF1) :   12.39 Volts | (ok)
BMC_SENSOR_P3V3_STBY         (0xF2) :    3.27 Volts | (ok)
BMC_SENSOR_P1V15_STBY        (0xF3) :    1.14 Volts | (ok)
BMC_SENSOR_P1V2_STBY         (0xF4) :    1.19 Volts | (ok)
BMC_SENSOR_P2V5_STBY         (0xF5) :    2.51 Volts | (ok)
BMC_SENSOR_HSC_TEMP          (0xF8) :   27.38 C     | (ok)
BMC_SENSOR_HSC_VIN           (0xF7) :   12.48 Volts | (ok)
BMC_SENSOR_HSC_PIN           (0xF9) :   16.53 Watts | (ok)
BMC_SENSOR_HSC_IOUT          (0xFA) :    1.31 Amps  | (ok)
BMC_SENSOR_P12V_MEDUSA       (0xF6) :   12.52 Volts | (ok)
BMC_SENSOR_FAN_IOUT          (0xFB) :    0.00 Amps  | (ok)
BMC_SENSOR_NIC_IOUT          (0xFC) :    1.37 Amps  | (ok)

Class 2:
root@bmc-oob:~# power-util slot1 12V-off
12V Powering fru 1 to OFF state...
ERROR: power-util fru[1] [12V_OFF] failed
root@bmc-oob:~# bic-util slot1 0x18 0x01
25 80 11 13 02 BF 4C 1C 00 39 30 00 00 00 00
root@bmc-oob:~# power-util slot1 12V-on
12V Powering fru 1 to ON state...
ERROR: power-util fru[1] [12V_ON] failed
root@bmc-oob:~# bic-util slot1 0x18 0x01
25 80 11 13 02 BF 4C 1C 00 39 30 00 00 00 00
root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
packet_write_wait: Connection to 192.168.88.157 port 22: Broken pipe

root@bmc-oob:~# sensor-util bmc
BMC_OUTLET_TEMP              (0xEE) :   31.50 C     | (ok)
BMC_SENSOR_P5V               (0xF0) :    4.91 Volts | (ok)
BMC_SENSOR_P12V              (0xF1) :   11.77 Volts | (ok)
BMC_SENSOR_P3V3_STBY         (0xF2) :    3.27 Volts | (ok)
BMC_SENSOR_P1V15_STBY        (0xF3) :    1.13 Volts | (ok)
BMC_SENSOR_P1V2_STBY         (0xF4) :    1.18 Volts | (ok)
BMC_SENSOR_P2V5_STBY         (0xF5) :    2.49 Volts | (ok)
BMC_SENSOR_FAN_IOUT          (0xFB) :    0.00 Amps  | (ok)
BMC_SENSOR_NIC_IOUT          (0xFC) :    0.00 Amps  | (ok)

Reviewed By: williamspatrick

Differential Revision: D20469860

Pulled By: benwei13

fbshipit-source-id: c7c53cb9be