Fix pal and sdr import errors in unit test env
Summary: Fix test_get_chassis_thermal pal and sdr import errors using sys.

Test Plan:
ptest
```
[adeelzafar@devvm3090.prn0 ~/local/openbmc] ./tests2/ptest-runner rest-api
Found 498 recipes of which 13 define unit-tests
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be foundTA:  --:--:--
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for nativesdk-rest-api SRC_URI entry fake_pal.py: file could not be found 0:00:35
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for nativesdk-rest-api SRC_URI entry fake_sdr.py: file could not be found
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for rest-api-native SRC_URI entry fake_pal.py: file could not be found
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for rest-api-native SRC_URI entry fake_sdr.py: file could not be found
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for rest-api SRC_URI entry fake_pal.py: file could not be found
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb: Unable to get checksum for rest-api SRC_URI entry fake_sdr.py: file could not be found
Parsing recipes: 100% |#######################################################################################################################################################################################| Time: 0:00:13
WARNING: No recipes available for:
  /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-tpm2/tpm2-tools/tpm2-tools_3.2.0.bbappend
Initialising tasks: 100% |####################################################################################################################################################################################| Time: 0:00:03
WARNING: rest-api-0.1-r1 do_fetch: Failed to fetch URL file://fake_pal.py, attempting MIRRORS if available
ERROR: rest-api-0.1-r1 do_fetch: Fetcher failure: Unable to find file file://fake_pal.py anywhere. The paths that were searched were:
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/poky
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/poky
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/poky
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/qemux86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/qemux86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/qemux86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/qemuall
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/qemuall
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/qemuall
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/x86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/x86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/x86
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/i686
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/i686
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/i686
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api-0.1/
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api/
    /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/files/
    /data/users/adeelzafar/openbmc/build-qemux86/downloads
ERROR: rest-api-0.1-r1 do_fetch: Fetcher failure for URL: 'file://fake_pal.py'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /data/users/adeelzafar/openbmc/build-qemux86/tmp/work/core2-32-fb-linux/rest-api/0.1-r1/temp/log.do_fetch.221866
ERROR: Task (/data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-rest/rest-api/rest-api_0.1.bb:do_fetch) failed with exit code '1'
Traceback (most recent call last):
  File "./tests2/ptest-runner", line 222, in <module>
    main(args)
  File "./tests2/ptest-runner", line 116, in main
    bmc_build(all_recipes, args.build, args.verbose)
  File "./tests2/ptest-runner", line 94, in bmc_build
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env', '-i', 'HOME=/home/adeelzafar', 'bash', '-l', '-c', 'cd /data/users/adeelzafar/openbmc; source ./openbmc-init-build-env qemux86 /data/users/adeelzafar/openbmc/build-qemux86 > /dev/null; sed -i -n \'/IMAGE_INSTALL_append/!p\' conf/local.conf; echo IMAGE_INSTALL_append = \\"libmisc-utils libipc fscd libgpio-ctrl pypartition libaggregate-sensor libkv rest-api fw-util name-util bios-util log-util attest-util\\" >> conf/local.conf; export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8; export LANGUAGE=en_US.UTF-8; export MACHINE=qemux86; bitbake -q qemux86-image']' returned non-zero exit status 1.
[adeelzafar@devvm3090.prn0 ~/local/openbmc] ./tests2/ptest-runner rest-api
Found 498 recipes of which 13 define unit-tests
WARNING: /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be foundTA:  --:--:--
Parsing recipes: 100% |#######################################################################################################################################################################################| Time: 0:00:12
WARNING: No recipes available for:
  /data/users/adeelzafar/openbmc/yocto/lf-dunfell/poky/../../../common/recipes-tpm2/tpm2-tools/tpm2-tools_3.2.0.bbappend
Initialising tasks: 100% |####################################################################################################################################################################################| Time: 0:00:03
START: ptest-runner
2021-07-19T05:17
BEGIN: /usr/lib/rest-api/ptest
/usr/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:110: DeprecationWarning: "coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def handler_wrapper(*args, **kwargs):
/usr/lib/python3.8/site-packages/aiohttp/helpers.py:141: DeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead
  task = asyncio.Task.current_task(loop=loop)
.Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc310>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc118>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc238>()]>>
./usr/local/fbpackages/rest-api/test_async_ratelimiter.py:88: RuntimeWarning: coroutine 'TestRatelimiterWorks.__assert_normal_request' was never awaited
  self.__assert_normal_request("GET", "agent2")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc550>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc568>()]>>
.Task was destroyed but it is pending!
task: <Task pending name='Task-53' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc4c0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-55' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf65cc0d0>()]>>
............../usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............../usr/lib/python3.8/site-packages/aiohttp/web_server.py:44: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.gather(*coros, loop=self._loop)
...................s...../usr/lib/python3.8/traceback.py:359: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmpnafqwp90' mode='ab' closefd=True>
  result.append(FrameSummary(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
../usr/local/fbpackages/rest-api/test_redfish_common_routes.py:25: DeprecationWarning: .url(...) is deprecated, use .url_for instead
  registered_routes.add(route.url())
./usr/local/fbpackages/rest-api/test_redfish_common_routes.py:65: DeprecationWarning: .url(...) is deprecated, use .url_for instead
  registered_routes.add(route.url())
......................................
----------------------------------------------------------------------
Ran 97 tests in 1.394s

OK (skipped=1)
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
/usr/local/fbpackages/rest-api/acl_config.py                                   1      0   100%
/usr/local/fbpackages/rest-api/acl_providers/__init__.py                       0      0   100%
/usr/local/fbpackages/rest-api/acl_providers/cached_acl_provider.py           37      2    95%   52-53
/usr/local/fbpackages/rest-api/acl_providers/common_acl_provider_base.py      41      1    98%   61
/usr/local/fbpackages/rest-api/async_ratelimiter.py                           18      1    94%   56
/usr/local/fbpackages/rest-api/boardroutes.py                                  1      0   100%
/usr/local/fbpackages/rest-api/common_auth.py                                 56      5    91%   57-60, 139
/usr/local/fbpackages/rest-api/common_logging.py                              32      2    94%   61, 71
/usr/local/fbpackages/rest-api/common_middlewares.py                          50      3    94%   45, 94-95
/usr/local/fbpackages/rest-api/common_utils.py                                56     40    29%   21-29, 43-48, 52-66, 82-87, 95, 101-116
/usr/local/fbpackages/rest-api/common_webapp.py                               13      6    54%   9, 13-19
/usr/local/fbpackages/rest-api/redfish_account_service.py                      7      0   100%
/usr/local/fbpackages/rest-api/redfish_base.py                                10      2    80%   60, 67
/usr/local/fbpackages/rest-api/redfish_chassis.py                             33      6    82%   10-19, 24, 29, 59
/usr/local/fbpackages/rest-api/redfish_chassis_helper.py                      43      5    88%   31-32, 44-45, 60
/usr/local/fbpackages/rest-api/redfish_common_routes.py                       45      1    98%   18
/usr/local/fbpackages/rest-api/redfish_managers.py                            99     46    54%   22-30, 34-46, 50-55, 59-64, 69-91
/usr/local/fbpackages/rest-api/redfish_service_root.py                        13      0   100%
/usr/local/fbpackages/rest-api/rest_config.py                                 37      1    97%   103
/usr/local/fbpackages/rest-api/rest_fruid.py                                  21     16    24%   30-47
/usr/local/fbpackages/rest-api/rest_fscd_sensor_data.py                       30      3    90%   59-62
/usr/local/fbpackages/rest-api/rest_gpios.py                                  22      4    82%   33-59
/usr/local/fbpackages/rest-api/rest_modbus_cmd.py                             86     10    88%   105, 125-128, 133, 137-141, 172
/usr/local/fbpackages/rest-api/rest_pal_legacy.py                            169    141    17%   48-49, 53-68, 72-80, 84-92, 97-105, 109-116, 124-145, 150-197, 201-216, 220-230, 234-236, 240-245, 249-257
/usr/local/fbpackages/rest-api/rest_utils.py                                   6      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                                        926    295    68%
DURATION: 4
END: /usr/lib/rest-api/ptest
2021-07-19T05:17
STOP: ptest-runner
```

Reviewed By: kawmarco

Differential Revision: D29761205

fbshipit-source-id: 688d238f28