qemu: Replace old slirp patches w/ new one I submitted upstream
Summary:
Unfortunately, nobody has reviewed it yet. But I _did_ submit it upstream, and it fixes the QEMU build with old versions of slirp, so probably worthwhile?

https://lore.kernel.org/qemu-devel/20230105091345.49757-2-peter@pjd.dev/

Test Plan:
Before:

```
$ cd openbmc
$ ./facebook/qemu/build.sh
....
[1898/2609] Compiling C object libcommon.fa.p/net_slirp.c.o
FAILED: libcommon.fa.p/net_slirp.c.o
cc -m64 -mcx16 -Ilibcommon.fa.p -I../dtc/libfdt -I/usr/include/pixman-1 -I/usr/include/slirp -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=auto -Wall -Winvalid-pch -std=gnu11 -O2 -isyst
em /data/users/pdel/openbmc/build/workspace/sources/qemu-system-native/linux-headers -isystem linux-headers -iquote . -iquote /data/users/pdel/openbmc/build/workspace/sources/qemu-system-native -iquote /data/users
/pdel/openbmc/build/workspace/sources/qemu-system-native/include -iquote /data/users/pdel/openbmc/build/workspace/sources/qemu-system-native/tcg/i386 -pthread -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D
_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-declaration -Wold-style-definition -
Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=2 -Wno-missing-include-dirs -Wno-shift-negati
ve-value -Wno-psabi -fstack-protector-strong -fPIE -MD -MQ libcommon.fa.p/net_slirp.c.o -MF libcommon.fa.p/net_slirp.c.o.d -o libcommon.fa.p/net_slirp.c.o -c ../net/slirp.c
../net/slirp.c: In function ‘net_slirp_init’:
../net/slirp.c:638:8: error: ‘SlirpConfig’ {aka ‘struct SlirpConfig’} has no member named ‘mfr_id’
     cfg.mfr_id = mfr_id;
        ^
../net/slirp.c:639:16: error: ‘SlirpConfig’ {aka ‘struct SlirpConfig’} has no member named ‘oob_eth_addr’; did you mean ‘outbound_addr’?
     memcpy(cfg.oob_eth_addr, oob_eth_addr, ETH_ALEN);
                ^~~~~~~~~~~~
                outbound_addr
[1935/2609] Compiling C object libqemu-aarch64-softmmu.fa.p/target_arm_ptw.c.o
ninja: build stopped: subcommand failed.
```

After:

```
$ sudo dnf --refresh install libslirp-devel
$ cd openbmc
$ ./facebook/qemu/build.sh
....
-enable-sync-profile
                enable synchronization profiling

Generic object creation:
-object TYPENAME[,PROP1=VALUE1,...]
                create a new object of type TYPENAME setting properties
                in the order they are specified.  Note that the 'id'
                property must be set.  These objects are placed in the
                '/objects' path.

During emulation, the following keys are useful:
ctrl-alt-f      toggle full screen
ctrl-alt-n      switch to virtual console 'n'
ctrl-alt        toggle mouse and keyboard grab

When using -nographic, press 'ctrl-a h' to get some help.

See <https://qemu.org/contribute/report-a-bug> for how to report bugs.
More information on the QEMU project at <https://qemu.org>.
```

Reviewed By: zhdaniel12

Differential Revision: D43015596

fbshipit-source-id: 31c91ea5e685e99be309bac335043b0b8c27e025