fby35: fix setting unused HSC (#2604)
Summary:
Root cause:
Since there is more than one type of HSC. When BMC boot up, these setting will cause write fail if is not using ADM1278.

Solution:
Check the MFR ID before setting the register.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/2604

Test Plan:
1. Build and test pass on YV3.5 system. pass

2. Check the console log. (1) Before fix
Error: Write failed
Error: Write failed
Error: Write failed
Setup sensor monitoring for FBYV35... done.

(2) After fix
Get MB FW version...
Setup sensor monitoring for FBYV35... done.

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: williamspatrick, wangx6f

Differential Revision: D45680111

fbshipit-source-id: c2c37fbfe9b4a5623905ce7f1a87698f0047b1ad