log-util-v2: Support for dynamic FRU lists
Summary:
Support platforms which self detect and change
FRU list based on the detection. This would
require the switch from using the pal_fru_list
(const char*) to pal_get_fru_list().

Test Plan:
Build AL and load on QEMU
```
root@bmc-oob:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,bmc,mb,nic0,nic1,pdb,sys} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU
```

Reviewed By: benwei13

Differential Revision: D22459335

fbshipit-source-id: cc4210e76a