tests2: fbgc: rest-api and me-util: fix and update (#1789)
Summary:
1. Update Server fru information let rest-api test successfully on EVT and DVT system.
2. Fix test_me_set_nm_power ValueError when BMC IPv6 encounter hex number(a~f).

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1789

Test Plan:
1. Built and test pass on Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and SELs.

3. Check test_rest_endpoints can successful.
(1) Copy file
root@guaigaui-Freedom:~/Sara# scp -r tests2 192.168.88.46:/usr/local/bin

(2) Run CIT test on BMC
- Before update
root@bmc-oob:~# cd /usr/local/bin/tests2/
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --run-test  tests.fbgc.test_rest_endpoint.RestEnd       pointTest.test_rest_endpoints
test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) ...
======================================================================
FAIL: test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) (attrib='Chassis Part Number')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 157, in verify_endpoint_attributes
    msg="endpoint {} missing attrib {}".format(endpointname, attrib),
AssertionError: 'Chassis Part Number' not found in '{"Information": {"Chassis Type": "Rack Mount Chassis", "Chassis Custom Data 1": "CPU-SN-Reserved", "Board Mfg Date": "Fri Jul  9 22:54:00 2021", "Board Mfg": "Wiwynn", "Board Product": "Barton Springs", "Board Serial": "WR2312503SZSA", "Board Part Number": "B81.04910.0123", "Board FRU ID": "1.0", "Board Custom Data 1": "02-000444", "Board Custom Data 2": "PCB Supplier - GCE", "Product Manufacturer": "Wiwynn", "Product Name": "Barton Springs DVT", "Product Part Number": "BZA.04901.0027", "Product Version": "DVT", "Product Serial": "BZAR2712800KZSA", "Product Asset Tag": "AS76254", "Product FRU ID": "1.0", "Product Custom Data 1": "01-005758"}, "Actions": [], "Resources": []}' : endpoint /api/server/fruid missing attrib Chassis Part Number

======================================================================
FAIL: test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) (attrib='Chassis Serial Number')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 157, in verify_endpoint_attributes
    msg="endpoint {} missing attrib {}".format(endpointname, attrib),
AssertionError: 'Chassis Serial Number' not found in '{"Information": {"Chassis Type": "Rack Mount Chassis", "Chassis Custom Data 1": "CPU-SN-Reserved", "Board Mfg Date": "Fri Jul  9 22:54:00 2021", "Board Mfg": "Wiwynn", "Board Product": "Barton Springs", "Board Serial": "WR2312503SZSA", "Board Part Number": "B81.04910.0123", "Board FRU ID": "1.0", "Board Custom Data 1": "02-000444", "Board Custom Data 2": "PCB Supplier - GCE", "Product Manufacturer": "Wiwynn", "Product Name": "Barton Springs DVT", "Product Part Number": "BZA.04901.0027", "Product Version": "DVT", "Product Serial": "BZAR2712800KZSA", "Product Asset Tag": "AS76254", "Product FRU ID": "1.0", "Product Custom Data 1": "01-005758"}, "Actions": [], "Resources": []}' : endpoint /api/server/fruid missing attrib Chassis Serial Number

======================================================================
FAIL: test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) (attrib='Product Custom Data 2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 157, in verify_endpoint_attributes
    msg="endpoint {} missing attrib {}".format(endpointname, attrib),
AssertionError: 'Product Custom Data 2' not found in '{"Information": {"Chassis Type": "Rack Mount Chassis", "Chassis Custom Data 1": "CPU-SN-Reserved", "Board Mfg Date": "Fri Jul  9 22:54:00 2021", "Board Mfg": "Wiwynn", "Board Product": "Barton Springs", "Board Serial": "WR2312503SZSA", "Board Part Number": "B81.04910.0123", "Board FRU ID": "1.0", "Board Custom Data 1": "02-000444", "Board Custom Data 2": "PCB Supplier - GCE", "Product Manufacturer": "Wiwynn", "Product Name": "Barton Springs DVT", "Product Part Number": "BZA.04901.0027", "Product Version": "DVT", "Product Serial": "BZAR2712800KZSA", "Product Asset Tag": "AS76254", "Product FRU ID": "1.0", "Product Custom Data 1": "01-005758"}, "Actions": [], "Resources": []}' : endpoint /api/server/fruid missing attrib Product Custom Data 2

----------------------------------------------------------------------
Ran 1 test in 15.016s

FAILED (failures=3)

- After update
(1) On EVT system
root@bmc-oob:~# fruid-util server

FRU Information           : Barton Springs
---------------           : ------------------
Chassis Type              : Rack Mount Chassis
Chassis Part Number       :
Chassis Serial Number     :
Board Mfg Date            : Mon Jul 10 17:01:00 2017
Board Mfg                 : Wiwynn
Board Product             : GCSCC001
Board Serial              :
Board Part Number         :
Product Manufacturer      : Wiwynn
Product Name              : GrandCanyon
Product Part Number       :
Product Version           : Q
Product Serial            :
Product Asset Tag         :
Product Custom Data 1     :

root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --run-test  tests.fbgc.test_rest_endpoint.RestEndpointTest.test_rest_endpoints
test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 15.994s

OK

(2) On DVT system
root@bmc-oob:/usr/local/bin/tests2# fruid-util server

FRU Information           : Barton Springs
---------------           : ------------------
Chassis Type              : Rack Mount Chassis
Chassis Custom Data 1     : CPU-SN-Reserved
Board Mfg Date            : Mon Jul 19 15:53:00 2021
Board Mfg                 : Wiwynn
Board Product             : Barton Springs
Board Serial              : WR2612803TZSA
Board Part Number         : B81.04910.0126
Board FRU ID              : 1.0
Board Custom Data 1       : 02-000444
Board Custom Data 2       : PCB Supplier - TRI
Product Manufacturer      : Wiwynn
Product Name              : Barton Springs DVT
Product Part Number       : BZA.04901.0030
Product Version           : DVT
Product Serial            : BZAR30129016ZSA
Product Asset Tag         : AS76013
Product FRU ID            : 1.0
Product Custom Data 1     : 01-005758

root@bmc-oob:~# cd /usr/local/bin/tests2/
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --run-test  tests.fbgc.test_rest_endpoint.RestEndpointTest.test_rest_endpoints
test_rest_endpoints (tests.fbgc.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 15.702s

OK

4. Check test_me_set_nm_power can successful.
(1) Copy file
[root@gc-golden ~]# scp -r tests2 192.168.88.48:/usr/local/bin

(2) Run CIT test on host
- Before update
[root@gc-golden ~]# cd /usr/local/bin/tests2/
[root@gc-golden tests2]# python3.6 cit_runner.py --run-test tests.fbgc.external_me_set_power_test.MESetPowerTest
test_me_set_nm_power (tests.fbgc.external_me_set_power_test.MESetPowerTest) ... ERROR

======================================================================
ERROR: test_me_set_nm_power (tests.fbgc.external_me_set_power_test.MESetPowerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_me_set_power_test.py", line 52, in setUp
    self.set_ssh_session_bmc_hostname()
  File "/usr/local/bin/tests2/tests/fbgc/external_me_set_power_test.py", line 34, in set_ssh_session_bmc_hostname
    int(raw_ip[16]),
ValueError: invalid literal for int() with base 10: '5f\n'

----------------------------------------------------------------------
Ran 1 test in 0.045s

FAILED (errors=1)

- After update
[root@gc-golden ~]# cd /usr/local/bin/tests2/
[root@gc-golden tests2]# python3.6 cit_runner.py --run-test tests.fbgc.external_me_set_power_test.MESetPowerTest
test_me_set_nm_power (tests.fbgc.external_me_set_power_test.MESetPowerTest) ...
Connecting to BMC ...
Done
Set power limit ...
Done
Run power stress ...
Get power ...
Check power ...
ok

----------------------------------------------------------------------
Ran 1 test in 74.765s

OK

Reviewed By: benwei13

Differential Revision: D30653463

Pulled By: zhdaniel12

fbshipit-source-id: 9f9f2d9ccb