psu-update: Add support to verify firmware
Summary:
Add support for verifying firmware while maintaining
support to perform firmware upgrades on older
versions. This allows one to continue exiting boot-mode
if verification fails thus "working" with older
versions while simultaneously printing an error to alert
the user that something is wrong.

Test Plan:
Check we can upgrade firmware on older versions
```
root@bmc-oob:~/FW_Update_Test# orv3-device-update-mailbox.py --addr 97 ./FW13H-01.bin
statusfile None
[100.00%] Sending block 3602 of 3602...
Firmware update failed ('Bad firmware state: ', 6)
<snip>
ValueError: ('Bad firmware state: ', 6)
```
But comes up with the expected good firmware version:
```
root@bmc-oob:~/FW_Update_Test# rackmoncli data --dev-addr 97 --reg-addr 0x38
<snip>
  FW Revision<0x0038> : "013H-01 "
```
Upgrade with the next version, this should succeed since 13H-01 added the
verify support
```
root@bmc-oob:~/FW_Update_Test# orv3-device-update-mailbox.py --addr 97 ./FW13H-02.bin
statusfile None
[100.00%] Sending block 3602 of 3602...
Resetting....
Resuming monitoring...
Upgrade success
```
Check upgrade was performed
```
root@bmc-oob:~/FW_Update_Test# rackmoncli data --dev-addr 97 --reg-addr 0x38
<snip>
  FW Revision<0x0038> : "013H-02 "
```

Reviewed By: garnermic

Differential Revision: D38962799

fbshipit-source-id: 560c0c5a53a49740063ecc600c43b3dc1ba7ee3b