Board routes index update
Summary:
Rest server failed to start due to this issue :
root@rsw1ag-oob:/usr/local/bin/tests2# python3 /usr/local/bin/rest.py
Traceback (most recent call last):
  File "/usr/local/bin/rest.py", line 61, in <module>
    setup_board_routes(app)
  File "/usr/local/fbpackages/rest-api/board_setup_routes.py", line 25, in setup_board_routes
    app.router.add_get(board_routes[2], bhandler.helper_modbus_registers_hdl)
IndexError: list index out of range

Test Plan:
scp the file and run rest server and test is is accessible
root@rsw1ag-oob:/usr/local/bin/tests2# curl -g http://localhost:8080/api
{"Actions": [], "Resources": ["sys"], "Information": {"version": "v0.1", "Description": "Wedge RESTful API Entry"}}root@rsw1ag-oob:/usr/local/bin/tests2#
root@rsw1ag-oob:/usr/local/bin/tests2#

Reviewed By: benwei13

Differential Revision: D14435911

fbshipit-source-id: 276cdc56fd