=?UTF-8?q?[openbmc.quanta][PR]=20fw-util:=20vr:=20enhance?= =?UTF-8?q?d=20version=20display=20and=20implement=20safeguard=20for=20inf?= =?UTF-8?q?=E2=80=A6?= (#1890)
Summary:
…ineon VRs
1. add vendor info: xdpe12284c, pxe1110c, tps53688, and mpq8645p
   add remaining writes: xdpe12284c and pxe1110c

2. enhanced display in JSON format (--version-json):
   xdpe12284c, pxe1110c, tps53688, and mpq8645p

3. prevent firmware update when rmng_w goes below 3 and allow only if --force is provided:
   xdpe12284c and pxe1110c

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1890

Test Plan:
Build and test pass on fbal and fbep

(1) fw-util vr --version
On fbal:
VR_CPU0_VCCIN/VCCSA Version: Infineon 879E0D21, Remaining Writes: 25
VR_CPU0_VCCIO Version: Infineon D0B85216, Remaining Writes: 25
VR_CPU0_VDDQ_ABC Version: Infineon 2C89744A, Remaining Writes: 26
VR_CPU0_VDDQ_DEF Version: Infineon 2C89744A, Remaining Writes: 26
VR_CPU1_VCCIN/VCCSA Version: Infineon 879E0D21, Remaining Writes: 25
VR_CPU1_VCCIO Version: Infineon D0B85216, Remaining Writes: 25
VR_CPU1_VDDQ_ABC Version: Infineon 2C89744A, Remaining Writes: 26
VR_CPU1_VDDQ_DEF Version: Infineon 2C89744A, Remaining Writes: 26
VR_PCH_PVNN/P1V05 Version: Infineon BCBA1E93, Remaining Writes: 11

root@bmc-oob:~# fw-util vr --version-json
[
    {
        "COMPONENT": "cpu0_vccin",
        "FRU": "vr",
        "VERSION": "879e0d21",
        "rmng_w": "25",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu0_vccio",
        "FRU": "vr",
        "VERSION": "d0b85216",
        "rmng_w": "25",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu0_vddq_abc",
        "FRU": "vr",
        "VERSION": "2c89744a",
        "rmng_w": "26",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu0_vddq_def",
        "FRU": "vr",
        "VERSION": "2c89744a",
        "rmng_w": "26",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu1_vccin",
        "FRU": "vr",
        "VERSION": "879e0d21",
        "rmng_w": "25",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu1_vccio",
        "FRU": "vr",
        "VERSION": "d0b85216",
        "rmng_w": "25",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu1_vddq_abc",
        "FRU": "vr",
        "VERSION": "2c89744a",
        "rmng_w": "26",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "cpu1_vddq_def",
        "FRU": "vr",
        "VERSION": "2c89744a",
        "rmng_w": "26",
        "vendor": "infineon"
    },
    {
        "COMPONENT": "pch_pvnn",
        "FRU": "vr",
        "VERSION": "bcba1e93",
        "rmng_w": "11",
        "vendor": "infineon"
    }
]

On fbep:
root@bmc-oob:~# fw-util vr --version
VR_P0V8_VDD0 Version: MPS 0x31
VR_P0V8_VDD1 Version: MPS 0x31
VR_P0V8_VDD2 Version: MPS 0x31
VR_P0V8_VDD3 Version: MPS 0x31
VR_P1V0_AVD0 Version: MPS 0x30
VR_P1V0_AVD1 Version: MPS 0x30
VR_P1V0_AVD2 Version: MPS 0x30
VR_P1V0_AVD3 Version: MPS 0x30

root@bmc-oob:~# fw-util vr --version-json
[
    {
        "COMPONENT": "p0v8_vdd0",
        "FRU": "vr",
        "VERSION": "0x31",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p0v8_vdd1",
        "FRU": "vr",
        "VERSION": "0x31",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p0v8_vdd2",
        "FRU": "vr",
        "VERSION": "0x31",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p0v8_vdd3",
        "FRU": "vr",
        "VERSION": "0x31",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p1v0_avd0",
        "FRU": "vr",
        "VERSION": "0x30",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p1v0_avd1",
        "FRU": "vr",
        "VERSION": "0x30",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p1v0_avd2",
        "FRU": "vr",
        "VERSION": "0x30",
        "vendor": "mps"
    },
    {
        "COMPONENT": "p1v0_avd3",
        "FRU": "vr",
        "VERSION": "0x30",
        "vendor": "mps"
    }
]

(2) safeguard for Infineon VRs
root@bmc-oob:~# fw-util vr --update cpu0_vccin /tmp/F0C_PVCCIN_CPU0_C0_DVT_rev00_879E0D21_20200528.xsf
Update VR: VR_CPU0_VCCIN/VCCSA
File CRC : 879E0D21
Remaining writes: 3
WARNING: the remaining writes is below the threshold value 3!
Please use "--force" option to try again.
CRC 9C30587A mismatch, expect 879E0D21
ERROR: VR Firmware update failed!
Upgrade of vr : cpu0_vccin failed

root@bmc-oob:~# fw-util vr --force --update cpu0_vccin /tmp/F0C_PVCCIN_CPU0_C0_DVT_rev00_879E0D21_20200528.xsf
Update VR: VR_CPU0_VCCIN/VCCSA
File CRC : 879E0D21
Remaining writes: 3
Memory pointer: 0x74
updated: 100 %
Force upgrade of vr : cpu0_vccin succeeded

root@bmc-oob:~# fw-util vr --update pch_pvnn /tmp/F0C_PVNN_1V05pch_initial_rev00_BCBA1E93_20191012.psf
Update VR: VR_PCH_PVNN/P1V05
File CRC : BCBA1E93
Remaining writes: 3
WARNING: the remaining writes is below the threshold value 3!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of vr : pch_pvnn failed

root@bmc-oob:~# fw-util vr --force --update pch_pvnn /tmp/F0C_PVNN_1V05pch_initial_rev00_BCBA1E93_20191012.psf
Update VR: VR_PCH_PVNN/P1V05
File CRC : BCBA1E93
Remaining writes: 3
updated: 100 %
Force upgrade of vr : pch_pvnn succeeded

Reviewed By: benwei13

Differential Revision: D23327173

fbshipit-source-id: d4dccc65d1