cit,fby3: Add mboot_test
Summary:
Add a mboot_test to make sure all to be attested components will be measured correctly.
Currently we will attesting "spl",

Test Plan:
Good test
```
root@dhcp-100-96-192-227:/usr/local/bin/tests2# ./cit_runner.py --platform fby3
test_mboot (tests.fby3.test_mboot.FBY3MBootTest)
Test all measures ... ok

----------------------------------------------------------------------
Ran 1 test in 18.528s

OK

```
Negative test, extend a value in current PCR0 and run test again
```
root@dhcp-100-96-192-227:/usr/local/bin/tests2# tpm2_pcrextend 0:sha256=11223344556677889900112233445566778899001
1223344556677889900aabb
root@dhcp-100-96-192-227:/usr/local/bin/tests2# ./cit_runner.py --platform fby3
test_mboot (tests.fby3.test_mboot.FBY3MBootTest)
Test all measures ... FAIL

======================================================================
FAIL: test_mboot (tests.fby3.test_mboot.FBY3MBootTest)
Test all measures
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/volatile/tmp/tests2/common/base_mboot_test.py", line 50, in test_mboot
    self.assertEqual(m["expect"], m["measure"])
AssertionError: '683cf87958e0ce925e7edd34bed2a25bc7428d05391dcfaeb5242e1f3131e562' != '89024a9c407225083c49b7a2a8a0bc9e71500723d880c67a3322fcc7dcdfde29'
- 683cf87958e0ce925e7edd34bed2a25bc7428d05391dcfaeb5242e1f3131e562
+ 89024a9c407225083c49b7a2a8a0bc9e71500723d880c67a3322fcc7dcdfde29

----------------------------------------------------------------------
Ran 1 test in 20.479s

FAILED (failures=1)
root@dhcp-100-96-192-227:/usr/local/bin/tests2#

```

Reviewed By: benwei13

Differential Revision: D23809925

fbshipit-source-id: 1c3b227529