meta-fboss-lite: mTerm: do not launch microcom from sol.sh
Summary:
Do not launch "microcom" from sol.sh when mTerm_server is not running
(usually at early bootup time), because an active microcom session could
block console access from all the future sol.sh instances.

Test Plan:
1) "bitbake montblanc-image" passed.
2) ondiff CIT passed.

root@bmc-oob:~# sol.sh

------------------TERMINAL MULTIPLEXER---------------------
  CTRL-l ?   : Display help message.
  CTRL-l x : Terminate the connection.
  /var/log/mTerm_wedge.log : Log location
  CTRL-l + b : Send Break

-----------------------------------------------------------

CentOS Stream 8
Kernel 6.4.3-0_fbk1_755_ga25447393a1d on an x86_64

montblanc login: Connection closed.
root@bmc-oob:~# systemctl stop mTerm_server
root@bmc-oob:~# sol.sh
Error: mTerm_server is Not running!
If the system rebooted recently, please wait until your system has
been up for at least 5 minutes.
If mTerm_server service is down unexpectedly, please reach out to
fboss_platform team for support.
Use <microcom -s 57600 /dev/ttyS4> with caution: an active microcom
session could block console access from all the other sol.sh instances.
Exiting!
root@bmc-oob:~# echo $?
1
root@bmc-oob:~# systemctl start mTerm_server
root@bmc-oob:~# sol.sh

------------------TERMINAL MULTIPLEXER---------------------
  CTRL-l ?   : Display help message.
  CTRL-l x : Terminate the connection.
  /var/log/mTerm_wedge.log : Log location
  CTRL-l + b : Send Break

-----------------------------------------------------------

CentOS Stream 8
Kernel 6.4.3-0_fbk1_755_ga25447393a1d on an x86_64

montblanc login: Connection closed.

Reviewed By: alandau

Differential Revision: D59646728

fbshipit-source-id: 7614fab4fc361fd887cec47628c4c08c6b6d2e66