adding test cases for log-util
Summary:
add 4 new test cases for log-util
1. test CLI: log-util <fru> --print
2. test CLI: log-util <fru> --print --json
3. check output format: log-util <fru> --print
4. check output format: log-util <fru> --print --json

Test Plan:
1. successful test suite run on fbttn platforms:
```
root@dhcp-100-96-192-237:/usr/local/bin/tests2# python cit_runner.py --platform fbttn --run-test tests.fbttn.test_log_util.LogUtilTest
test_show_log (tests.fbttn.test_log_util.LogUtilTest) ... ok
test_show_log_json (tests.fbttn.test_log_util.LogUtilTest) ... ok
test_validate_log_format (tests.fbttn.test_log_util.LogUtilTest) ... ok
test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) ... ok

----------------------------------------------------------------------
Ran 4 tests in 21.315s

OK
```

2. manually introduce incorrect regex to verify the test will fail:
```
root@dhcp-100-96-192-237:/usr/local/bin/tests2# cat tests/fbttn/test_log_util.py | grep APP_NAME
            "APP_NAME": {"idx": 3, "regex": "[a-zA-Z]"}, <-- APP_NAME should have characters exist
root@dhcp-100-96-192-237:/usr/local/bin/tests2# python cit_runner.py --platform fbttn --run-test tests.fbttn.test_log_util.LogUtilTest.test_validate_log_format_json
test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) ...
======================================================================
FAIL: test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) [validate log format json APP_NAME]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fbttn/test_log_util.py", line 114, in test_validate_log_format_json
    self.assertIsNone(rx.search(_out[log_header]))
AssertionError: <_sre.SRE_Match object; span=(0, 1), match='h'> is not None

======================================================================
FAIL: test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) [validate log format json APP_NAME]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fbttn/test_log_util.py", line 114, in test_validate_log_format_json
    self.assertIsNone(rx.search(_out[log_header]))
AssertionError: <_sre.SRE_Match object; span=(0, 1), match='h'> is not None

======================================================================
FAIL: test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) [validate log format json APP_NAME]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fbttn/test_log_util.py", line 114, in test_validate_log_format_json
    self.assertIsNone(rx.search(_out[log_header]))
AssertionError: <_sre.SRE_Match object; span=(0, 1), match='i'> is not None

======================================================================
FAIL: test_validate_log_format_json (tests.fbttn.test_log_util.LogUtilTest) [validate log format json APP_NAME]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/fbttn/test_log_util.py", line 114, in test_validate_log_format_json
    self.assertIsNone(rx.search(_out[log_header]))
AssertionError: <_sre.SRE_Match object; span=(0, 1), match='p'> is not None

----------------------------------------------------------------------
Ran 1 test in 6.059s

FAILED (failures=4)
```

Reviewed By: vineelasmile

Differential Revision: D26763018

fbshipit-source-id: 507926d718