Handle peeking into next mtd
Summary:
verified_read() calls next_image_if_needed() and checks how many bytes
are actually read. But in the peek case, we don't want to update the
bytes_read_or_skipped counter. It turns out that that counter is unused.
So remove that counter update and then use verified_read() in peek() to
prevent the following error:

  2017-10-26 02:56:34,160 ERROR:Unhandled exception raised.
  Traceback (most recent call last):
    File "/tmp/improve_system.py", line 109, in <module>
      improve_system(logger)
    File "/tmp/improve_system.py", line 72, in improve_system
      partitions = system.get_valid_partitions(all_mtds, checksums, logger)
    File "/var/volatile/tmp/system.py", line 219, in get_valid_partitions
      partitions = get_partitions(vc, checksums, logger)
    File "/var/volatile/tmp/system.py", line 180, in get_partitions
      next_magic = images.peek()
    File "/var/volatile/tmp/virtualcat.py", line 107, in peek
      return struct.unpack(b'>I', word)[0]
  error: unpack requires a string argument of length 4

Test Plan:
P58535630

  $ python -m unittest discover -v
  test_partition (test_partition.TestPartition) ... ok
  test_multiple_images_peek_beyond_end (test_virtualcat.TestVirtualCat) ... ok
  test_multiple_images_skip_beyond_end (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_open_close (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_afterword (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_afterword_to_middle (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_buffer (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_buffer_afterword (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_foreword_afterword (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_foreword_buffer (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_read_foreword_buffers_afterword (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_skip_to_end_then_beyond (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_skip_to_middle (test_virtualcat.TestVirtualCat) ... ok
  test_single_image_small_read_past_end (test_virtualcat.TestVirtualCat) ... ok
  test_not_openbmc (test_improve_system.TestImproveSystem) ... ok
  test_flash_competition (test_system.TestSystem) ... ok
  test_flash_retries (test_system.TestSystem) ... ok
  test_flash_too_big (test_system.TestSystem) ... ok
  test_get_mtds_dual_super_fit_mode (test_system.TestSystem) ... ok
  test_get_mtds_single_full_mode (test_system.TestSystem) ... ok
  test_reboot (test_system.TestSystem) ... ok

  ----------------------------------------------------------------------
  Ran 21 tests in 0.173s

  OK

Differential Revision: D6157609

fbshipit-source-id: 3f50bef