fby35: Power lock implementation for class2 (#2323)
Summary:
Implement power lock feature so that while one slot is undergoing a firmware update, the other slot's sled-cycle is disabled.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/2323

Test Plan:
When the component is being fw update, another slot cannot do power sled-cycle.

(1) BB_BIC

One slot do BB_BIC fw update:
root@bmc-oob:~# fw-util slot1 --update bb_bic oby35-bb-2022.28.01.bin
slot_id: 1, comp: 11, intf: 0, img: oby35-bb-2022.28.01.bin, force: 0
Set fan mode to manual and set PWM to 70%
file size = 187400 bytes, slot = 1, intf = 0x10
updating fw on slot 1:
updated bic: 100 %
Elapsed time:  10   sec.

get new SDR cache from BIC
ok: run: sensord: (pid 24606) 0s
Set fan mode to auto and start fscd
Upgrade of slot1 : bb_bic succeeded

Another Slot do sled-cycle at the same time should be fail:
root@bmc-oob:~# power-util sled-cycle
Another slot is doing fw update, cannot do sled cycle.
ERROR: power-util fru[255] [SLED_CYCLE] failed

(2) BB_CPLD

One slot do bb_cpld fw update:
root@bmc-oob:~# fw-util slot1 --force --update bb_cpld Y35CBB_E07_EVT_BB_signed.rpd
This image is not for Yv3.5 platform
There is no valid platform signature in image.
slot_id: 1, comp: 12, intf: 0, img: Y35CBB_E07_EVT_BB_signed.rpd, force: 1
Set fan mode to manual and set PWM to 70%
OnChip Flash Status = 0xFFFFFE18., slot_id 0x1, sectype 0x1, intf: 0x10, read 143360 bytes.
Erase sector SUCCESS.
Erase sector SUCCESS.
updated cpld: 100 %
Elapsed time:  41   sec.
Set fan mode to auto and start fscd

Another Slot do sled-cycle at the same time should be fail:
root@bmc-oob:~# power-util sled-cycle
Another slot is doing fw update, cannot do sled cycle.
ERROR: power-util fru[255] [SLED_CYCLE] failed

(3) CL_BIC

One slot do bic fw update:
root@bmc-oob:~# fw-util slot1 --force --update bic oby35-cl-2022.28.02.bin
Please use EVT firmware on EVT system
To force the update, please use the --force option.
slot_id: 1, comp: 2, intf: 0, img: oby35-cl-2022.28.02.bin, force: 1
Set fan mode to manual and set PWM to 70%
file size = 216252 bytes, slot = 1, intf = 0xff
updating fw on slot 1:
updated bic: 100 %
Elapsed time:  8   sec.

get new SDR cache from BIC
ok: run: sensord: (pid 12076) 0s
Set fan mode to auto and start fscd
Force upgrade of slot1 : bic succeeded

Another Slot do sled-cycle at the same time should be fail:
root@bmc-oob:~# power-util sled-cycle
Another slot is doing fw update, cannot do sled cycle.
ERROR: power-util fru[255] [SLED_CYCLE] failed

(4) BMC

One slot do bmc fw update:
root@bmc-oob:~# fw-util bmc --update bmc flash-fby35
Flashing to device: /dev/mtd6
Erasing block: 476/476 (100%)
Writing kb: 30410/30410 (100%)
Verifying kb: 30410/30410 (100%)
Upgrade of bmc : bmc succeeded

Another Slot do sled-cycle at the same time should be fail:
root@bmc-oob:~# power-util sled-cycle
Another slot is doing fw update, cannot do sled cycle.
ERROR: power-util fru[255] [SLED_CYCLE] failed

(5) BIOS

root@bmc-oob:~# fw-util slot1 --force --update bios Y35CLD03.bin
Please use EVT firmware on EVT system
To force the update, please use the --force option.
Checking if the server is ready...
Server power status: 1
Powering off the server (cmd 0)...
Server power status: 0
Putting ME into recovery mode...
slot_id: 1, comp: c, intf: 0, img: Y35CLD03.bin, force: 1
Init libusb Successful!
1d6b:0104 (bus 1, device 17) path: 1.4
Manufactured : ZEPHYR
Product : Zephyr CDC ACM
----------------------------------------
Device Descriptors:
Vendor ID : 1d6b
Product ID : 104
Serial Number : 3
Size of Device Descriptor : 18
Type of Descriptor : 1
USB Specification Release Number : 512
Device Release Number : 518
Device Class : 0
Device Sub-Class : 0
Device Protocol : 0
Max. Packet Size : 64
No. of Configuraions : 1
Configured value : 1
Claimed Interface: 1, EP addr: 0x03
-----------------------------------

Interface Descriptors:
  Number of Interfaces : 0x2
  Length : 0x9
  Desc_Type : 0x2
  Config_index : 0x0
  Total length : 75
  Configuration Value  : 0x1
  Configuration Attributes : 0xc0
  MaxPower(mA) : 50
    Interface:
      bInterfaceNumber:   0
      bAlternateSetting:  0
      bNumEndpoints:      1
      bInterfaceClass:    2
      bInterfaceSubClass: 2
      bInterfaceProtocol: 0
      iInterface:         0

      EndPoint Descriptors:
        bLength: 7
        bDescriptorType: 0x5
        bEndpointAddress: 0x81
        Maximum Packet Size: 0x10
        bmAttributes: 0x3
        bInterval: 0xa
-----------------------------------
    Interface:
      bInterfaceNumber:   1
      bAlternateSetting:  0
      bNumEndpoints:      2
      bInterfaceClass:    10
      bInterfaceSubClass: 0
      bInterfaceProtocol: 0
      iInterface:         0

      EndPoint Descriptors:
        bLength: 7
        bDescriptorType: 0x5
        bEndpointAddress: 0x82
        Maximum Packet Size: 0x40
        bmAttributes: 0x2
        bInterval: 0x0
      EndPoint Descriptors:
        bLength: 7
        bDescriptorType: 0x5
        bEndpointAddress: 0x3
        Maximum Packet Size: 0x40
        bmAttributes: 0x2
        bInterval: 0x0
-----------------------------------
Strong checksum function is not available, disabling deduplication.
Updating BIOS, dedup is off, verification is off.
1024 blocks (1024 written, 0 skipped)...finished.
Elapsed time:  189   sec.
Doing ME Reset...
Power-cycling the server...
Force upgrade of slot1 : bios succeeded

Another Slot do sled-cycle at the same time should be fail:
root@bmc-oob:~# power-util sled-cycle
Another slot is doing fw update, cannot do sled cycle.
ERROR: power-util fru[255] [SLED_CYCLE] failed

Reviewed By: GoldenBug

Differential Revision: D39283703

Pulled By: garnermic

fbshipit-source-id: d55d1b03b8547bb0c09aa501881f0b1bcf85e686