correct some logging issues
Summary:
- lastlog & wtmp were missing from the image.
- logrotate has been throwing errors for quite a while now because a duplicate config was being installed.
- Add a CIT test for logrotate.

```
root@rsw1qq-oob:~# /etc/cron.daily/logrotate
error: syslog:3 duplicate log entry for /var/log/messages
error: syslog:16 duplicate log entry for /var/log/kern.log
error: syslog:16 duplicate log entry for /var/log/cron.log
error: found error in file syslog, skipping
```

Test Plan:
Build image and boot on test BMC.  observe that the logrotate errors are gone and that /var/log has expected contents.

```
root@rsw1at-oob:~# cat /etc/issue
OpenBMC Release wedge100-1f627a1bb0-dirty

root@rsw1at-oob:~# /etc/cron.daily/logrotate
root@rsw1at-oob:~# echo $?
0
root@rsw1at-oob:~# ls -lL /var/log
-rw-r--r--    1 root     root         23612 Feb 19 09:33 backports.log
-rw-r--r--    1 root     root         26521 Feb 19 09:42 fscd.log
-rw-r--r--    1 root     root         99873 Feb 19 09:40 fscd.log.1
-rw-rw-r--    1 root     utmp           292 Feb 19 09:33 lastlog
-rw-r--r--    1 root     root             0 Feb 19 09:18 mTerm_wedge.log
-rw-r-----    1 root     adm         125751 Feb 19 09:42 messages
-rw-r--r--    1 root     root             0 Feb 19 09:18 psu-status.log
-rw-rw-r--    1 root     utmp          3456 Feb 19 09:38 wtmp
```

New CIT test.

Reviewed By: kawmarco

Differential Revision: D26547511

fbshipit-source-id: bb973cf656