fbgc: cit: fix REST API test failed while checking UIC FRU (#2020)
Summary:
As the UIC is front swappable, which does not have tight bound with chassis.
The PVT UIC's FRU remove 'Chassis Part Number', 'Chassis Serial Number', and 'Chassis Type' these chassis fields.

All of these information will only be contained in DPB FRU which has tight bound with chassis.

This commit make the corresponding change in rest api test also.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/2020

Test Plan:
1. Build and test pass on Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and BMC SELs.

3. Check REST API test pass.
    [Before]
        - Test fail while testing test_rest_endpoints.

        ======================================================================
        FAIL: test_rest_endpoints (tests.grandcanyon.test_rest_endpoint.RestEndpointTest) (attrib='Chassis Part Number')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 156, in verify_endpoint_attributes
            self.assertIn(
        AssertionError: 'Chassis Part Number' not found in '{"Information": {"Board Mfg Date": "Fri Dec  3 10:32:00 2021", "Board Mfg": "Wiwynn", "Board Product": "User Interface Card w/ BMC", "Board Serial": "WR14148048ZSA", "Board Part Number": "B81.04910.0214", "Board FRU ID": "1.0", "Board Custom Data 1": "19-002056", "Board Custom Data 2": "PCB Supplier - TRI", "Product Manufacturer": "Wiwynn", "Product Name": "Grand Canyon PVT", "Product Part Number": "B81.04901.0129", "Product Version": "PVT", "Product Serial": "WTR2152005ZSA", "Product Asset Tag": "AS75875", "Product FRU ID": "1.0", "Product Custom Data 1": "01-006063", "Product Custom Data 2": "TI"}, "Actions": [], "Resources": []}' : endpoint /api/uic/fruid missing attrib Chassis Part Number

        ======================================================================
        FAIL: test_rest_endpoints (tests.grandcanyon.test_rest_endpoint.RestEndpointTest) (attrib='Chassis Serial Number')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 156, in verify_endpoint_attributes
            self.assertIn(
        AssertionError: 'Chassis Serial Number' not found in '{"Information": {"Board Mfg Date": "Fri Dec  3 10:32:00 2021", "Board Mfg": "Wiwynn", "Board Product": "User Interface Card w/ BMC", "Board Serial": "WR14148048ZSA", "Board Part Number": "B81.04910.0214", "Board FRU ID": "1.0", "Board Custom Data 1": "19-002056", "Board Custom Data 2": "PCB Supplier - TRI", "Product Manufacturer": "Wiwynn", "Product Name": "Grand Canyon PVT", "Product Part Number": "B81.04901.0129", "Product Version": "PVT", "Product Serial": "WTR2152005ZSA", "Product Asset Tag": "AS75875", "Product FRU ID": "1.0", "Product Custom Data 1": "01-006063", "Product Custom Data 2": "TI"}, "Actions": [], "Resources": []}' : endpoint /api/uic/fruid missing attrib Chassis Serial Number

        ======================================================================
        FAIL: test_rest_endpoints (tests.grandcanyon.test_rest_endpoint.RestEndpointTest) (attrib='Chassis Type')
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 156, in verify_endpoint_attributes
            self.assertIn(
        AssertionError: 'Chassis Type' not found in '{"Information": {"Board Mfg Date": "Fri Dec  3 10:32:00 2021", "Board Mfg": "Wiwynn", "Board Product": "User Interface Card w/ BMC", "Board Serial": "WR14148048ZSA", "Board Part Number": "B81.04910.0214", "Board FRU ID": "1.0", "Board Custom Data 1": "19-002056", "Board Custom Data 2": "PCB Supplier - TRI", "Product Manufacturer": "Wiwynn", "Product Name": "Grand Canyon PVT", "Product Part Number": "B81.04901.0129", "Product Version": "PVT", "Product Serial": "WTR2152005ZSA", "Product Asset Tag": "AS75875", "Product FRU ID": "1.0", "Product Custom Data 1": "01-006063", "Product Custom Data 2": "TI"}, "Actions": [], "Resources": []}' : endpoint /api/uic/fruid missing attrib Chassis Type

    [After]
        root@bmc-oob:/usr/local/bin/tests2# python3 cit_runner.py --platform grandcanyon --run-test tests.grandcanyon.test_rest_endpoint
        test_rest_endpoints (tests.grandcanyon.test_rest_endpoint.RestEndpointTest) ... ok
        test_server_httperror_code_404 (tests.grandcanyon.test_rest_endpoint.RestEndpointTest)
        Test if REST server return 404 code when url is not accessible ... ok

        ----------------------------------------------------------------------
        Ran 2 tests in 19.098s

        OK

Reviewed By: peterdelevoryas

Differential Revision: D33821394

Pulled By: zhdaniel12

fbshipit-source-id: 05c16aaf17