Add FBVBOOT_GOLDEN_IMAGE_SIZE_MB image configuration
Summary:
Add FBVBOOT_GOLDEN_IMAGE_SIZE_MB configuation for fbobmc-image.

Add default/common image layout which can be reused
by platforms: fbobmc_get_default_image_part_table
it took input flash_size_mb default 128MB
and data0_size_mb default 32MB.
The default partition table will set the os-fit partition
upbound to FBVBOOT_GOLDEN_IMAGE_SIZE_MB
and put the data0 partition at the end of flash device

P.S. Currently the partition table is only used during assembling
the all-in-one image with all components and generate
the image-meta data. Sanity checking all components
fits to the partition and no overlap. It does not check the
kernel mtd information is consistent with it.

TODO: generate the kernel mtd layout dts information
based on the partition table define here.

Test Plan:
Platform not setting this value will default to 32
```
[ ~/workspaces/openbmc/build-fbgc-ubu  (artemis)] bb -ne grandcanyon-image | grep 'FBVBOOT_GOLDEN_IMAGE_SIZE_MB='
FBVBOOT_GOLDEN_IMAGE_SIZE_MB="32"
```
Platform set support value 64
```
[~/workspaces/openbmc/build-gtt  (artemis)] bb -ne grandteton-image | grep 'FBVBOOT_GOLDEN_IMAGE_SIZE_MB='
FBVBOOT_GOLDEN_IMAGE_SIZE_MB="64"
```
Platform set unsupported value failed at parser
```
[~/workspaces/openbmc/build-gtt  (artemis)] bb -ne grandteton-image | grep 'FBVBOOT_GOLDEN_IMAGE_SIZE'
ERROR: /home/zhdaniel/workspaces/openbmc/yocto/lf-kirkstone/../../meta-facebook/meta-grandteton/recipes-core/images/grandteton-image.bb: FBVBOOT_GOLDEN_IMAGE_SIZE_MB(48) not support
ERROR: Parsing halted due to errors, see error messages above
```

Reviewed By: williamspatrick

Differential Revision: D41920070

fbshipit-source-id: 01f1b22d353135efe0ebcb7d9062d7081efe5b5c