Update references to TestCase.assertEquals
Summary:
assertEquals used to be an alias to assertEqual, but seems the aliases were removed:

https://github.com/python/cpython/pull/28268

This is causing some tests to fail with
```
======================================================================
ERROR: test_set_all_fans_and_read (tests.grandcanyon.test_fans.FansTest.test_set_all_fans_and_read)
Test setting all fans speed and read to ensure it is the same
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_fans_test.py", line 362, in test_set_all_fans_and_read
    speed = self.get_speed(data)
            ^^^^^^^^^^^^^^^^^^^^
  File "/run/tests2/common/base_fans_test.py", line 287, in get_speed
    self.assertEquals(num, self.names[m.group(1)], "Bad fan index")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'FansTest' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?
```

Test Plan:
Test run on grandcanyon
```
$ netcastle --team openbmc --platform grandcanyon

Ran 90 tests in 39 mins 54.908 secs
[   ERROR] 0
[  FAILED] 0
[ TIMEOUT] 0
[  PASSED] 70
[ SKIPPED] 20
[ OMITTED] 0
[ RETRIED] 0
2024/02/01 02:36:52.896|522087|MainThread|I|abstract_runner: All tests passed!

Reviewed By: lsiudut

Differential Revision: D53307151

fbshipit-source-id: 163ef91fd883ca607f6bfdb0b10e756015957e74