GT/GTI: MB cycle needs to check HGX update ongoing flag
Summary:
MB on, off, cycle and reset needs to check both MB and HGX update ongoing flag

# Testing:
  Terminal 1:
    root@bmc-oob:# fw-util hgx --update auto /tmp/nvfw_HGX-H100x8_0002_231020.1.1_prod-signed.fwpkg
    Started update task: 0
    The task with id 0 has started.
    The target device 'HGX_FW_PCIeSwitch_0' will be updated with image '1.7.5F'.
    The target device 'HGX_FW_NVSwitch_0' will be updated with image '96.10.4A.00.01'.
    The target device 'HGX_FW_NVSwitch_2' will be updated with image '96.10.4A.00.01'.
    The target device 'HGX_FW_NVSwitch_1' will be updated with image '96.10.4A.00.01'.
    The target device 'HGX_FW_NVSwitch_3' will be updated with image '96.10.4A.00.01'.
    The target device 'HGX_FW_GPU_SXM_8' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_6' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_5' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_7' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_4' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_3' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_2' will be updated with image '96.00.89.00.01'.
    The target device 'HGX_FW_GPU_SXM_1' will be updated with image '96.00.89.00.01'.
    ...
  Terminal 2:
    root@bmc-oob:# power-util mb cycle
    FW update for hgx is ongoing, block the power controlling.
    ERROR: power-util fru[1] [POWER_CYCLE] failed

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4159

Test Plan: Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: williamspatrick

Differential Revision: D51931241

fbshipit-source-id: 3d54d9d597576c068d45520da3bedc82c0626e95