fby3: make mp5920 be built as an module (#1135)
Summary:
-mp5920 driver in fby3 was a built-in driver.
An mp5920 device can't be accessed in userspace since it is used by kernel.
Let mp5920 be built as an module so users can access the mp5920 device after unload the module.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1135

Test Plan:
-build code(pass)
-access the mp5920 device in user space(pass)

root@bmc-oob:~# i2cget -y 11 0x44 0xb0 w
Error: Could not set address to 0x44: Device or resource busy
root@bmc-oob:~# lsmod
    Not tainted
i2c_slave_mqueue 2162 0 - Live 0x7f028000
mp5920 1884 0 - Live 0x7f024000
tmp421 4138 0 - Live 0x7f01f000
tpm_tis_spi 4675 0 - Live 0x7f01a000
tpm_tis_core 10968 1 tpm_tis_spi, Live 0x7f014000
uhci_hcd 41515 0 - Live 0x7f004000
spi_aspeed 3513 0 - Live 0x7f000000
root@bmc-oob:~# modprobe -r mp5920
root@bmc-oob:~#

root@bmc-oob:~# i2cget -y 11 0x44 0xb0 w
0x0000
root@bmc-oob:~# i2cset -y 11 0x44 0xe1 0xc2 0x82 i
root@bmc-oob:~# i2cget -y 11 0x44 0xb0 w
0x0053
root@bmc-oob:~# i2cget -y 11 0x44 0xb1 w
0x0000
root@bmc-oob:~# i2cset -y 11 0x44 0xe1 0x00 0x00 i
root@bmc-oob:~# i2cget -y 11 0x44 0xb1 w
0x0000

Reviewed By: tao-ren

Differential Revision: D22665631

Pulled By: benwei13

fbshipit-source-id: 181a302b3b