tests2: CommonEepromTest: fix python string.format syntax issues (#1090)
Summary:
When eeprom test fails, the debug message can not display error key words correctly due to the string.format() syntax issue.

Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/1090

Test Plan:
```
root@bmc-oob:~/tests2# python cit_runner.py -p wedge400 --run-test tests.wedge400.test_eeprom.SCMEepromTest.test_product_name
test_product_name (tests.wedge400.test_eeprom.SCMEepromTest)
Tests if the platform defined product name is present ... FAIL

======================================================================
FAIL: test_product_name (tests.wedge400.test_eeprom.SCMEepromTest)
Tests if the platform defined product name is present
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/root/tests2/common/base_eeprom_test.py", line 93, in test_product_name
    found, "Product name {} not in set {}".format(name, self.product_name)
AssertionError: False is not true : Product name wedge400-scm not in set ['WEDGE400C-SCM']

----------------------------------------------------------------------
Ran 1 test in 3.127s

FAILED (failures=1)
```

Reviewed By: tao-ren

Differential Revision: D28512895

fbshipit-source-id: bdf61ee21c