restapi/fruid: Ignore non-ascii parameters in the output of weutil
Summary:
The REST API crashes and returns 500 on /api/sys/mb/fruid with the following
trace when there are garbage characters in some fields of the output of
weutil:
```
  File "/usr/local/fbpackages/rest-api/rest_fruid.py", line 34, in get_fruid
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 268: invalid start byte
```

Test Plan:
In /tmp/rest.log:
     - - [19/Jul/2018:01:24:22 +0000] "GET /api/sys/mb/fruid HTTP/1.1" 200 969 "-" "Go-http-client/1.1"
instead of a 500 and the trace previously

Reviewed By: mikechoifb

Differential Revision: D9582295

fbshipit-source-id: 099694029