tests2: common: increase "sv stop" timeout for watchdog test (#1383)
Summary:
from stress test on wedge400 unit, found some iteration the CIT testing be error,

```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --platform wedge400c -r tests.wedge400.test_watchdog.WatchdogTest --repeat 50

Test Iteration https://github.com/facebookexternal/openbmc.celestica/issues/1
test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest) ... ERROR
test_watchdog_start_stop (tests.wedge400.test_watchdog.WatchdogTest)
Test if watchdog is configured properly on bmc. ... ok

======================================================================
ERROR: test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/utils/shell_util.py", line 68, in run_shell_cmd
    raise Exception(
Exception: /usr/bin/sv stop fscd exited with non 0 exit code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_watchdog_test.py", line 122, in test_watchdog_kick
    self.kill_watchdog_daemon()
  File "/usr/local/bin/tests2/common/base_watchdog_test.py", line 86, in kill_watchdog_daemon
    run_shell_cmd(cmd)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 39, in wrap
    return func(*args, **kwargs)
  File "/usr/local/bin/tests2/utils/shell_util.py", line 73, in run_shell_cmd
    raise Exception("Failed to run command = {} and exception {}".format(cmd, e))
Exception: Failed to run command = /usr/bin/sv stop fscd and exception /usr/bin/sv stop fscd exited with non 0 exit code

----------------------------------------------------------------------
Ran 2 tests in 33.201s

FAILED (errors=1)

Test Iteration https://github.com/facebookexternal/openbmc.celestica/issues/2
test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest) ... ok
test_watchdog_start_stop (tests.wedge400.test_watchdog.WatchdogTest)
Test if watchdog is configured properly on bmc. ... ok

----------------------------------------------------------------------
Ran 2 tests in 62.928s

OK
....
```

fscd can't stop in 7 second (sv default timeout)
fscd need to set_fan_speed before (from experiment use time 0.2 to 3.6 second)
then stop wdt thread which has the sleep 5 second

```
def fscd_release_watchdog(stop_wdt=False):   <<<<<<<<<<< wait after set_fan_speed
    """stop the watchdog device."""
    if _WATCHDOG_THREAD.is_alive():
        Logger.info("Stopping watchdog thread")
        _WATCHDOG_STOP.set()                         <<<<<<<<<<<<< set flag true
        _WATCHDOG_THREAD.join()
        Logger.info("Watchdog thread stopped")

    if stop_wdt:
        stop_watchdog()
        Logger.info("watchdog stopped")

    release_watchdog()

def _watchdog_thread_f():
    while not _WATCHDOG_STOP.is_set():      <<<<<<<<<<<<< wait to be true
        kick_watchdog()
        time.sleep(5)

_WATCHDOG_THREAD = threading.Thread(target=_watchdog_thread_f, daemon=True)
_WATCHDOG_STOP = threading.Event()
```

add timeout more than the worse case

run repeatedly  CIT Watchdog test.
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --platform wedge400c -r tests.wedge400.test_watchdog.WatchdogTest --repeat 50

Test Iteration https://github.com/facebookexternal/openbmc.celestica/issues/1
test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest) ... ok
test_watchdog_start_stop (tests.wedge400.test_watchdog.WatchdogTest)
Test if watchdog is configured properly on bmc. ... ok

----------------------------------------------------------------------
Ran 2 tests in 67.639s

OK

....

Test Iteration https://github.com/facebookexternal/openbmc.celestica/issues/49
test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest) ... ok
test_watchdog_start_stop (tests.wedge400.test_watchdog.WatchdogTest)
Test if watchdog is configured properly on bmc. ... ok

----------------------------------------------------------------------
Ran 2 tests in 63.947s

OK

Test Iteration https://github.com/facebookexternal/openbmc.celestica/issues/50
test_watchdog_kick (tests.wedge400.test_watchdog.WatchdogTest) ... ok
test_watchdog_start_stop (tests.wedge400.test_watchdog.WatchdogTest)
Test if watchdog is configured properly on bmc. ... ok

----------------------------------------------------------------------
Ran 2 tests in 62.826s

OK
root@bmc-oob:/usr/local/bin/tests2#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1383

Reviewed By: GoldenBug

Differential Revision: D38852720

fbshipit-source-id: 333da756a35ed377e3fa82c186414b6c035dbc37