rest-api-v2: Isolate global read-only configuration enforcement to a single file
Summary:
Move read-only/read-write configuration enforcement from each platform layer
to the common calling function to avoid accidental inclusion of actionable nodes.
This make security enforcement and audits easy and platform independent.

Checking for supported actions is also done by the calling function. Thus, doAction()
methods of nodes need not worry about unsupported actions (Obviously unless they
support a subset of the actions under run-time varying conditions).

Test Plan:
0. Build on fbtp
1. run rest_crawler.py from the BMC. Since the default is to disable writes, we should see "ACTION * secured on *" for all endpoints.
root@bmc-oob:~# rest_crawler.py
Crawling localhost
ACTION sled-cycle secured on /api/sled
<snip>
ACTION clear secured on /api/sled/mezz/logs
2. Enable actions. Make sure some of the enabled actions dont pull the rug from under neath us :-)
chmod a-x /sbin/reboot
chmod a-x /usr/local/bin/power-util
change /etc/rest.cfg to enable writes.
sv restart restapi
3. Run rest_crawler.py.All endpoints which succeeded in step 1 should fail with an error.
root@bmc-oob:~# rest_crawler.py
Crawling localhost
ERROR: Unexpected response to action when read-only sled-cycle on url: /api/sled
<snip>
ERROR: Unexpected response to action when read-only clear on url: /api/sled/mezz/logs
4. Check /tmp/rest.log to make sure no crashes were endured during the above 2 crawling steps.
5. Repeat 0-4 on fby2
root@bmc-oob:~# rest_crawler.py
Crawling localhost
ACTION sled-cycle secured on /api/spb
ACTION sled-identify-on secured on /api/spb
<snip>
ACTION disable secured on /api/server4/bios/boot-order/boot_order

root@bmc-oob:~# rest_crawler.py
Crawling localhost
ERROR: Unexpected response to action when read-only sled-cycle on url: /api/spb
ERROR: Unexpected response to action when read-only sled-identify-on on url: /api/spb
<snip>
ERROR: Unexpected response to action when read-only set on url: /api/server4/bios/boot-order/boot_order
ERROR: Unexpected response to action when read-only disable on url: /api/server4/bios/boot-order/boot_order
6. Repeat 0-4 on Yosemite:
root@bmc-oob:~# rest_crawler.py
Crawling localhost
ACTION sled-cycle secured on /api/spb
ACTION sled-identify-on secured on /api/spb
<snip>

root@bmc-oob:~# rest_crawler.py
Crawling localhost
ERROR: Unexpected response to action when read-only sled-cycle on url: /api/spb
ERROR: Unexpected response to action when read-only sled-identify-on on url: /api/spb
<snip>

Reviewed By: benwei13

Differential Revision: D8584514

fbshipit-source-id: 8107bcabd