fbal, fbsp: fix compile fail in VR
Summary:
Fix the following failure:

```
| vr.c: In function 'vr_fw_version':
| vr.c:226:48: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size 71 [-Werror=format-truncation=]
|    snprintf(ver_str, MAX_VER_STR_LEN, "Version: %s", tmp_str);
```
The VR code reads from a kv, which is a longer string than
`MAX_VER_STR_LEN`, thus GCC can warn about format truncation if the return
code of `snprintf` is not caught.  Return the value of `snprintf` since
we do not actually expect truncation to take place.

Test Plan: #buildit

Reviewed By: amithash

Differential Revision: D18653582

fbshipit-source-id: c83d74e015