fby3: cwc: extend cpld fw update time out to avoid interruptions by power-util (#1918)
Summary:
- Recently, it is found that the cpld fw update process can be interrupted by power-util on cwc/gpv3,
  the reason is that the time out for cpld fw update is 60 seconds now,
  but it actually takes more than 100 seconds for cpld fw update on cwc/gpv3.
  This commit extend the time out for cpld fw update to 300 seconds to avoid interruption.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1918

Test Plan:
- Check if 12v cycle can be executed during cpld fw update - pass

Log:
- update cpld fw
root@bmc-oob:/tmp# fw-util slot1 --update 2U-top 2U_cpld Y3CG3_MCHP_D02.jed
 3358 root     69640 S    /usr/local/bin/healthd
slot_id: 1, comp: 32, intf: 0, img: Y3CG3_MCHP_D02.jed, force: 0
* Turning off BIC sensor monitor...
Init libusb Successful!
....

Elapsed time:  101   sec.
* Turning on BIC sensor monitor...
Upgrade of slot1 : 2U_cpld_top succeeded
root@bmc-oob:/tmp#

- power cycle
root@bmc-oob:~# power-util slot1 12V-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed
root@bmc-oob:~# power-util slot1 12V-cycle
FW update for slot1 is ongoing, block the power controlling.
ERROR: power-util fru[1] [12V_CYCLE] failed
root@bmc-oob:~#

Reviewed By: peterdelevoryas

Differential Revision: D32142765

Pulled By: GoldenBug

fbshipit-source-id: 88b4068041