GT: Add fw-util new component brick on VPDB (#3556)
Summary:
Add fw-util new component brick on VPDB when is 3rd source

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3556

Test Plan:
Check new component's functions with fw-util

Testing:
root@bmc-oob:#
root@bmc-oob:# fw-util
USAGE: fw-util all|FRU --version|--version-json [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
       fw-util FRU --update COMPONENT IMAGE_PATH --schedule now
       fw-util all --show-schedule
       fw-util all --delete-schedule TASK_ID

FRU        : Components
---------- : ----------
bmc       : bmc fscd rom tpm
hgx        : auto
mb         : bios cpu0_faon cpu0_vccd cpu0_vccin cpu1_faon cpu1_vccd cpu1_vccin mb_cpld me
nic0       : nic0
nic1       : nic1
ocpdbg   : mcu mcubl
scm        : scm_cpld
swb        : bic bic_recovery pex0 pex1 pex2 pex3 pex01_vcc pex23_vcc pex_all swb_cpld swb_nic0 swb_nic1 swb_nic2 swb_nic3 swb_nic4 swb_nic5 swb_nic6 swb_nic7
vpdb       : brick
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util vpdb --version
VPDB_BRICK Version: Renesas 4dfb615a, Remaining Write: 25
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util vpdb --update brick /tmp/signed.hex
Configuration GEN2 CRC: 4DFB615A
Update VR: VPDB_BRICK
WARNING: the CRC is the same as used now 4DFB615A!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
/tmp/vpdb_signed_update.bin
Update component with temp file failed. error(-1)
Upgrade of vpdb : brick failed
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util vpdb --force --update brick /tmp/signed.hex
Configuration GEN2 CRC: 4DFB615A
Update VR: VPDB_BRICK
Remaining writes: 25
updated: 100 %
Force upgrade of vpdb : brick succeeded
root@bmc-oob:#
root@bmc-oob:#
root@bmc-oob:# fw-util vpdb --version
VPDB_BRICK Version: Renesas 4dfb615a, Remaining Write: 25

Reviewed By: williamspatrick

Differential Revision: D43000536

fbshipit-source-id: 58b325fecb30715ead11817b57fb18d07198d5ec