libipmb: fix unused variable warning
Summary:
Resolve unused variable warning on some platforms:
```
| ../ipmb.c: In function 'lib_ipmb_send_request':
| ../ipmb.c:189:7: error: unused variable 'ret' [-Werror=unused-variable]
|    int ret=0;
```

Test Plan: CIT build passes.

Reviewed By: sammyblueeyes

Differential Revision: D20765966

fbshipit-source-id: 4e81b0f115