rackmon2: Fix unit-test compilation error
Summary: Fixing unit-test compilation regression from D34094965.

Test Plan:
Previously:

```
| ../tests/RegisterValueTest.cpp:160:40: error: could not convert '{{true, "HELLO"}, {false, "WORLD"}, {false, "HELLO2"}, {true,
 "WORLD2"}}' from '<brace-enclosed initializer list>' to 'rackmon::RegisterValue::FlagsType' {aka 'std::vector<std::tuple<bool,
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned char> >'}
|   160 |     {false, "HELLO2"}, {true, "WORLD2"}};
|       |                                        ^
|       |                                        |
|       |                                        <brace-enclosed initializer list>
```

Now:

```
Initialising tasks: 100% |#######################################################################################| Time: 0:00:03
Sstate summary: Wanted 0 Found 0 Missed 0 Current 0 (0% match, 0% complete)
NOTE: No setscene tasks
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 1 tasks of which 0 didn't need to be rerun and all succeeded.
```

Reviewed By: amithash

Differential Revision: D34114920

fbshipit-source-id: 40978f7c9e