wedge400: pal: remove trailing space from pal_fru_list (#1409)
Summary:
found bug of pal_fru_list when using log-util command

```
root@bmc-oob:~# log-util fan4 --clear
ERROR: ValidationError: fru:  not in {all,fan1,fan2,fan3,fan4 ,pem1,pem2,psu1,psu2,scm,smb,sys}
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,fan1,fan2,fan3,fan4 ,pem1,pem2,psu1,psu2,scm,smb,sys} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
  -s TEXT                     Starting time for timestamp delete
  -e TEXT Needs: -s           Ending time for timestamp delete
[Option Group: Actions]
...
```

from the failure result, fan4 has a more space it making the issue for log-util command
```
                                                             have more space
                                                             v
ERROR: ValidationError: fru:  not in {all,fan1,fan2,fan3,fan4 ,pem1,pem2,psu1,psu2,scm,smb,sys}
```

`log-util fan4 --clear` able to run as normal
```
root@bmc-oob:~# log-util fan4 --print
root@bmc-oob:~# log-util fan4 --clear
root@bmc-oob:~#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1409

Reviewed By: mikechoifb

Differential Revision: D41192220

fbshipit-source-id: 52d22e2775aac06faf0ecc3b07e09b5d445d2f0c