common: ipmbd: add verbose logging command line option
Summary:
The patch allows us to turn on verbose logging easily (by "-v" option),
which is helpful to verify if ipmbd is running properly (i.e. threads
are actively processing requests). The behavior/logic of ipmbd should
not be changed by this patch.

Detailed changes are:
  - using getopt_long() to parse command line options.
  - adding "-v|--verbose" option to turn on verbose logging.
  - converting syslog() to OBMC_* APIs defined in <openbmc/log.h>.
  - adding a few verbose-logging statements for debugging purpose.
  - converting all <bus_id> to "int" type to avoid potential failures
    cause by sign extention.
  - minimizing the use of global variables (such as g_bus_id and
    g_payload_id).
  - a few other misc cleanup and bug fixes.

Test Plan:
1) "bitbake minipack-image" succeeded.
2) booted up minipack: ipmbd is running without issues.

Command output:
root@bmc-oob:/tmp# /usr/local/bin/ipmbd -h
Usage: /usr/local/bin/ipmbd [options] <bus-id> <payload-id>
    -h|--help                - print this help message
    -v|--verbose             - enable verbose logging
    -u|--enable-bic-update   - enable/allow bic update
root@bmc-oob:/tmp# /usr/local/bin/ipmbd -v -u
Error: <bus-id> and/or <payload-id> is missing!

Usage: /usr/local/bin/ipmbd [options] <bus-id> <payload-id>
    -h|--help                - print this help message
    -v|--verbose             - enable verbose logging
    -u|--enable-bic-update   - enable/allow bic update
root@bmc-oob:/tmp# /usr/local/bin/ipmbd -v -u 0 1

Sample logs from /var/log/messages
ipmbd_0: ipmbd_0 started: bus#:0, payload#:1
ipmbd_0: message queue /mq_ipmb_req_0 created
ipmbd_0: message queue /mq_ipmb_res_0 created
ipmbd_0: sequence buffer initialized
ipmbd_0: creating thread rx_handler
ipmbd_0: creating thread req_handler
ipmbd_0: creating thread res_handler
ipmbd_0: ipmb lib handler started successfully
ipmbd_0: rx_handler: thread starts execution
ipmbd_0: rx_handler: opened bmc i2c-0 controller as slave, fd=7
ipmbd_0: rx_handler: message queue /mq_ipmb_req_0 opened
ipmbd_0: rx_handler: message queue /mq_ipmb_res_0 opened
ipmbd_0: req_handler: thread starts execution
ipmbd_0: res_handler: thread starts execution
ipmbd_0: svc_handler: entering svc handler
...

Reviewed By: benwei13

Differential Revision: D15040771

fbshipit-source-id: 2f44e9a623