Support default Partition_000 name for flash0
Summary:
Some systems are still in this state so make the small changes to
support moving them beyond it. This prevents the following error:

  Can't open /dev/mtd1: No such device
  2017-11-09 09:56:09,324 ERROR:Unhandled exception raised.
  Traceback (most recent call last):
    File "/tmp/improve_system.py", line 109, in <module>
      improve_system(logger)
    File "/tmp/improve_system.py", line 76, in improve_system
      system.append_to_kernel_parameters(args.dry_run, mtdparts, logger)
    File "/var/volatile/tmp/system.py", line 149, in append_to_kernel_parameters
      before = get_kernel_parameters()
    File "/var/volatile/tmp/system.py", line 144, in get_kernel_parameters
      return subprocess.check_output(['fw_printenv', '-n', 'bootargs']).strip()
    File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
      raise CalledProcessError(retcode, cmd, output=output)
  CalledProcessError: Command '[u'fw_printenv', u'-n', u'bootargs']' returned non-zero exit status 1

Test Plan:
Unit tests:
  python -m unittest discover
  .....................
  ----------------------------------------------------------------------
  Ran 21 tests in 0.152s

  OK

System flash: P58612230

Reviewed By: benwei13

Differential Revision: D6283047

fbshipit-source-id: 8f70553