only import common_endpoint and rest_utils for fboss platforms
Summary: fix restapi for compute platforms

Test Plan:
Rest starts:
```
➜  openbmc git:(helium) tools/rest_api/run_rest_on_oob rtptest005-oob.ftw3
Validating environment: [OK]
Checking target oob reachability: [OK]
Current platform is fby2
Remote platform is fby2
Platforms match.
Preparing working directory
bash: systemctl: command not found
ok: down: restapi: 0s, normally up
Uploading full initial state to BMC
Preparing stdout logging conf
(Re)Starting REST on BMC
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/data/users/death0wl/openbmc/common/recipes-rest/rest-api/files/common_setup_routes.py was changed, syncing to BMC
bash: systemctl: command not found
ok: down: restapi: 126s, normally up
(Re)Starting REST on BMC
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
Traceback (most recent call last):
  File "/usr/local/fbpackages/rest-api/rest.py", line 37, in <module>
    from setup_plat_routes import setup_plat_routes
  File "/usr/local/fbpackages/rest-api/setup_plat_routes.py", line 24, in <module>
    from common_setup_routes import setup_common_routes
  File "/usr/local/fbpackages/rest-api/common_setup_routes.py", line 23, in <module>
    from rest_utils import common_routes
  File "/usr/local/fbpackages/rest-api/rest_utils.py", line 23, in <module>
    from boardroutes import board_routes
ImportError: No module named 'boardroutes'
/data/users/death0wl/openbmc/common/recipes-rest/rest-api/files/common_setup_routes.py was changed, syncing to BMC
bash: systemctl: command not found
ok: down: restapi: 390s, normally up
(Re)Starting REST on BMC
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
Creating new webapp
Adding compute base-routes
Adding Redfish common routes
Loaded acl cache with 70 entries

```
REST responds
```
➜  openbmc git:(helium) ✗ curl -k  https://rtptest005-oob.ftw3:8443/api/spb
{"Resources": ["bmc", "fans", "fruid", "logs", "sensors"], "Actions": ["sled-cycle", "sled-identify-on", "sled-identify-off"], "Information": {"Description": "FBY2 Side Plane"}}%
```

Reviewed By: jerrt2003

Differential Revision: D29492475

fbshipit-source-id: 5e88a7e01b