ELBERT: fix bios_util.sh erase (#221)
Summary:
https://github.com/facebookexternal/openbmc.arista/issues/155 introduced a regression in bios_util.sh wherein `erase` doesn't work due to a missing flag; this change fixes that.

## Testing
Verified on Elbert.

Current output without this change:
```
root@bmc-oob:/mnt/data1# bios_util.sh erase
Binding spi1.0 to ...
Erasing flash content ...
flashrom v1.2 on Linux 5.10.23-elbert (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Error: Extra parameter found.
Please run "flashrom --help" for usage info.
Unbinding spi-nor from spi1.0
Binding spidev back to spi1.0
```
Output with fix:
```
root@bmc-oob:/mnt/data1# bios_util.sh erase
Binding spi1.0 to ...
Erasing flash content ...
flashrom v1.2 on Linux 5.10.23-elbert (armv7l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Opened /dev/mtd7 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on linux_mtd.
Erasing and writing flash chip... Erase/write done.
Unbinding spi-nor from spi1.0
Binding spidev back to spi1.0
```

Pull Request resolved: https://github.com/facebookexternal/openbmc.arista/pull/221

Reviewed By: tao-ren

Differential Revision: D31113754

fbshipit-source-id: ac2a7f60b8