fuji: rest: fix rest_piminfo error when not plug all PIMs (#1384)
Summary:
when unplug some PIM or not plug all PIM cards

the rest  /api/sys/piminfo  will be error.
```
root@bmc-oob:/var/log# curl http://localhost:8080/api/sys/piminfo
{"Information": {"reason": "CalledProcessError(1, ['/usr/local/bin/peutil', '9'])"}, "Actions": [], "Resources": []}
```

that because the peutil command return exit code with non-zero
```
root@bmc-oob:/var/log# python
Python 3.8.13 (default, Mar 16 2022, 13:02:57)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> stdout = subprocess.check_output(["/usr/local/bin/peutil","9"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/peutil', '9']' returned non-zero exit status 1.
```

#### Solution:
add try-catch in `prepare_pimver()` to ignore the peutil error and let value be 'NA'

### TestPlan:
unplug some PIM then try rest_piminfo and run CIT RestEndpointTest
```
root@bmc-oob:/usr/local/bin/tests2# curl http://localhost:8080/api/sys/piminfo
{"Information": {"PIM2": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM3": {"type": "16Q", "fpga_ver": "0.31", "ver": "1.2.0"}, "PIM4": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM5": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM6": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM7": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM8": {"type": "16Q", "fpga_ver": "0.35", "ver": "1.2.0"}, "PIM9": {"type": "NA", "fpga_ver": "NA", "ver": "NA"}}, "Actions": [], "Resources": []}
```
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py --platform fuji -r tests.fuji.test_rest_endpoint.RestEndpointTest
test_endpoint_api (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_fan_present (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_psu_present (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_scm_present (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc_mtd (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc_secondary_boot (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fc_present (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_all (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_cpld (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_fpga (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_scm (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan1 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan2 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan3 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan4 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan5 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan6 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan7 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... skipped 'fan7 is not present'
test_endpoint_api_sys_fruid_fan8 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... skipped 'fan8 is not present'
test_endpoint_api_sys_fruid_fcm_bottom (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fcm_top (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim1 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim2 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim3 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim4 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim5 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim6 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim7 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_pim8 (tests.fuji.test_rest_endpoint.RestEndpointTest) ... skipped 'pim8 is not present'
test_endpoint_api_sys_fruid_scm (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_smb (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_mb (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_mb_fruid (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_piminfo (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_pimserial (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_sensors (tests.fuji.test_rest_endpoint.RestEndpointTest) ... skipped 'FIXME T127573953'
test_endpoint_api_sys_server (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_seutil_fruid (tests.fuji.test_rest_endpoint.RestEndpointTest) ... ok
test_server_httperror_code_404 (tests.fuji.test_rest_endpoint.RestEndpointTest)
Test if REST server return 404 code when url is not accessible ... ok

----------------------------------------------------------------------
Ran 41 tests in 45.915s

OK (skipped=4)
root@bmc-oob:/usr/local/bin/tests2#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1384

Reviewed By: GoldenBug

Differential Revision: D39215322

fbshipit-source-id: a4ebe2fcffb008d2b02890257ee2c2beec471814