cit: montblanc: test_rest_endpoint - add peci sensors for sensors attribute
Summary:
# Description
add sensors PECI data in cit montblanc
add sensors attribute in /api/sys/sensors in REST test_rest_endpoint

# Motivation
support cit rest endpoint sensors for PECI sensor

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1574

Test Plan:
test result
```
root@bmc-oob:/usr/local/bin/tests2# echo 0-30 > /sys/bus/peci/drivers/peci-cpu/bind
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc -r tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors
test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.335s

OK
```

failed case
```
root@bmc-oob:/usr/local/bin/tests2# echo 0-30 > /sys/bus/peci/drivers/peci-cpu/unbind
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc -r tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors
test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) ...
  test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='DIMM A1') ... FAIL
  test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='DIMM B1') ... FAIL

...

  test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='Core 8') ... FAIL
  test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='Core 9') ... FAIL

======================================================================
FAIL: test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='DIMM A1')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 155, in verify_endpoint_attributes
    self.assertIn(
AssertionError: 'DIMM A1' not found in '{"Information": [], "Actions": [], "Resources": []}' : endpoint /api/sys/sensors missing attrib DIMM A1

======================================================================
FAIL: test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='DIMM B1')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 155, in verify_endpoint_attributes
    self.assertIn(
AssertionError: 'DIMM B1' not found in '{"Information": [], "Actions": [], "Resources": []}' : endpoint /api/sys/sensors missing attrib DIMM B1

======================================================================

...

======================================================================
FAIL: test_endpoint_api_sys_sensors (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) (attrib='Core 9')
--------------------------------...

Reviewed By: binhuang00

Differential Revision: D46637038

fbshipit-source-id: 0cd0cfa05d36e7c319113317d3091d0d8b9dbca4