GT: Fixing SWB firmware force update with non-pldm image issue
Summary:
# Motivation:
SWB firmware force update before this update would perform normal update, which might be prevented when update VR with the same version.

# Description:
Change normal update to force update when user perform force update with non-pldm image.

# Testing:
    1. before update
        root@bmc-oob:# fw-util swb --force --update pex01_vcc /tmp/GT-SWB-INF_VR0_8D03623C.xsf
        Raw image detected.
        set_swb_snr_polling rc = 0
        Update VR: VR_PEX01_VCC
        File CRC : 8D03623C
        WARNING: the CRC is the same as used now 8D03623C!
        Please use "--force" option to try again.
        ERROR: VR Firmware update failed!
        set_swb_snr_polling rc = 0
        Force upgrade of swb : pex01_vcc failed
    2. After update
        root@bmc-oob:# fw-util swb --force --update pex01_vcc /tmp/GT-SWB-INF_VR0_8D03623C.xsf
        Raw image detected.
        set_swb_snr_polling rc = 0
        Update VR: VR_PEX01_VCC
        File CRC : 8D03623C
        Remaining writes: 22
        Memory pointer: 0xFC
        updated: 100 %
        set_swb_snr_polling rc = 0
        Force upgrade of swb : pex01_vcc succeeded

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3965

Reviewed By: amithash

Differential Revision: D47145565

fbshipit-source-id: c784356475fb2af365a33a38bd3a9ce54b8e539b