libvr: mpq8645p: block update if the version is the same as current (#1903)
Summary:
As title

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1903

Test Plan:
Build pass and test on fbep

root@bmc-oob:~# fw-util vr --update p0v8_vdd0 /mnt/data1/30h_20-0608.csv
WARNING: the version is the same as used now 0x31!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of vr : p0v8_vdd0 failed

root@bmc-oob:~# fw-util vr --force --update p0v8_vdd0 /mnt/data1/30h_20-0608.csv
Update VR VR_P0V8_VDD0 to version 0x31
Force upgrade of vr : p0v8_vdd0 succeeded

Reviewed By: williamspatrick

Differential Revision: D23382957

fbshipit-source-id: 40fcc5c6c6