GT: Update SWB-CPLD SWB-VR firmware component on fw-util (#3650)
Summary:
1. Update SWB-CPLD SWB-VR to support pldm update.
2. Implement get_version() using pldm get firmware parameter.
3. Change the logic of pldm component update. Now, normal update only verifies the validity of the pldm image, while force update will use ipmi update when a non-pldm image is detected.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3650

Test Plan:
1. Update SWB-VR with ipmi image.
2. Update SWB-VR with unvalid pldm image.
3. Force update SWB-VR with ipmi image.
4. Update SWB-CPLD with valid pldm image.

Testing:
root@bmc-oob:#
root@bmc-oob:# fw-util swb --update pex01_vcc /tmp/F0T_Swith\ P0V8V_PEX0_1\ 0x60\ PN321\ 20220824.hex
The image is not a valid PLDM image.
Upgrade of swb : pex01_vcc failed
root@bmc-oob:#
root@bmc-oob:# fw-util swb --update pex01_vcc /tmp/comp0_vr_infineon_xdpe12284c.pldm
The PLDM header info of the image is invalid.
Upgrade of swb : pex01_vcc failed
root@bmc-oob:#
root@bmc-oob:# cat /var/log/messages | grep fw-util
 2023 Mar  5 17:32:27 bmc-oob. user.warning grandteton-v2023.08.1.Daniel_PLDM: fw-util: read_pkg_header_info decode failed
 2023 Mar  5 17:32:38 bmc-oob. user.warning grandteton-v2023.08.1.Daniel_PLDM: fw-util: check_header_info SOURCE_NOT_MATCH
root@bmc-oob:#
root@bmc-oob:# fw-util swb --force --update pex01_vcc /tmp/F0T_Swith\ P0V8V_PEX0_1\ 0x60\ PN321\ 20220824.hex
The image is not a valid PLDM image. update with IPMI over PLDM. set_swb_snr_polling rc=0Configuration GEN2 CRC: 8B13EF75 Update VR: VR_PEX01_VCC
WARNING: the CRC is the same as used now 8B13EF75! Please use "--force" option to try again.
ERROR: VR Firmware update failed!
set_swb_snr_polling rc=0Force upgrade of swb : pex01_vcc failed
root@bmc-oob:#
root@bmc-oob:# fw-util swb --version swb_cpld
SWB SWB_CPLD Version: 0001000
root@bmc-oob:#
root@bmc-oob:# fw-util swb --update swb_cpld /tmp/comp7_cpld_lattice_LCMXO3-9400C.pldm
size of file is 2107793 bytes

PLDM Firmware Package Header Info
  UUID: 1244d2648d7d4718a030fc8a56587d5a    PLDM UUID Y/N? (Y)
  headerRevision: 0x1
  headerSize: 0xee
  componentBitmapBitLength: 0x8
  versionStringType: 0x1 (ASCII)
  versionStringLength: 0x25
  version string: json config lib - v1.0.0 - 2023/01/11  (0x6a 0x73 0x6f 0x6e 0x20 0x63 0x6f 0x6e 0x66 0x69 0x67 0x20 0x6c 0x69 0x62 0x20 0x2d 0x20 0x76 0x31 0x2e 0x30 0x2e 0x30 0x20 0x2d 0x20 0x32 0x30 0x32 0x33 0x2f 0x30 0x31 0x2f 0x31 0x31 )

 Number of Device ID Record in package (devIdRecordCnt) =1
DevRec[0].length=111, processed=111

Device ID[0] Record Info
  devRec[0].RecordLength: 111
  devRec[0].descriptorCnt: 0x4
  devRec[0].deviceUpdateOptionFlags: 0x1
  devRec[0].compImgSetVersionStringType: 0x1 (ASCII)
  devRec[0].compImgSetVersionStringLength: 0x1c
  devRec[0].fwDevPkgDataLength: 0x0
  devRec[0].applicableComponents: 0
  devRec[0].versionString: PLDM_UPDATE_SUPPORTED_DEVICE  (0x50 0x4c 0x44 0x4d 0x5f 0x55 0x50 0x44 0x41 0x54 0x45 0x5f 0x53 0x55 0x50 0x50 0x4f 0x52 0x54 0x45 0x44 0x5f 0x44 0x45 0x56 0x49 0x43 0x45 )
  Record Descriptors
    Record Descriptor[0]
      Type=0x1      length=0x4      data=[00a015]
    Record Descriptor[1]
      Type=0xffff      length=0x15      data=[18506c6174666f726d4772616e64205465746f6e]
    Record Descriptor[2]
      Type=0xffff      length=0x14      data=[17426f6172644944537769746368426f617264]
    Record Descriptor[3]
      Type=0xffff      length=0xa      data=[155374616765505654]

 Number of Component in package (componentImageCnt) =1

Component[0] Info
  Component[0].classification: 65535 (unknown_classification)
  Component[0].identifier: 0x7
  Component[0].comparison stamp: 0xffffffff
  Component[0].component options: 0x2
  Component[0].request update activation method: 0x1
  Component[0].location offset: 0xee
  Component[0].component size: 0x202893
  Component[0].versionStringType: 0x1 (ASCII)
  Component[0].versionStringLength: 0x19
  Component[0].versionString: lattice_LCMXO3-9400C_test  (0x6c 0x61 0x74 0x74 0x69 0x63 0x65 0x5f 0x4c 0x43 0x4d 0x58 0x4f 0x33 0x2d 0x39 0x34 0x30 0x30 0x43 0x5f 0x74 0x65 0x73 0x74 )

PDLM Firmware Package Checksum=0xb8e27acf

CMD_REQUEST_UPDATE
      Request_update buffer size=1024
dbgPrintCdb
   common:  810510
   payload: 00040000 01000100 00011c50 4c444d5f
            55504441 54455f53 5550504f 52544544
            5f444556 49434500 0000

   iid=1, cmd=0x10 (CMD_REQUEST_UPDATE)

01 PldmRequestUpdateOp: payload_size=42

CMD_PASS_COMPONENT_TABLE
dbgPrintCdb
   common:  820513
   payload: 05ffff07 0000ffff ffff0119 6c617474
            6963655f 4c434d58 4f332d39 34303043
            5f746573 74434500

   iid=2, cmd=0x13 (CMD_PASS_COMPONENT_TABLE)

02 PldmPassComponentTableOp[0]: payload_size=40

CMD_UPDATE_COMPONENT
dbgPrintCdb
   common:  830514
   payload: ffff0700 00ffffff ff932820 00020000
            0001196c 61747469 63655f4c 434d584f
            332d3934 3030435f 74657374 000000

   iid=3, cmd=0x14 (CMD_UPDATE_COMPONENT)

03 PldmUpdateComponentOp[0]: payload_size=47
handlePldmReqFwData offset = 0x20283f, length = 0x54, compBytesLeft=84, numPadding=0handle CMD_TRANSFER_COMPLETE dbgPrintCdb
   common:  920516
   payload: 00282000

   iid=18, cmd=0x16 (CMD_TRANSFER_COMPLETE)

handle CMD_VERIFY_COMPLETE
dbgPrintCdb
   common:  930517
   payload: 00282000

   iid=19, cmd=0x17 (CMD_VERIFY_COMPLETE)

handle CMD_APPLY_COMPLETE
dbgPrintCdb
   common:  940518
   payload: 00000000 5400

   iid=20, cmd=0x18 (CMD_APPLY_COMPLETE)

Apply result = 0x0, compActivationMethodsModification=0x0

CMD_ACTIVATE_FIRMWARE

05 PldmActivateFirmwareOp
Upgrade of swb : swb_cpld succeeded
root@bmc-oob:#
root@bmc-oob:# power-util sled-cycle
client_loop: send disconnect: Broken pipe

root@bmc-oob:# fw-util swb --version swb_cpld
SWB SWB_CPLD Version: 0002000
root@bmc-oob:#

Reviewed By: zhdaniel12

Differential Revision: D43911896

Pulled By: amithash

fbshipit-source-id: 530dd88c97a3ad91fc7cd6f5a032b10d11cc8989