wedge400: spi_util.sh: set the gpio mode as default after use (#1382)
Summary:
CIT GPIO run will be fail
after read/write/erase DOM_FPGA_FLASH

because spi_utils.sh will unexport the SPI related GPIO.

bonus fix: fix all the warnings reported by github reviewdog.

```
root@bmc-oob:/usr/local/bin/tests2#spi_util.sh read spi1 DOM_FPGA_FLASH1 ~/dom.bin
Config SPI1 Done.
Reading flash to /home/root/dom.bin...
flashrom v1.2 on Linux 5.10.23-wedge400 (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Micron/Numonyx/ST flash chip "N25Q128..3E" (16384 kB, SPI) on linux_spi.
Reading flash... done.

root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p wedge400c -r tests.wedge400.test_gpio.GpioTest
test_gpios (tests.wedge400.test_gpio.GpioTest)
Python's subTest will run the test 'gpio_shadow_path' for every gpio ...
======================================================================
FAIL: test_gpios (tests.wedge400.test_gpio.GpioTest) (gpioname='BMC_SPI1_CS0')
Python's subTest will run the test 'gpio_shadow_path' for every gpio
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 64, in test_gpios
    self.gpio_shadow_path(gpioname, attributes)
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 45, in gpio_shadow_path
    self.assertTrue(os.path.exists(gpio_path), "GPIO missing={}".format(gpioname))
AssertionError: False is not true : GPIO missing=BMC_SPI1_CS0

======================================================================
FAIL: test_gpios (tests.wedge400.test_gpio.GpioTest) (gpioname='BMC_SPI1_CLK')
Python's subTest will run the test 'gpio_shadow_path' for every gpio
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 64, in test_gpios
    self.gpio_shadow_path(gpioname, attributes)
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 45, in gpio_shadow_path
    self.assertTrue(os.path.exists(gpio_path), "GPIO missing={}".format(gpioname))
AssertionError: False is not true : GPIO missing=BMC_SPI1_CLK

======================================================================
FAIL: test_gpios (tests.wedge400.test_gpio.GpioTest) (gpioname='BMC_SPI1_MOSI')
Python's subTest will run the test 'gpio_shadow_path' for every gpio
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 64, in test_gpios
    self.gpio_shadow_path(gpioname, attributes)
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 45, in gpio_shadow_path
    self.assertTrue(os.path.exists(gpio_path), "GPIO missing={}".format(gpioname))
AssertionError: False is not true : GPIO missing=BMC_SPI1_MOSI

======================================================================
FAIL: test_gpios (tests.wedge400.test_gpio.GpioTest) (gpioname='BMC_SPI1_MISO')
Python's subTest will run the test 'gpio_shadow_path' for every gpio
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 64, in test_gpios
    self.gpio_shadow_path(gpioname, attributes)
  File "/usr/local/bin/tests2/common/base_gpio_test.py", line 45, in gpio_shadow_path
    self.assertTrue(os.path.exists(gpio_path), "GPIO missing={}".format(gpioname))
AssertionError: False is not true : GPIO missing=BMC_SPI1_MISO

----------------------------------------------------------------------
Ran 1 test in 3.138s

FAILED (failures=4)
root@bmc-oob:/usr/local/bin/tests2#
```

set GPIO back after operating spi.

read DOM_FPGA_FLASH before run cit test
```
root@bmc-oob:~# ./spi_util.sh read spi1 DOM_FPGA_FLASH1 ~/dom.bin
Config SPI1 Done.
Reading flash to /home/root/dom.bin...
flashrom v1.2 on Linux 5.10.23-wedge400 (armv6l)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Using default 2000kHz clock. Use 'spispeed' parameter to override.
Found Micron/Numonyx/ST flash chip "N25Q128..3E" (16384 kB, SPI) on linux_spi.
Reading flash... done.
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p wedge400c -r tests.wedge400.test_gpio.GpioTest
test_gpios (tests.wedge400.test_gpio.GpioTest)
Python's subTest will run the test 'gpio_shadow_path' for every gpio ... ok

----------------------------------------------------------------------
Ran 1 test in 2.184s

OK
root@bmc-oob:/usr/local/bin/tests2#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1382

Reviewed By: GoldenBug

Differential Revision: D38852779

fbshipit-source-id: 3feee6e3955004e4c1813a3b6187c05fa2e4f55c