libvr: block update if the CRC is the same as current used (#1902)
Summary:
block update when the CRC is the same and allow only if --force is provided:
xdpe12284c, pxe1110c, and tps53688

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1902

Test Plan:
Build and test pass on fbal

root@bmc-oob:~# fw-util vr --update pch_pvnn /tmp/F0C_PVNN_1V05pch_initial_rev00_BCBA1E93_20191012.psf
Update VR: VR_PCH_PVNN/P1V05
File CRC : BCBA1E93
WARNING: the CRC is the same as used now BCBA1E93!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of vr : pch_pvnn failed

root@bmc-oob:~# fw-util vr --force --update pch_pvnn /tmp/F0C_PVNN_1V05pch_initial_rev00_BCBA1E93_20191012.psf
Update VR: VR_PCH_PVNN/P1V05
File CRC : BCBA1E93
Remaining writes: 9
updated: 100 %
Force upgrade of vr : pch_pvnn succeeded

root@bmc-oob:~# fw-util vr --update cpu0_vccin /tmp/F0C_PVCCIN_CPU0_C0_DVT_rev00_879E0D21_20200528.xsf
Update VR: VR_CPU0_VCCIN/VCCSA
File CRC : 879E0D21
WARNING: the CRC is the same as used now 879E0D21!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of vr : cpu0_vccin failed

root@bmc-oob:~# fw-util vr --force --update cpu0_vccin /tmp/F0C_PVCCIN_CPU0_C0_DVT_rev00_879E0D21_20200528.xsf
Update VR: VR_CPU0_VCCIN/VCCSA
File CRC : 879E0D21
Remaining writes: 24
Memory pointer: 0xB8
updated: 100 %
Force upgrade of vr : cpu0_vccin succeeded

Reviewed By: benwei13

Differential Revision: D23376954

fbshipit-source-id: f8eb464ab9