tests2: Disable Fuji adm1275 test in QEMU
Summary:
This test is failing and blocking CircleCI Fuji QEMU tests from passing. https://fburl.com/gdvwxbk7

```
tests.fuji.test_i2c_driver_presence.FujiI2cDriverPresenceTest.test_i2c_driver_presence: fail
test_i2c_driver_presence (tests.fuji.test_i2c_driver_presence.FujiI2cDriverPresenceTest) ...
======================================================================
FAIL: test_i2c_driver_presence (tests.fuji.test_i2c_driver_presence.FujiI2cDriverPresenceTest) (i2c_driver='adm1275')
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/bin/tests2/common/base_i2c_driver_presence_test.py", line 63, in test_i2c_driver_presence
self.check_i2c_driver_presence(i2c_driver)
File "/usr/local/bin/tests2/common/base_i2c_driver_presence_test.py", line 51, in check_i2c_driver_presence
self.assertTrue(
AssertionError: False is not true : i2c driver adm1275 is missing

----------------------------------------------------------------------
Ran 1 test in 0.238s

FAILED (failures=1)
```

Test Plan: NA

Reviewed By: GoldenBug

Differential Revision: D40232521

fbshipit-source-id: 625abb5966e3dc91ad1b4412db2b15d47e5f222f