fby35: block power-util on/12V-on when all fan fail (#3789)
Summary:
1. block power-util on/12V-on when all fan fail, and use "--force" to force on/12V-on in the situation:
power-util slotX --force on
power-util slotX --force 12V-on

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3789

Test Plan:
Build and test pass on fby35 and halfdome

(1) power-util slotX 12V-on:
root@bmc-oob:~# power-util slot1 status
Power status for fru 1 : OFF (12V-OFF)

root@bmc-oob:~# power-util slot1 12V-on
12V Powering fru 1 to ON state...
Failed to 12V Power fru 1 to ON state due to fan fail...
ERROR: power-util fru[1] [12V_ON] failed

root@bmc-oob:~# power-util slot1 12V-cycle
12V Power cycling fru 1...
Failed to 12V Power cycle fru 1 due to fan fail...
ERROR: power-util fru[1] [12V_CYCLE] failed

root@bmc-oob:~# power-util slot1 --force 12V-on
12V Powering fru 1 to ON state...

1    slot1    2023-04-19 15:53:39    power-util       SERVER_12V_ON failed for FRU: 1 due to fan fail
1    slot1    2023-04-19 15:53:44    power-util       SERVER_12V_CYCLE failed for FRU: 1 due to fan fail
1    slot1    2023-04-19 15:53:58    power-util       SERVER_12V_ON successful for FRU: 1
1    slot1    2023-04-19 15:54:13    gpiod            FRU: 1, System powered ON

(2) power-util slotX on:
root@bmc-oob:~# power-util slot1 status
Power status for fru 1 : OFF

root@bmc-oob:~# power-util slot1 on
Powering fru 1 to ON state...
Failed to power fru 1 to ON state due to fan fail...
ERROR: power-util fru[1] [PWR_ON] failed

root@bmc-oob:~# power-util slot1 cycle
Power cycling fru 1...
Failed to power cycle fru 1 due to fan fail...
ERROR: power-util fru[1] [POWER_CYCLE] failed

root@bmc-oob:~# power-util slot1 --force on
Powering fru 1 to ON state...

1    slot1    2023-04-19 15:55:43    power-util       SERVER_POWER_ON failed for FRU: 1 due to fan fail
1    slot1    2023-04-19 15:55:48    power-util       SERVER_POWER_CYCLE failed for FRU: 1 due to fan fail
1    slot1    2023-04-19 15:56:00    power-util       SERVER_POWER_ON successful for FRU: 1
1    slot1    2023-04-19 15:56:00    gpiod            FRU: 1, System powered ON

Reviewed By: amithash

Differential Revision: D45120508

fbshipit-source-id: 0394be1a234dec31accd1211395125e81aa36290