common: rest-api: Fix ValueError of endpoint /api/fwinfo (#2705)
Summary:
-Fix ValueError while get endpoint /api/fwinfo and cit_runner RestEndpointTest
-rest_fwinfo.py split fw-util output line by colon then assign to variables "identifier, version"
but for components SB VR, the output line will split to 3 strings but only two variable to store cause this ValueError rising.
```
root@bmc-oob:~# fw-util all --version
...
VCCIN_VSA Version : Renesas A8009F7D, Remaining Writes: 24
VCCIO Version : Renesas 071E99C4, Remaining Writes: 23
VDDQ_ABC Version : Renesas C7CD8991, Remaining Writes: 24
VDDQ_DEF Version : Renesas 39D8D6AA, Remaining Writes: 24
...
```
-modify :split by first colon to guarantee only two strings for "identifier, version"

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/2705

Test Plan:
-Before
```
root@bmc-oob:~# curl http:/localhost:8080/api/fwinfo
{"Information": {"reason": "ValueError('too many values to unpack (expected 2)')"}, "Actions": [], "Resources": []}

root@bmc-oob:/usr/local/bin/tests2# python  cit_runner.py  --run-test tests.fby3.test_rest_endpoint.RestEndpointTest
...
======================================================================
ERROR: test_restendpoint_/api (tests.fby3.test_rest_endpoint.RestEndpointTest) (item='fwinfo')
partial(func, *args, **keywords) - new function with partial application
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 131, in verify_endpoint_resource
    ) from None
common.base_rest_endpoint_test.BaseRestEndpointException: HTTPError on GET /api/fwinfo : <HTTPError 500: 'Internal Server Error'>
```
-After
Build OK and test on fby3

1. get endpoint OK
```
root@bmc-oob:~# curl http:/localhost:8080/api/fwinfo
{"Information": {"fruid_info": {"slot1": {"vendor": "Quanta", "model": "Delta Lake-Class1", "serial_number": "TW3YX04200029", "part_number": "N/A"}, "nic": {"vendor": "Broadcom", "model": "BRCM 100G 1P 57504 OCP Mezz", "serial_number": "N1100FY19450001MCQ", "part_number": "BCM957504-N1100FY"}, "nicexp": {"vendor": null, "model": null, "serial_number": null, "part_number": null}}, "fw_info": {"bmc_ver": "fby3-d83e710a465-dirty", "bmc_cpld_ver": "00030A04", "bic_version": "NA (2ou is empty)"}}, "Actions": [], "Resources": []}
```
2.cit_runner tests.fby3.test_rest_endpoint.RestEndpointTest OK
```
root@bmc-oob:/usr/local/bin/tests2# python  cit_runner.py  --run-test tests.fby3.test_rest_endpoint.RestEndpointTest
test_restendpoint_/api (tests.fby3.test_rest_endpoint.RestEndpointTest)
partial(func, *args, **keywords) - new function with partial application ... ok
test_restendpoint_/api/bmc (tests.fby3.test_rest_endpoint.RestEndpointTest)
partial(func, *args, **keywords) - new function with partial application ... ok
.......
test_restendpoint_/api/spb/logs (tests.fby3.test_rest_endpoint.RestEndpointTest)
partial(func, *args, **keywords) - new function with partial application ... ok
test_restendpoint_/api/spb/sensors (tests.fby3.test_rest_endpoint.RestEndpointTest)
partial(func, *args, **keywords) - new function with partial application ... ok
test_server_httperror_code_404 (tests.fby3.test_rest_endpoint.RestEndpointTest)
Test if REST server return 404 code when url is not accessible ... ok

----------------------------------------------------------------------
Ran 68 tests in 1192.402s

OK
```

Reviewed By: zhdaniel12

Differential Revision: D31684650

fbshipit-source-id: a0812f476f