snapshot-util: add dump all option, password on clear, and cmd line reason
Summary:
1. increase RMA entries from 2 to 3
2. add "dump all" option to retrieve all information
3. add basic protection on --clear operation to prevent accidental clearing
4. add option to allow user to specify RMA reason through command line

Test Plan:
* test new region and dump all command
```
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --mfg reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 556
    Storing to EEPROM...
    Finished
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --rma reason.txt

    Getting logs...
    Getting POST codes...
    File Size: 555
    Storing to EEPROM...
    Finished
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 555
    Storing to EEPROM...
    Finished
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --rma reason.txt
    all Info areas are occupied
    Failed
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --mfg reason.txt

    all Info areas are occupied
    Failed

    root@sled0103gi-oob:/tmp# snapshot-util slot1 --get --all /tmp/dump-all-06-11

    Filename: /tmp/dump-all-06-11-rma1
    File Size: 552
    Dumping from EEPROM...
    Filename: /tmp/dump-all-06-11-rma2
    File Size: 555
    Dumping from EEPROM...
    Filename: /tmp/dump-all-06-11-rma3
    File Size: 555
    Dumping from EEPROM...
    Filename: /tmp/dump-all-06-11-mfi1
    File Size: 556
    Dumping from EEPROM...
    mismatched checksum, 0xfea5 / 0x069a
    Finished
```

* Test clear

```
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --clear --mfg 1
    Error: incorrect --clear command
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --clear --mfg 1 0
    Error: incorrect --clear command
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --clear --mfg 1 571934
    Error: incorrect --clear command
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --clear --mfg 1 571932
    Finished
```

* Test command line reason

```
    root@sled0103gi-oob:/tmp# snapshot-util slot1 --set --rma "this is the 3rd dump"
    Reason file doesn't exist, assume stdin
    Getting logs...
    Getting POST codes...
    File Size: 555
    Storing to EEPROM...
    Finished
```

Reviewed By: zhdaniel12

Differential Revision: D15780705

fbshipit-source-id: bbf9d0f0c1