Simplify Redfish Chassis route handling
Summary:
use of matchers in the route is more idiomatic, so let's drop the statically registered routes, and use matchers in the routing setup
Handle bad submitted routes properly, by returning 404 for multi-slot Chassis server_names on single slot servers
Do the later for Sensors too

Test Plan:
Unit tests:
```
➜  openbmc git:(helium) ✗ ./tests2/ptest-runner rest-api
Found 507 recipes of which 14 define unit-tests
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for nativesdk-mypy SRC_URI entry 001-load-so-fix.patch: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for mypy-native SRC_URI entry 001-load-so-fix.patch: file could not be found
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/recipes-utils/mypy-native/mypy_0.910.bb: Unable to get checksum for mypy SRC_URI entry 001-load-so-fix.patch: file could not be found
Parsing recipes: 100% |########################################################| Time: 0:00:14
WARNING: No recipes available for:
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby3-image.bbappend
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby35-image.bbappend
Initialising tasks: 100% |#####################################################| Time: 0:00:03
START: ptest-runner
2021-11-25T02:45
BEGIN: /usr/lib/rest-api/ptest
/usr/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:110: DeprecationWarning: "coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def handler_wrapper(*args, **kwargs):
/usr/lib/python3.8/site-packages/aiohttp/helpers.py:141: DeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead
  task = asyncio.Task.current_task(loop=loop)
.Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9f88>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9ce8>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9868>()]>>
./usr/local/fbpackages/rest-api/test_async_ratelimiter.py:88: RuntimeWarning: coroutine 'TestRatelimiterWorks.__assert_normal_request' was never awaited
  self.__assert_normal_request("GET", "agent2")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9730>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:55> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9aa8>()]>>
.Task was destroyed but it is pending!
task: <Task pending name='Task-53' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9250>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-55' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:54> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf62f9418>()]>>
............../usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............../usr/lib/python3.8/site-packages/aiohttp/web_server.py:44: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.gather(*coros, loop=self._loop)
...................s...../usr/lib/python3.8/linecache.py:171: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmp8zzr7uf7' mode='ab' closefd=True>
  get_source = getattr(loader, 'get_source', None)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
.............................................................
----------------------------------------------------------------------
Ran 119 tests in 1.801s

OK (skipped=1)
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
/usr/local/fbpackages/rest-api/acl_config.py                                   2      0   100%
/usr/local/fbpackages/rest-api/acl_providers/__init__.py                       0      0   100%
/usr/local/fbpackages/rest-api/acl_providers/cached_acl_provider.py           37      2    95%   52-53
/usr/local/fbpackages/rest-api/acl_providers/common_acl_provider_base.py      41      1    98%   61
/usr/local/fbpackages/rest-api/async_ratelimiter.py                           18      1    94%   56
/usr/local/fbpackages/rest-api/boardroutes.py                                  1      0   100%
/usr/local/fbpackages/rest-api/common_auth.py                                 56      5    91%   57-60, 139
/usr/local/fbpackages/rest-api/common_logging.py                              32      2    94%   61, 71
/usr/local/fbpackages/rest-api/common_middlewares.py                          76     12    84%   48, 68-69, 76-80, 89-90, 125-126
/usr/local/fbpackages/rest-api/common_utils.py                                57     41    28%   21-29, 43-48, 52-67, 83-88, 96, 102-116
/usr/local/fbpackages/rest-api/common_webapp.py                               13      6    54%   9, 13-19
/usr/local/fbpackages/rest-api/redfish_account_service.py                     17      7    59%   25-34, 38-46
/usr/local/fbpackages/rest-api/redfish_base.py                                54     36    33%   98, 105, 121-125, 128-139, 150-153, 156-163, 166-169, 172
/usr/local/fbpackages/rest-api/redfish_bios_firmware_dumps.py                204    154    25%   23-24, 40-41, 45-46, 50-51, 55-56, 89, 96-102, 107-117, 120-172, 177-180, 185-209, 212-258, 265-278, 281-312, 324, 327, 330, 333, 336
/usr/local/fbpackages/rest-api/redfish_chassis.py                             29      0   100%
/usr/local/fbpackages/rest-api/redfish_chassis_helper.py                     188    118    37%   60-62, 66-67, 71-72, 77, 95-106, 112-119, 127-133, 137-189, 195-202, 206-225, 250-251, 257-299, 305, 309, 333
/usr/local/fbpackages/rest-api/redfish_common_routes.py                       62      1    98%   30
/usr/local/fbpackages/rest-api/redfish_computer_system.py                     55     26    53%   30-42, 45-48, 53-81, 86-102, 105-124, 136, 139, 142
/usr/local/fbpackages/rest-api/redfish_log_service.py                         88      9    90%   31, 37, 44, 54, 85, 89, 113, 119, 140
/usr/local/fbpackages/rest-api/redfish_managers.py                           104     49    53%   22-30, 34-46, 50-55, 59-64, 69-91, 142-151
/usr/local/fbpackages/rest-api/redfish_powercycle.py                          59     10    83%   68, 79, 85, 93, 103, 122, 127, 129, 137, 142
/usr/local/fbpackages/rest-api/redfish_sensors.py                            117     26    78%   24-25, 29, 64, 98-101, 109, 125, 142, 201, 203, 205, 207, 209, 211, 217-233
/usr/local/fbpackages/rest-api/redfish_service_root.py                        27      8    70%   39, 41-42, 49-59, 63-2506
/usr/local/fbpackages/rest-api/redfish_session_service.py                     12      7    42%   7-21, 25-34
/usr/local/fbpackages/rest-api/rest_config.py                                 37      1    97%   103
/usr/local/fbpackages/rest-api/rest_fruid.py                                  21     16    24%   30-47
/usr/local/fbpackages/rest-api/rest_fscd_sensor_data.py                       30      3    90%   59-62
/usr/local/fbpackages/rest-api/rest_fwinfo.py                                 47      1    98%   78
/usr/local/fbpackages/rest-api/rest_gpios.py                                  22      4    82%   33-59
/usr/local/fbpackages/rest-api/rest_mmc.py                                    25      0   100%
/usr/local/fbpackages/rest-api/rest_modbus_cmd.py                             86     10    88%   105, 125-128, 133, 137-141, 172
/usr/local/fbpackages/rest-api/rest_pal_legacy.py                            169    141    17%   48-49, 53-68, 72-80, 84-92, 97-105, 109-116, 124-145, 150-197, 201-216, 220-230, 234-236, 240-245, 249-257
/usr/local/fbpackages/rest-api/rest_utils.py                                   6      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                                       1792    697    61%
DURATION: 5
END: /usr/lib/rest-api/ptest
2021-11-25T02:45
STOP: ptest-runner

````

Manual testing:
Chassis/1 on single slot:
```
curl -k https://fboss8845005-oob.snc1:8443/redfish/v1/Chassis/1
{"Status": {"Health": "OK", "State": "Enabled"}, "Id": "1", "odata.id": "/redfish/v1/Chassis/1", "Name": "Computer System Chassis", "Manufacturer": "Joytech", "SerialNumber": "AF45007844", "PowerState": "On", "odata.context": "/redfish/v1/$metadata#Chassis.Chassis", "ChassisType": "RackMount", "Sensors": {"odata.id": "/redfish/v1/Chassis/1/Sensors"}, "odata.type": "#Chassis.v1_15_0.Chassis", "Model": "Wedge-DC-F", "Links": {"ManagedBy": [{"odata.id": "/redfish/v1/Managers/1"}]}}%
```
Chassis/server(x) on single slot:
```
➜  openbmc git:(helium) ✗ curl -vk https://fboss8845005-oob.snc1:8443/redfish/v1/Chassis/server4
*   Trying 2401:db00:116:302c:ce37:abff:fe6d:e07d...
* TCP_NODELAY set
* Connected to fboss8845005-oob.snc1 (2401:db00:116:302c:ce37:abff:fe6d:e07d) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  start date: Jan 17 02:04:21 2020 GMT
*  expire date: Jan 16 02:04:21 2022 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /redfish/v1/Chassis/server4 HTTP/1.1
> Host: fboss8845005-oob.snc1:8443
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Content-Length: 0
< Date: Thu, 25 Nov 2021 10:47:32 GMT
< Server: Python/3.5 aiohttp/2.1.0
<
* Connection #0 to host fboss8845005-oob.snc1 left intact
```
Chassis/1/Sensors
```
➜  openbmc git:(helium) ✗ curl -k https://fboss8845005-oob.snc1:8443/redfish/v1/Chassis/1/Sensors
{"Members": [{"odata.id": "/redfish/v1/Chassis/1/Sensors/tmp75-i2c-3-48_1e78a100.i2c-bus_InletTemp"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/adm1278-i2c-12-10_1e78a440.i2c-bus_vin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/adm1278-i2c-12-10_1e78a440.i2c-bus_vout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/adm1278-i2c-12-10_1e78a440.i2c-bus_temp1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/adm1278-i2c-12-10_1e78a440.i2c-bus_pin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/adm1278-i2c-12-10_1e78a440.i2c-bus_iout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-1-60_1e78a080.i2c-bus_vin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-1-60_1e78a080.i2c-bus_vout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-1-60_1e78a080.i2c-bus_temp1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-1-60_1e78a080.i2c-bus_pout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-1-60_1e78a080.i2c-bus_iout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan2front"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan3front"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan1front"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan0front"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan2rear"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan3rear"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan1rear"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/aspeed_pwm_tacho-isa-0000_ISAadapter_Fan0rear"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_vin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_vout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_fan1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_temp1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_temp2"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_pin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_pout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_iin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/pfe1100-i2c-7-59_1e78a300.i2c-bus_iout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/fb_panther_plus-i2c-4-40_1e78a140.i2c-bus_CPUTemp"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/fb_panther_plus-i2c-4-40_1e78a140.i2c-bus_DIMM0Temp"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/tmp75-i2c-3-49_1e78a100.i2c-bus_SwitchTemp"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-2-60_1e78a0c0.i2c-bus_vin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-2-60_1e78a0c0.i2c-bus_vout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-2-60_1e78a0c0.i2c-bus_temp1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-2-60_1e78a0c0.i2c-bus_pout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-2-60_1e78a0c0.i2c-bus_iout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-8-60_1e78a340.i2c-bus_vin"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-8-60_1e78a340.i2c-bus_vout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-8-60_1e78a340.i2c-bus_temp1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-8-60_1e78a340.i2c-bus_pout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ncp4200-i2c-8-60_1e78a340.i2c-bus_iout1"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ast_adc_hwmon-isa-0000_ISAadapter_+1CoreVoltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ast_adc_hwmon-isa-0000_ISAadapter_+1AnalogVoltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ast_adc_hwmon-isa-0000_ISAadapter_+5Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ast_adc_hwmon-isa-0000_ISAadapter_+3.3Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/ast_adc_hwmon-isa-0000_ISAadapter_+2.5Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/max127-i2c-6-28_1e78a1c0.i2c-bus_+1Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/max127-i2c-6-28_1e78a1c0.i2c-bus_+2.5Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/max127-i2c-6-28_1e78a1c0.i2c-bus_+1Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/max127-i2c-6-28_1e78a1c0.i2c-bus_+3.3Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/max127-i2c-6-28_1e78a1c0.i2c-bus_+5Voltage"}, {"odata.id": "/redfish/v1/Chassis/1/Sensors/tmp75-i2c-3-4a_1e78a100.i2c-bus_OutletTemp"}], "odata.type": "#SensorCollection.SensorCollection", "odata.id": "/redfish/v1/Chassis/1/Sensors", "Members@odata.count": 52, "Name": "Chassis sensors"}
```

Chassis/server4/Sensors on single slot
```
➜  openbmc git:(helium) ✗ curl -kv https://fboss8845005-oob.snc1:8443/redfish/v1/Chassis/server4/Sensors
*   Trying 2401:db00:116:302c:ce37:abff:fe6d:e07d...
* TCP_NODELAY set
* Connected to fboss8845005-oob.snc1 (2401:db00:116:302c:ce37:abff:fe6d:e07d) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  start date: Jan 17 02:04:21 2020 GMT
*  expire date: Jan 16 02:04:21 2022 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /redfish/v1/Chassis/server4/Sensors HTTP/1.1
> Host: fboss8845005-oob.snc1:8443
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Content-Length: 0
< Date: Thu, 25 Nov 2021 10:48:26 GMT
< Server: Python/3.5 aiohttp/2.1.0
<
* Connection #0 to host fboss8845005-oob.snc1 left intact
```

Reviewed By: doranand

Differential Revision: D32648045

fbshipit-source-id: ca2d3c55a9