uboot: automatic stop watchdog when stop in u-boot cli
Summary:
use script to automatically stop the watchdog when user get into
uboot command line.

we have duplicated code in
facebook_common_v0.h ==> will retire after all platforms onboard image-meta
facebook_common_v1.h ==> will split out ast-g5 common stuff to fbobmc-ast-g5.h
fbobmc-ast-g6.h ==> will move acebook common code into facebook_common.h

Test Plan:
With QEMU, change the watchdog to 30s.
CMM:
```
U-Boot 2019.04 cmm-d83d88355089-dirty (Apr 23 2021 - 06:28:48 +0000)

Model: Aspeed BMC
DRAM:  434 MiB
Watch Dog stopped.
watchdog@1e785020 set timeout after 30000000us ; enable 2nd boot
Watchdog: 30s
MMC:
Loading Environment from SPI Flash... SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:
Warning: ethernet@1e680000 (eth1) using random MAC address - 8e:0c:2d:76:b8:6b
eth1: ethernet@1e680000
autoboot in 2 seconds (stop with 'Delete' key)...
stop wdt2
CMM-boot=> md 1e785000
1e785000: 03ef1480 03ef1480 00000000 00000000    ................
1e785010: 00000000 00000000 000000ff 00000000    ................
1e785020: 01c9c380 01c9c380 00000000 00000000    ................
1e785030: 00000000 00000000 000000ff 023ffff3    ..............?.
1e785040: 03ef1480 03ef1480 00000000 00000000    ................
1e785050: 00000000 00000000 000000ff 00000000    ................
...
CMM-boot=> reset
resetting ...
Watch Dog stopped.
ast_sysreset_request( type=1 )
Full-chip reset
watchdog@1e785000 set timeout after 1000us

U-Boot 2019.04 cmm-d83d88355089-dirty (Apr 23 2021 - 06:28:48 +0000)

Model: Aspeed BMC
DRAM:  434 MiB
Watch Dog stopped.
watchdog@1e785020 set timeout after 30000000us ; enable 2nd boot
Watchdog: 30s
MMC:
Loading Environment from SPI Flash... SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:
Warning: ethernet@1e680000 (eth1) using random MAC address - 8e:0c:2d:76:b8:6b
eth1: ethernet@1e680000
autoboot in 2 seconds (stop with 'Delete' key)...
Wrong Image Format for bootm command
ERROR: can't get kernel image!
CMM-boot=> md 1e785000
1e785000: 03ef1480 03ef1480 00000000 00000000    ................
1e785010: 00000000 00000000 000000ff 023ffff3    ..............?.
1e785020: 01c9c380 01c9c380 00000000 00000093    ................
1e785030: 00000000 00000000 000000ff 023ffff3    ..............?.
1e785040: 03ef1480 03ef1480 00000000 00000000    ................
1e785050: 00000000 00000000 000000ff 00000000    ................
...
CMM-boot=>

U-Boot 2019.04 cmm-d83d88355089-dirty (Apr 23 2021 - 06:28:48 +0000)

Model: Aspeed BMC
DRAM:  434 MiB
Watch Dog stopped.
watchdog@1e785020 set timeout after 30000000us ; enable 2nd boot
Watchdog: 30s
MMC:
Loading Environment from SPI Flash... SF: Detected w25q256 with page size 256 Bytes, erase size 4 KiB, total 32 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:
Warning: ethernet@1e680000 (eth1) using random MAC address - 6a:0b:6e:33:47:ff
eth1: ethernet@1e680000
autoboot in 2 seconds (stop with 'Delete' key)...
Wrong Image Format for bootm command
ERROR: can't get kernel image!
CMM-boot=> QEMU: Terminated

```

GC
```
U-Boot SPL 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:06 +0000)
SYS_INIT_RAM_END=10016000
CONFIG_SYS_INIT_SP_ADDR=10015800
CONFIG_MALLOC_F_ADDR=10012800
gd = sp = 10012730
fdt=00013e80
Setup flash: write enable, addr4B, CE1 AHB 64MB window
!!!QEMU!!! FMC_CE_CTRL = 0x00000000
Watchdog: 300s
vboot_verify_subordinate 301
U-Boot configuration was not verified.
Check that the 'required' field for each key- is set to 'conf'.
Check the board configuration for supported hash algorithms.
vboot_verify_uboot 364
Blindly jumping to 0x48104000

U-Boot 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:06 +0000)

SOC: AST2600-A1
eSPI Mode: SIO:Enable : SuperIO-2e
Eth: MAC0: RGMII, MAC1: RGMII, MAC2: RGMII, MAC3: RGMII
Model: Aspeed BMC
DRAM:  440 MiB (capacity:512 MiB, VGA:64 MiB), ECC on
Watchdog: 30s
MMC:
Loading Environment from SPI Flash... SF: Detected w25q512jv with page size 256 Bytes, erase size 64 KiB, total 64 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Model: Aspeed BMC
Net:   No MDIO found.
No ethernet found.
autoboot in 3 seconds (stop with 'Delete' key)...
stop wdt1
fbgc# md 1e785000
1e785000: 01c9c380 01c9c380 00000000 00000000    ................
1e785010: 00000000 00000000 000000ff 030f1ff1    ................
1e785020: 00000000 00000000 00000000 00000000    ................
1e785030: 00000000 00000000 00000000 00000000    ................
1e785040: 03ef1480 03ef1480 00000000 00000000    ................
1e785050: 00000000 00000000 000000ff 00000000    ................

fbgc# reset
resetting ...

U-Boot SPL 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:06 +0000)
SYS_INIT_RAM_END=10016000
CONFIG_SYS_INIT_SP_ADDR=10015800
CONFIG_MALLOC_F_ADDR=10012800
gd = sp = 10012730
fdt=00013e80
Setup flash: write enable, addr4B, CE1 AHB 64MB window
!!!QEMU!!! FMC_CE_CTRL = 0x00000000
Watchdog: 300s
U-Boot failed to execute.
vboot_reset 395
Booting recovery U-Boot.
Blindly jumping to 0x40040000

U-Boot 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:16 +0000)

SOC: AST2600-A1
eSPI Mode: SIO:Enable : SuperIO-2e
Eth: MAC0: RGMII, MAC1: RGMII, MAC2: RGMII, MAC3: RGMII
Model: Aspeed BMC
DRAM:  440 MiB (capacity:512 MiB, VGA:64 MiB), ECC on
Watchdog: 30s
MMC:
In:    serial
Out:   serial
Err:   serial
Model: Aspeed BMC
Net:   No MDIO found.
No ethernet found.
autoboot in 3 seconds (stop with 'Delete' key)...
SF: Detected w25q512jv with page size 256 Bytes, erase size 64 KiB, total 64 MiB
Wrong Image Format for bootm command
ERROR: can't get kernel image!
Wrong Image Format for bootm command
ERROR: can't get kernel image!
fbgc# md 1e785000
1e785000: 01c9c380 01c9c380 00000000 00000013    ................
1e785010: 00000000 00000000 000000ff 030f1ff1    ................
1e785020: 00000000 00000000 00000000 00000000    ................
1e785030: 00000000 00000000 00000000 00000000    ................
1e785040: 03ef1480 03ef1480 00000000 00000000    ................
1e785050: 00000000 00000000 000000ff 00000000    ................
1e785060: 00000000 00000000 00000000 00000000    ................

fbgc#
U-Boot SPL 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:06 +0000)
SYS_INIT_RAM_END=10016000
CONFIG_SYS_INIT_SP_ADDR=10015800
CONFIG_MALLOC_F_ADDR=10012800
gd = sp = 10012730
fdt=00013e80
Setup flash: write enable, addr4B, CE1 AHB 64MB window
!!!QEMU!!! FMC_CE_CTRL = 0x00000000
Watchdog: 300s
vboot_verify_subordinate 301
U-Boot configuration was not verified.
Check that the 'required' field for each key- is set to 'conf'.
Check the board configuration for supported hash algorithms.
vboot_verify_uboot 364
Blindly jumping to 0x48104000

U-Boot 2019.04 grandcanyon-d83d88355089-dirty (Apr 23 2021 - 06:14:06 +0000)

SOC: AST2600-A1
eSPI Mode: SIO:Enable : SuperIO-2e
Eth: MAC0: RGMII, MAC1: RGMII, MAC2: RGMII, MAC3: RGMII
Model: Aspeed BMC
DRAM:  440 MiB (capacity:512 MiB, VGA:64 MiB), ECC on
Watchdog: 30s
MMC:
Loading Environment from SPI Flash... SF: Detected w25q512jv with page size 256 Bytes, erase size 64 KiB, total 64 MiB
*** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Model: Aspeed BMC
Net:   No MDIO found.
No ethernet found.
autoboot in 3 seconds (stop with 'Delete' key)...
stop wdt1
fbgc# QEMU: Terminated

```

Reviewed By: benwei13

Differential Revision: D27961961

fbshipit-source-id: ba2115f379