fw-util: Switch to using ptest to run unit tests
Summary:
Switch to building a ptest executable along with
the regular component.

Test Plan:
A. Run tests (Some tests are expected to fail since running unit-tests have not been part of standard development)
```
devvm350:openbmc :-) (fw-util-ptest) # ./tests2/experimental/ptest-runner fw-util
Found 437 recipes of which 7 define unit-tests
<snip>
START: ptest-runner
2020-07-14T13:54
BEGIN: /usr/lib/fw-util/ptest
[==========] Running 7 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from ComponentTest
[ RUN      ] ComponentTest.FruListTest
[       OK ] ComponentTest.FruListTest (0 ms)
[ RUN      ] ComponentTest.BaseClassTest
[       OK ] ComponentTest.BaseClassTest (0 ms)
[ RUN      ] ComponentTest.AliasTest
[       OK ] ComponentTest.AliasTest (0 ms)
[----------] 3 tests from ComponentTest (0 ms total)

[----------] 4 tests from BmcComponentTest
[ RUN      ] BmcComponentTest.DefaultSystemVersion
[       OK ] BmcComponentTest.DefaultSystemVersion (0 ms)
[ RUN      ] BmcComponentTest.MTDVersion
[       OK ] BmcComponentTest.MTDVersion (7 ms)
[ RUN      ] BmcComponentTest.MTDFlash
Cannot open blahimage
Cannot open blahimage
<snip>
[  FAILED  ] BmcComponentTest.MTDOffsetFlash (1 ms)
[----------] 4 tests from BmcComponentTest (8 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 2 test cases ran. (8 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] BmcComponentTest.MTDFlash
[  FAILED  ] BmcComponentTest.MTDOffsetFlash

 2 FAILED TESTS

ERROR: Exit status is 256
DURATION: 1
END: /usr/lib/fw-util/ptest
2020-07-14T13:54
STOP: ptest-runner
```

B. Test fw-util on platform to ensure nothing is broken.
```
root@dhcp-100-96-192-149:~# fw-util bmc --update bmc /tmp/flash-fbtp-20200714205832.signed
Flashing to device: /dev/mtd6
Erasing block: 292/292 (100%)
Writing kb: 18666/18666 (100%)
Verifying kb: 18666/18666 (100%)
Upgrade of bmc : bmc succeeded
```

Reviewed By: benwei13

Differential Revision: D22535129

fbshipit-source-id: a31e546bc1