common: fscd: Fix ptest attribute error
Summary:
We were failing on the following attribute error in several ptest cases:

```
FAIL fsc_bmc_machine_tester.FscdBmcMachineUnitTest2.test_sensor_read (0.001s)
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 672, in run
    self._callSetUp()
  File "/usr/lib/python3.8/unittest/case.py", line 630, in _callSetUp
    self.setUp()
  File "/usr/lib/fscd/ptest/fsc_base_tester.py", line 39, in setUp
    self.define_fscd()
  File "/usr/lib/fscd/ptest/fsc_bmc_machine_tester.py", line 56, in define_fscd
    super(FscdBmcMachineUnitTest2, self).define_fscd(
  File "/usr/lib/fscd/ptest/fsc_base_tester.py", line 53, in define_fscd
    self.fscd_tester.builder()
  File "/usr/bin/fscd.py", line 811, in builder
    self.build_profiles()
  File "/usr/bin/fscd.py", line 246, in build_profiles
    if isinstance(sensor.source, FscSensorSourceJson):
AttributeError: 'Sensor' object has no attribute 'source'
```

This is cause we weren't initializing `self.source` in the `Sensor` class for code paths in the ptest environment.

Test Plan:
Verified `fscd` recipe in `ptest-runner`:

```
pdel@devvm660:openbmc$ python3 tests2/ptest-runner fscd -b build-qemux86/ --force-rebuild
Found 520 recipes of which 15 define unit-tests
Loading cache: 100% |##########################################################################################| Time: 0:00:0
WARNING: No recipes available for:
  /data/users/pdel/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby3-image.bbappend
  /data/users/pdel/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby35-image.bbappend
Initialising tasks: 100% |#####################################################################################| Time: 0:00:0
START: ptest-runner
2022-02-04T12:15
BEGIN: /usr/lib/fscd/ptest
PASS fsc_config_tester.FscdConfigUnitTest.test_config_params (0.003s)
PASS fsc_config_tester.FscdConfigUnitTest.test_zone_config (0.002s)
PASS fsc_config_tester.FscdConfigUnitTest.test_fan_config (0.002s)
PASS fsc_config_tester.FscdConfigUnitTest.test_fan_zone_config (0.002s)
PASS fsc_config_tester.FscdConfigUnitTest.test_profile_config (0.002s)
PASS fsc_bmc_machine_tester.FscdBmcMachineUnitTest.test_sensor_read (0.161s)
/bin/sh: /usr/local/bin/fan-util: No such file or directory
PASS fsc_bmc_machine_tester.FscdBmcMachineUnitTest.test_fan_read (0.124s)
PASS fsc_bmc_machine_tester.FscdBmcMachineUnitTest2.test_sensor_read (0.079s)
PASS fsc_bmc_machine_tester.FscdBmcMachineUnitTest2.test_fan_read (0.359s)
PASS fsc_bmc_machine_tester.FscdBmcMachineUnitTest2.test_fan_write_all (0.156s)
PASS fsc_operational_tester.FscdOperationalTest.test_dead_fan (0.133s)
PASS fsc_operational_tester.FscdOperationalTest.test_chassis_intrusion (0.570s)
PASS fsc_operational_tester.FscdOperationalTest.test_fan_led (0.003s)
PASS fsc_sysfs_tester.FscdSysfsTester.test_sensor_read (0.001s)
PASS fsc_sysfs_tester.FscdSysfsTester.test_fan_read (0.001s)
PASS fsc_sysfs_tester.FscdSysfsTester.test_fsc_safe_guards (0.004s)
PASS fsc_sysfs_tester.FscdSysfsOperationalTester.test_fscd_operation (0.363s)
Total Tests=17
Total Failed Tests=0
Total Errored Tests=0

DURATION: 3
END: /usr/lib/fscd/ptest
2022-02-04T12:15
STOP: ptest-runner
```

Reviewed By: amithash

Differential Revision: D34015470

fbshipit-source-id: 6059b8e585