Fix fit-sign for newer OpenBMC images
Summary:
So, I recently updated the signing tools to support Python 3 (D29776252), and I tested it pretty thoroughly, but almost exclusively on TiogaPass, which produces legacy images. Post-2020, OpenBMC images contain a JSON metadata section with an md5 checksum. For example, YosemiteV3 and Elbert include this JSON metadata, but TiogaPass does _not_. `fit-sign` is injecting bytes into the image, so it needs to update the md5 checksum on newer images. I missed this in my previous diff:

  def update_rom_checksum():
      rom_changed = False
      with open(args.output, 'r') as fh:
          fh.seek(0)
          current_md5 = hashlib.md5(fh.read(args.rom_size)).hexdigest()
          if current_md5 != rom_part_info["md5"]:
              rom_part_info["md5"] = current_md5
              rom_changed = True
      return rom_changed

So when you run `fit-sign` on a new style image with Python 3, you get this error:

  Traceback (most recent call last):
    File "./fit-sign", line 599, in <module>
      sys.exit(main())
    File "./fit-sign", line 453, in main
      update_spl_checksum("Signed")
    File "./fit-sign", line 56, in update_spl_checksum
      if image_meta and update_rom_checksum():
    File "./fit-sign", line 33, in update_rom_checksum
      current_md5 = hashlib.md5(fh.read(args.rom_size)).hexdigest()
    File "/usr/lib64/python3.6/codecs.py", line 321, in decode
      (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 3: invalid continuation byte

Because in Python 3, when you open a file with `'r'`, it expects a utf-8 stream. I fixed this in a bunch of places previously by opening with `'rb'`, I just neglected to do a proper "grep -r open tools/verified-boot/signing" to make sure that I checked every spot.

After this change, now I'm relatively certain that I've updated all of these spots:

  $ grep -r open tools/verified-boot/signing
  tools/verified-boot/signing/fit-signsub:    with open(args.filename, 'rb') as fh:
  tools/verified-boot/signing/fit-cs:    with open(filename, 'rU') as fh:
  tools/verified-boot/signing/fit-cs:        with open(tmp.name) as fh:
                                                  ^^^^^^^^^^^^^^This one is for printing out the device tree from
                                                                decompilation output, which I think should always
                                                                be utf-8
  tools/verified-boot/signing/fit-cs:    with open(args.template, "rU") as fh:
  tools/verified-boot/signing/fit-cs:        with open(args.subtemplate, "rU") as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.output, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.output, "r+b") as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.output, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.output, 'wb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.output, 'ab' if offset > 0 else 'wb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(filename, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(filename, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(path, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(path, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.filename, 'rb') as fh:
  tools/verified-boot/signing/fit-sign:    with open(args.filename, "rb") as fh:
  tools/verified-boot/signing/vboot-sign:    openssl genrsa -F4 -out "$KEYS/kek/kek.key" 4096
  tools/verified-boot/signing/vboot-sign:    openssl rsa -in "$KEYS/kek/kek.key" -pubout > "$KEYS/kek/kek.pub"
  tools/verified-boot/signing/vboot-sign:    openssl genrsa -F4 -out "$KEYS/subordinate/subordinate.key" 4096
  tools/verified-boot/signing/vboot-sign:    openssl rsa -in "$KEYS/subordinate/subordinate.key" -pubout > "$KEYS/subordinate/subordinate.pub"
  tools/verified-boot/signing/vboot-sign:    LD_LIBRARY_PATH=$POKY_BUILD/tmp/sysroots-components/x86_64/openssl-native/usr/lib:$LD_LIBRARY_PATH \
  tools/verified-boot/signing/vboot-sign:LD_LIBRARY_PATH=$POKY_BUILD/tmp/sysroots-components/x86_64/openssl-native/usr/lib:$LD_LIBRARY_PATH \

For reference, the `fit-cs` code path that uses `open(tmp.name)` is exercised
by the `--no-out` option:

  ./fit-cs --template store.dts.in ./kek/ --no-out
  /dts-v1/;

  / {
	  timestamp = <0x610053c8>;
	  no-fallback;

	  signature {

		  key-kek {
			  required = "image";
			  algo = "sha256,rsa4096";
			  rsa,r-squared = <0x3a021eea 0xc5827c0b 0xb0e4a49b 0xac2365af 0x8a449c88 0xf68819d1 0xf0ffb996 0x6c44c32a 0xabde3ba2 0xecbf223a 0x79e0ac2b 0x330ac025 0x720151a 0x1c244e95 0x47942de9 0xdc9ad06a 0x6601f55 0x226cbeab 0xccc3716 0xc53c2774 0x642e3413 0x459566d1 0xd68363f1 0x32925a17 0x83e9b024 0x79124b65 0x538814f 0x70387900 0x77f1e8f0 0xf53c60ba 0x7161271a 0x5643fa0d 0x9709435a 0xc34f9092 0xc1fa8900 0xa4837328 0x5ae7dfc1 0x1595593a 0x7e8776b5 0xebca9f0f 0x49529cac 0xcb5741c4 0xb84f5f3d 0xc39b55e2 0x515fe3ca 0xc8111264 0xc86f25da 0xe755758b 0x8cfa80c5 0x4760d7e5 0xe7699ab 0xee651ed9 0x697e89d4 0x3ee6956a 0x7509a7a7 0xbdab825 0x903ce21d 0x3804171e 0x79812f3d 0x1120dced 0x87983050 0xdcf09cef 0x7970d5d1 0x79eac78 0x7b7fb7e0 0x1e0a62fe 0x484aa837 0x14b35b25 0x526c3c34 0xe9ad5ccf 0xf8e8227b 0xb6dd783e 0x9d9f3134 0xd4b93524 0x12ea1e1 0x22e1019e 0xed37c23b 0xef9b0e05 0x1f638191 0xb59a8e06 0xda41cc5e 0x8bf6ba9 0x5e2071ad 0xa95ee27c 0x483b9592 0x83ee996e 0x241f8d84 0x618bd994 0x96180f22 0x7327e2bd 0x31d77d4f 0xccfbc558 0xdba51d02 0x9e82a192 0x346402c 0x770c13c 0xf7562c2 0x9081e938 0x57a6ac36 0x6c24ca7b 0x7e0f6f30 0xa774539b 0x94ae25b2 0x7cc612f4 0x17794e3 0xe8f64b40 0x9988e766 0x931993b6 0xc1700813 0xac66e2ee 0xb5c912b2 0x81f5dc48 0x308c9bcb 0x7a6e3885 0x59e1052c 0x402f23a8 0x1748a4a0 0x7a62e9d9 0x3c4adc81 0xa7a61342 0xc9cac6b5 0x2249a80d 0xaa377437 0x1617a6b7 0x15d23947 0x47864e3 0x92014c7d 0xe0968659>;
			  rsa,modulus = <0xaf37dc29 0x53d591d4 0x2f831f46 0x86840333 0x91047f24 0x51a5729e 0x393746ca 0xbd5162a2 0xdeabcff1 0xd81d85a7 0xe79bf68c 0x351ded6b 0xff5d327 0x40210b38 0x8bf01881 0x1799c769 0x9a5d9e43 0x36700b14 0xe5caeec8 0xc377c41e 0xa264e597 0xa92e1a37 0xb1ebdd79 0x2ebc4108 0x3633ee80 0x1dfbd44a 0xfd8c1080 0x89548e32 0x99acced 0x5da628f3 0xffb4c7a3 0x63d0eb84 0x451319f0 0x4937fe52 0xd8f9993d 0x83e91651 0x8a05fd6d 0x1d58b13e 0xd7ad6e4a 0x90fee9bb 0xb90ba5c3 0xdba46dd 0xc68d5bc 0x6c68374f 0x5e751fa6 0x53cc1e0 0x61f26d2a 0x5f3ce2ca 0x8f092823 0x820a29af 0xaffa5bde 0x5d6e8955 0xec371c56 0x640357e2 0xb8d7aed5 0x2a5f6575 0xcb714619 0x3023e653 0xcba94333 0xbca8fd06 0x64bec4d0 0x725f6c1a 0xf9aa9f06 0x6bd6290 0x1f8ef766 0x5ce43159 0xdbb5a4f 0xaed8c44f 0xdf78fd39 0x10be3e19 0x7952ccf3 0x6e9c1d4c 0x1de862cd 0x70d0e8b9 0xc8d14234 0x94e171ee 0x6078a9ca 0x63f08fb9 0xab2d90b2 0xb4a7017a 0xc8d2e107 0x8b90d47b 0xd54a6ad6 0x4736cf9 0x5a71afb 0x9cb22700 0x67c7b09b 0x24451dd9 0xbf29aa0c 0xaa96227a 0x2f5efa71 0x3cfcffb4 0x78cfa41d 0x49c5332b 0x26897bd7 0x7e98eca0 0x81d45344 0x121b3376 0x22e57ff2 0xe8bd7aad 0xa6e1f253 0xdf096ada 0x40245f01 0x2564b09e 0x545cf7ae 0x6abb9c81 0x6bf13aa1 0xfc3179e9 0x2567b120 0x4d7db8df 0x731a54f4 0x823caf3e 0xd9cbc8e 0x4804ebdd 0xf7e2ac6f 0xf76b1f3b 0xf7b63535 0xc77f38d1 0xdc7f5ae2 0x28a1d09c 0x29559a80 0x5ddfead4 0x6ae86661 0x699c7f0e 0x17578d05 0x78ed4c1d 0x3b8692b2 0x68725769>;
			  rsa,exponent = <0x0 0x10001>;
			  rsa,n0-inverse = <0xe7e05727>;
			  rsa,num-bits = <0x1000>;
			  key-name-hint = "kek";
		  };

	  };
  };

Its output is from the device-tree decompiler, so that should always be utf-8.

Additionally, I added a `--force` option to `vboot-sign`. This is also something specific to new-style images, because of the following code in `fit-sign`:

  image_meta = None
  rom_part_info = None
  try:
      image_meta = load_image_meta()
      rom_part_info = override_defaut_args_with_image_meta()
  except Exception as e:
      print("No image meta found: %s" % repr(e))
      print("Signing legacy image")

  if not ( args.lock or args.time_back or args.force ):
      if args.keyname is None and image_meta is not None:
	  print("Please use HSM key (--keyname <hsm/key/name>) to sign new image")
	  print("Or (--force) to sign without using HSM key")
	  sys.exit(2)
      if args.keyname is not None and image_meta is None:
	  print("Please don't use HSM key to sign legacy image")
	  print("Or (--force) to sign using HSM key")
	  sys.exit(3)

When you try to use a self-signed key with a new-style image, this check will prevent you from doing so, to encourage people to use HSM keys. This is not specific to Python 3, this affects Python 2.7 too.

  ./vboot-sign --build ~/local/openbmc/build-fby3/ --python python2.7
  POKY_BUILD=/home/pdel/local/openbmc/build-fby3/
  POKY_DIR=/home/pdel/local/openbmc
  KEYS_DIR=/data/users/pdel/openbmc/tools/verified-boot/signing
  IMAGE_NAME=fby3
  find mkimage in u-boot-tools-native
  ~/local/openbmc/tools/verified-boot/signing ~/local/openbmc/tools/verified-boot/signing
  Try loading image meta from image /home/pdel/local/openbmc/build-fby3//tmp/deploy/images/fby3/flash-fby3
  override args.rom_size: 0x15000 => 0x40000
  override args.offset: 0x80000 => 0x100000
  override args.max_size: 0x60000 => 0xa0000
  override args.os: 0xe0000 => 0x1a0000
  Please use HSM key (--keyname <hsm/key/name>) to sign new image
  Or (--force) to sign without using HSM key
  ~/local/openbmc/tools/verified-boot/signing

Legacy images don't have this problem, I guess because we expect that people will be self-signing them.

  ./vboot-sign --build ~/local/openbmc/build-fbttn/ --python python2.7
  ...
  Try loading image meta from image /home/pdel/local/openbmc/build-fbttn//tmp/deploy/images/fbttn/flash-fbttn
  No image meta found: ValueError('No JSON object could be decoded',)
  Signing legacy image
  The firmware does not contain a /keys subnode
  /home/pdel/local/openbmc/build-fbttn//tmp/sysroots-components/x86_64/u-boot-mkimage-native/usr/bin/mkimage -f /tmp/tmpPJvh7d -E -k /data/users/pdel/openbmc/tools/verified-boot/signing/subordinate -p 00004000 -r /tmp/tmpMkmosO
  Signing OS kernel and rootfs
  /home/pdel/local/openbmc/build-fbttn//tmp/sysroots-components/x86_64/u-boot-mkimage-native/usr/bin/mkimage -f /tmp/tmpJSxZKD -k /data/users/pdel/openbmc/tools/verified-boot/signing/subordinate -r /tmp/tmpYcxwPO
  Wrote signed firmware: /home/pdel/local/openbmc/build-fbttn//tmp/deploy/images/fbttn/flash-fbttn.signed

To allow people to self-sign new-style images, I added a `--force` option to `vboot-sign` that just passes `--force` to `fit-sign`.

  ./vboot-sign --help
  USAGE: ./vboot-sign [OPTIONS]
  OPTIONS:
  --help
      Print this message
  -k|--keys KEYS_DIR
      Set Keys directory to KEYS_DIR, else the path of this script will be used
  -b|--build BUILD_DIR
      Set the build directory to BUILD_DIR. Else the current working directory will be used
  -s|--setup
      Generate the keys in KEYS_DIR (See above for default path)
  -S|--HSM {compute|storage|network|training}
      Use FB HSM keyname ncipher/simple/obmc-<platform_type>-sub-0 key to sign
  --force
      Force signing with self-signed, non-HSM keys on new images

Test Plan:
To test this, I'm actually just going to verify that `vboot-sign` works with both Python versions and both image kinds (instead of running the individual commands manually).

  ./vboot-sign --build ~/local/openbmc/build-fbttn/ --python python2.7 --setup
  ./vboot-sign --build ~/local/openbmc/build-fbttn/ --python python2.7
  ./vboot-sign --build ~/local/openbmc/build-fbttn/ --python python3.6 --setup
  ./vboot-sign --build ~/local/openbmc/build-fbttn/ --python python3.6
  ./vboot-sign --build ~/local/openbmc/build-fby3/ --python python2.7 --setup
  ./vboot-sign --build ~/local/openbmc/build-fby3/ --python python2.7 --force
  ./vboot-sign --build ~/local/openbmc/build-fby3/ --python python3.6 --setup
  ./vboot-sign --build ~/local/openbmc/build-fby3/ --python python3.6 --force
  ~/local/openbmc/common/recipes-utils/vboot-utils/files/vboot-check ~/local/openbmc/build-fbttn/tmp/deploy/images/fbttn/flash-fbttn.signed
  ~/local/openbmc/common/recipes-utils/vboot-utils/files/vboot-check ~/local/openbmc/build-fby3/tmp/deploy/images/fby3/flash-fby3.signed

I also tried using `mypy` to see if it catches anything, but unfortunately it doesn't catch stuff like `UnicodeDecodeError`'s, so I'm not sure that it gives me any additional confidence.

  cat verify.sh
  mypy fit-cs --python-version 2.7
  mypy fit-sign --python-version 2.7
  mypy fit-signsub --python-version 2.7
  mypy fit-cs --python-version 3.6
  mypy fit-sign --python-version 3.6
  mypy fit-signsub --python-version 3.6

  ./verify.sh
  fit-cs:11: error: Skipping analyzing "jinja2": found module but no type hints or library stubs
  fit-cs:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
  Found 1 error in 1 file (checked 1 source file)
  Success: no issues found in 1 source file
  Success: no issues found in 1 source file
  fit-cs:11: error: Skipping analyzing "jinja2": found module but no type hints or library stubs
  fit-cs:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
  Found 1 error in 1 file (checked 1 source file)
  Success: no issues found in 1 source file
  Success: no issues found in 1 source file

Reviewed By: zhdaniel12

Differential Revision: D29943165

fbshipit-source-id: 8c8da7ec9d