cloudripper: enable log-util (#942)
Summary:
Enable log-util for cloudripper.

Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/942

Test Plan:
```
root@bmc-oob:~# cat /etc/issue
OpenBMC Release cloudripper-130bee6505-dirty

root@bmc-oob:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,fan1,fan2,fan3,fan4 ,fcm,psu1,psu2,scm,smb,sys} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU

```

Reviewed By: GoldenBug

Differential Revision: D25960408

fbshipit-source-id: c89d4d122d