fbgc: support snapshot-util (#1476)
Summary:
1. Support snapshot-util in Grand Canyon.

2. snapshot-util can store the zip file of SEL logs, postcode file, and error/failure reason file into the EEPROM of server. Used for manufacturing build or RMA.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1476

Test Plan:
1. Built and test pass on Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and SELs.

3. Check snapshot-util is functional.
(1) Usage
    root@bmc-oob:~# snapshot-util
    Error: invalid number of arguments
    Usage: snapshot-util [fru] --set <type> <reason_file>
           snapshot-util [fru] --set <type> "<inline reason string>"
           snapshot-util [fru] --get <type> <info_num> <dump_file>
           snapshot-util [fru] --get --all <dump_file>
           snapshot-util [fru] --clear <type> <info_num>

           [fru]: server
           <type>:
             --rma  RMA information
             --mfg  MFG failure information
           <info_num>: 1 ~ 3 for RMA information; 1 for MFG failure information

(2) Test clear
    root@bmc-oob:~# snapshot-util server --clear --mfg 1 571932
    Finished

    root@bmc-oob:~# snapshot-util server --clear --rma 1 571932
    Finished

    root@bmc-oob:~# snapshot-util server --clear --rma 2 571932
    Finished

    root@bmc-oob:~# snapshot-util server --clear --rma 3 571932
    Finished

(3) Set information to different regions
    [Create reason file for snapshot-util]
    root@bmc-oob:~# cat reason.txt
    test

    root@bmc-oob:~# snapshot-util server --set --mfg reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 431
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util server --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 429
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util server --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 430
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util server --set --rma reason.txt
    Getting logs...
    Getting POST codes...
    File Size: 429
    Storing to EEPROM...
    Finished

(4) Dump all snapshot files
    root@bmc-oob:~# snapshot-util server --get --all server
    Filename: server-rma1
    File Size: 429
    Dumping from EEPROM...
    Filename: server-rma2
    File Size: 430
    Dumping from EEPROM...
    Filename: server-rma3
    File Size: 429
    Dumping from EEPROM...
    Filename: server-mfg1
    File Size: 431
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# ls
    reason.txt   server-mfg1  server-rma1  server-rma2  server-rma3

(5) Check the snapshot files
    [Change the files extension to 'tgz' and unzip the files]
    root@bmc-oob:~# mv server-mfg1 server-mfg1.tgz
    root@bmc-oob:~# mkdir server-mfg1 && tar zxvf server-mfg1.tgz -C server-mfg1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv server-rma1 server-rma1.tgz
    root@bmc-oob:~# mkdir server-rma1 && tar zxvf server-rma1.tgz -C server-rma1
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv server-rma2 server-rma2.tgz
    root@bmc-oob:~# mkdir server-rma2 && tar zxvf server-rma2.tgz -C server-rma2
    ./log.txt
    ./postcode.txt
    ./reason.txt

    root@bmc-oob:~# mv server-rma3 server-rma3.tgz
    root@bmc-oob:~# mkdir server-rma3 && tar zxvf server-rma3.tgz -C server-rma3
    ./log.txt
    ./postcode.txt
    ./reason.txt

    [MFG failure information]
    root@bmc-oob:~# cat server-mfg1/log.txt
    2021 Feb 18 01:21:56 log-util: User cleared all logs

    root@bmc-oob:~# cat server-mfg1/postcode.txt
    00 00 00 00 AA 84 B1 B1 B0 AF AD D9 AD D9 AD 92
    A0 92 92 99 92 B4 B4 9C 9A 9D 98 97 92 92 92 92
    91 99 92 92 92 10 50 EF 96 95 94 94 94 94 94 94
    94 94 94 94 94 94 94 94 94 94 94 94 94 92 91 90
    79 70 68 9A 61 60 33 4F BF C6 CE BC CC 7E D5 7E
    B7 7E 7E B9 BB 7E CB B9 BA C9 7E B8 7E B8 B7 B9
    C7 C7 7E D6 D2 7E 7E BE BE 7E B7 B7 B7 B7 B7 B6
    B6 B6 B6 B6 B6 B6 B3 B3 B3 B3 B3 C7 C6 B2 C5 7E
    B4 B1 7E B1 C1 7E B0 B0 B8 CD 7E CF 7E AF AE AA
    A8 A9 A9 A7 A7 A7 A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50 AF 7E B1 C1 7E B0 B0 B8 CD
    7E CF 7E AF AB AA A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50

    root@bmc-oob:~# cat server-mfg1/reason.txt
    test

    [RMA 1 information]
    root@bmc-oob:~# cat server-rma1/log.txt
    2021 Feb 18 01:21:56 log-util: User cleared all logs

    root@bmc-oob:~# cat server-rma1/postcode.txt
    00 00 00 00 AA 84 B1 B1 B0 AF AD D9 AD D9 AD 92
    A0 92 92 99 92 B4 B4 9C 9A 9D 98 97 92 92 92 92
    91 99 92 92 92 10 50 EF 96 95 94 94 94 94 94 94
    94 94 94 94 94 94 94 94 94 94 94 94 94 92 91 90
    79 70 68 9A 61 60 33 4F BF C6 CE BC CC 7E D5 7E
    B7 7E 7E B9 BB 7E CB B9 BA C9 7E B8 7E B8 B7 B9
    C7 C7 7E D6 D2 7E 7E BE BE 7E B7 B7 B7 B7 B7 B6
    B6 B6 B6 B6 B6 B6 B3 B3 B3 B3 B3 C7 C6 B2 C5 7E
    B4 B1 7E B1 C1 7E B0 B0 B8 CD 7E CF 7E AF AE AA
    A8 A9 A9 A7 A7 A7 A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50 AF 7E B1 C1 7E B0 B0 B8 CD
    7E CF 7E AF AB AA A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50

    root@bmc-oob:~# cat server-rma1/reason.txt
    test

    [RMA 2 information]
    root@bmc-oob:~# cat server-rma2/log.txt
    2021 Feb 18 01:21:56 log-util: User cleared all logs

    root@bmc-oob:~# cat server-rma2/postcode.txt
    00 00 00 00 AA 84 B1 B1 B0 AF AD D9 AD D9 AD 92
    A0 92 92 99 92 B4 B4 9C 9A 9D 98 97 92 92 92 92
    91 99 92 92 92 10 50 EF 96 95 94 94 94 94 94 94
    94 94 94 94 94 94 94 94 94 94 94 94 94 92 91 90
    79 70 68 9A 61 60 33 4F BF C6 CE BC CC 7E D5 7E
    B7 7E 7E B9 BB 7E CB B9 BA C9 7E B8 7E B8 B7 B9
    C7 C7 7E D6 D2 7E 7E BE BE 7E B7 B7 B7 B7 B7 B6
    B6 B6 B6 B6 B6 B6 B3 B3 B3 B3 B3 C7 C6 B2 C5 7E
    B4 B1 7E B1 C1 7E B0 B0 B8 CD 7E CF 7E AF AE AA
    A8 A9 A9 A7 A7 A7 A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50 AF 7E B1 C1 7E B0 B0 B8 CD
    7E CF 7E AF AB AA A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50

    root@bmc-oob:~# cat server-rma2/reason.txt
    test

    [RMA 3 information]
    root@bmc-oob:~# cat server-rma3/log.txt
    2021 Feb 18 01:21:56 log-util: User cleared all logs

    root@bmc-oob:~# cat server-rma3/postcode.txt
    00 00 00 00 AA 84 B1 B1 B0 AF AD D9 AD D9 AD 92
    A0 92 92 99 92 B4 B4 9C 9A 9D 98 97 92 92 92 92
    91 99 92 92 92 10 50 EF 96 95 94 94 94 94 94 94
    94 94 94 94 94 94 94 94 94 94 94 94 94 92 91 90
    79 70 68 9A 61 60 33 4F BF C6 CE BC CC 7E D5 7E
    B7 7E 7E B9 BB 7E CB B9 BA C9 7E B8 7E B8 B7 B9
    C7 C7 7E D6 D2 7E 7E BE BE 7E B7 B7 B7 B7 B7 B6
    B6 B6 B6 B6 B6 B6 B3 B3 B3 B3 B3 C7 C6 B2 C5 7E
    B4 B1 7E B1 C1 7E B0 B0 B8 CD 7E CF 7E AF AE AA
    A8 A9 A9 A7 A7 A7 A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50 AF 7E B1 C1 7E B0 B0 B8 CD
    7E CF 7E AF AB AA A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50

    root@bmc-oob:~# cat server-rma3/reason.txt
    test

(6) Test command line reason
    root@bmc-oob:~# snapshot-util server --clear --rma 1 571932
    Finished
    root@bmc-oob:~# snapshot-util server --clear --rma 2 571932
    Finished
    root@bmc-oob:~# snapshot-util server --clear --rma 3 571932
    Finished

    root@bmc-oob:~# snapshot-util server --set --rma "rma test"
    Reason file doesn't exist, assume stdin
    Getting logs...
    Getting POST codes...
    File Size: 445
    Storing to EEPROM...
    Finished

    root@bmc-oob:~# snapshot-util server --get --rma 1 rma
    Filename: rma
    File Size: 445
    Dumping from EEPROM...
    Finished

    root@bmc-oob:~# mv rma rma.tgz
    root@bmc-oob:~# mkdir rma && tar zxvf rma.tgz -C rma
    ./log.txt
    ./postcode.txt
    ./snapshot-reason-dft

    root@bmc-oob:~# cat rma/log.txt
    2021 Feb 18 01:21:56 log-util: User cleared all logs

    root@bmc-oob:~# cat rma/postcode.txt
    00 00 00 00 AA 84 B1 B1 B0 AF AD D9 AD D9 AD 92
    A0 92 92 99 92 B4 B4 9C 9A 9D 98 97 92 92 92 92
    91 99 92 92 92 10 50 EF 96 95 94 94 94 94 94 94
    94 94 94 94 94 94 94 94 94 94 94 94 94 92 91 90
    79 70 68 9A 61 60 33 4F BF C6 CE BC CC 7E D5 7E
    B7 7E 7E B9 BB 7E CB B9 BA C9 7E B8 7E B8 B7 B9
    C7 C7 7E D6 D2 7E 7E BE BE 7E B7 B7 B7 B7 B7 B6
    B6 B6 B6 B6 B6 B6 B3 B3 B3 B3 B3 C7 C6 B2 C5 7E
    B4 B1 7E B1 C1 7E B0 B0 B8 CD 7E CF 7E AF AE AA
    A8 A9 A9 A7 A7 A7 A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50 AF 7E B1 C1 7E B0 B0 B8 CD
    7E CF 7E AF AB AA A9 A7 A3 A3 A1 31 32 11 19 06
    05 04 03 02 01 10 50

    root@bmc-oob:~# cat rma/snapshot-reason-dft
    rma test

Reviewed By: benwei13

Differential Revision: D26668716

Pulled By: zhdaniel12

fbshipit-source-id: 5170b92a2b