wedge400 cit: Fix wedge400/wedge400c restful sys and sensors endpoint (#344)
Summary:
Fix sys and sensors restful endpoint cit test cases
Pull Request resolved: https://github.com/facebookexternal/openbmc.celestica/pull/344

Test Plan:
There is some commond code issue of ntp restful api: need to fix later.
We skip to test ntp endpoint in base_rest_endpoint_test.py then all can run pass.
root@bmc-oob:~/tests2# curl -g http://localhost:8080/api/sys/ntp | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93  100    93    0     0    135      0 --:--:-- --:--:-- --:--:--   142
{
    "Resources": [],
    "Actions": [],
    "Information": {
        "reason": "No association ID's returned\n"
    }
}
root@bmc-oob:~/tests2# python
Python 3.5.3 (default, Feb 13 2020, 09:36:25)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> a=urlopen("http://localhost:8080/api/sys/ntp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
>>> a=urlopen("http://localhost:8080/api/sys/bmc")
>>> a.read()
b'{"Resources": [], "Actions": [], "Information": {"MAC Addr": "00:E0:EC:DC:A1:63", "SPI1 Vendor": "Unknown", "TPM FW version": "NA", "uptime": "243587.07", "load-5": "3.15", "Uptime": "01:22:30 up 2 days, 19:39,  load average: 3.47, 3.14, 2.93", "At-Scale-Debug Running": false, "Description": "wedge400 BMC", "load-15": "2.94", "vboot": {"status": "-1", "status_text": "Unsupported"}, "CPU Usage": "CPU:  23% usr  47% sys   0% nic  29% idle   0% io   0% irq   0% sirq", "open-fds": "718", "kernel version": "5.3.8-wedge400 https://github.com/facebookexternal/openbmc.celestica/issues/9 Mon Mar 9 03:24:51 UTC 2020", "SPI0 Vendor": "Unknown", "Memory Usage": "Mem: 151640K used, 734700K free, 12784K shrd, 156K buff, 84756K cached", "u-boot version": "2019.01", "TPM TCG version": "NA", "Reset Reason": "User Initiated Reset or WDT Reset", "OpenBMC Version": "", "load-1": "3.47"}}'
>>> quit()
root@bmc-oob:~/tests2#

root@bmc-oob:~/tests2# source /usr/local/bin/openbmc-utils.sh
root@bmc-oob:~/tests2# wedge_board_type_rev
WEDGE400_DVT2
root@bmc-oob:~/tests2#
root@bmc-oob:~/tests2# python cit_runner.py --platform wedge400 --run-test tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys
test_endpoint_api_sys (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 29.913s

OK
root@bmc-oob:~/tests2# python cit_runner.py --platform wedge400 --run-test tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors
test_endpoint_api_sys_sensors (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 23.785s

OK

--------------------- Wedge400C ---------------------
root@bmc-oob:~/tests2# source /usr/local/bin/openbmc-utils.sh
root@bmc-oob:~/tests2# wedge_board_type_rev
WEDGE400-C_EVT2
root@bmc-oob:~/tests2# python cit_runner.py --platform wedge400 --run-test tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys
test_endpoint_api_sys (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 30.511s

OK
root@bmc-oob:~/tests2# python cit_runner.py --platform wedge400 --run-test tests.wedge400.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors
test_endpoint_api_sys_sensors (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 25.315s

OK

Reviewed By: joancaneus

Differential Revision: D20471754

fbshipit-source-id: 23e0735ec0