fby3: plat-utils: fix error messages when a system is run in rc5.d (#1055)
Summary:
-setup-dev.sh: ltc4282 is not supported to read 0x99 and i2cget will output the error messages.
Redirect stderr to /dev/null.

-setup-gpio.sh: Fix a typo. GPIOAB2-RST_BMC_WDRST1_R and GPIOAB3-RST_BMC_WDRST2_R should be exported instead of calling gpio_set.

-setup-ipmbd.sh: A 12V control register of CPLD is set to 1 by default even if a slot is empty.
BMC fails to initialize the slot when the slot is plugged since it runs `power-util slotX 12V-on` and the 12V control register is checked.
power-util will consider the slot is powered on and stop initializaing the slot.
Therefore, setup the init value of the 12V control register.
Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1055

Test Plan:
-built code(pass)
-no error messages were found from setup-gpio.sh and setup-dev.sh(pass)
-switch slots and make sure SB BIC can be reached(pass)
-check 1st and 2nd sources of HSC can be identified(pass)

root@bmc-oob:~# i2cget -y 12 0xf 0x9
0x01
root@bmc-oob:~# i2cget -y 12 0xf 0xa
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xb
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xc
0x01
root@bmc-oob:~# bic-util slot1 0x18 0x01
25 80 11 13 02 BF 4C 1C 00 39 30 00 00 00 00
root@bmc-oob:~# i2cget -y 12 0xf 0x9
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xa
0x01
root@bmc-oob:~# i2cget -y 12 0xf 0xb
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xc
0x01
root@bmc-oob:~# bic-util slot2 0x18 0x01
25 80 11 13 02 BF 4C 1C 00 39 30 00 00 00 00
root@bmc-oob:~# i2cget -y 12 0xf 0x9
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xa
0x00
root@bmc-oob:~# i2cget -y 12 0xf 0xb
0x01
root@bmc-oob:~# i2cget -y 12 0xf 0xc
0x01
root@bmc-oob:~# bic-util slot3 0x18 0x01
25 80 11 13 02 BF 4C 1C 00 39 30 00 00 00 00

Before:
Set up GPIO pins.....failed to open gpio (shadow=RST_BMC_WDRST1_R): No such file or directory
failed to open gpio (shadow=RST_BMC_WDRST2_R): No such file or directory
[   39.685874] i2c i2c-8: new_device: Instantiated device tmp421 at 0x1f
[   39.741372] at24 8-0050: 4096 byte 24c32 EEPROM, writable, 1 bytes/write
[   39.755065] i2c i2c-8: new_device: Instantiated device 24c32 at 0x50
Setup devs for fby3...[   40.025906] lm75 12-004e: hwmon3: sensor 'lm75'
[   40.035263] i2c i2c-12: new_device: Instantiated device lm75 at 0x4e
[   40.063994] lm75 12-004f: hwmon4: sensor 'lm75'
[   40.073347] i2c i2c-12: new_device: Instantiated device lm75 at 0x4f
[   40.102001] at24 11-0051: 16384 byte 24c128 EEPROM, writable, 1 bytes/write
[   40.116204] i2c i2c-11: new_device: Instantiated device 24c128 at 0x51
[   40.145448] at24 11-0054: 16384 byte 24c128 EEPROM, writable, 1 bytes/write
[   40.159678] i2c i2c-11: new_device: Instantiated device 24c128 at 0x54
Error: Length invalid
Usage: i2cget [-f] [-y] I2CBUS CHIP-ADDRESS [DATA-ADDRESS [MODE]]
  I2CBUS is an integer or an I2C bus[   40.241035] i2c i2c-11: new_device: Instantiated device ltc4282 at 0x44
 name
  ADDRESS is an integer (0x03 - 0x77)
  MODE is one of:
    b (read byte data, default)
    w (read word data)
    c (write byte/read byte)
    i (read I2C block data)
    Append p for SMBus PEC
Done.

After:
Set up GPIO pins.....[   40.798610] i2c i2c-8: new_device: Instantiated device tmp421 at 0x1f
[   40.855778] at24 8-0050: 4096 byte 24c32 EEPROM, writable, 1 bytes/write
[   40.869462] i2c i2c-8: new_device: Instantiated device 24c32 at 0x50
Setup devs for fby3...[   41.147451] lm75 12-004e: hwmon3: sensor 'lm75'
[   41.156813] i2c i2c-12: new_device: Instantiated device lm75 at 0x4e
[   41.185415] lm75 12-004f: hwmon4: sensor 'lm75'
[   41.194769] i2c i2c-12: new_device: Instantiated device lm75 at 0x4f
[   41.223690] at24 11-0051: 16384 byte 24c128 EEPROM, writable, 1 bytes/write
[   41.237902] i2c i2c-11: new_device: Instantiated device 24c128 at 0x51
[   41.267042] at24 11-0054: 16384 byte 24c128 EEPROM, writable, 1 bytes/write
[   41.281246] i2c i2c-11: new_device: Instantiated device 24c128 at 0x54
[   41.360756] i2c i2c-11: new_device: Instantiated device ltc4282 at 0x44
Done.

root@bmc-oob:~# cat /var/log/messages | grep -i medusa
 2020 May 14 21:59:52 bmc-oob. user.warning fby3-b747881-dirty: sensord: read_medusa_val() Use 'ltc4282-i2c-11-44', flag:1
root@bmc-oob:~# sensor-util bmc | grep -i medusa
BMC_SENSOR_MEDUSA_VOUT       (0xF6) :   12.51 Volts | (ok)
BMC_SENSOR_MEDUSA_VIN        (0xFD) :   12.51 Volts | (ok)
BMC_SENSOR_MEDUSA_CURR       (0xD0) :    8.83 Amps  | (ok)
BMC_SENSOR_MEDUSA_PWR        (0xD1) :  109.89 Watts | (ok)

root@bmc-oob:~# cat /var/log/messages | grep Use
 2020 May 14 22:15:41 bmc-oob. user.warning fby3-b747881-dirty: sensord: read_medusa_val() Use 'mp5920-i2c-11-44', flag:0
root@bmc-oob:~# sensor-util bmc | grep -i medusa
BMC_SENSOR_MEDUSA_VOUT       (0xF6) :   12.43 Volts | (ok)
BMC_SENSOR_MEDUSA_VIN        (0xFD) :   12.42 Volts | (ok)
BMC_SENSOR_MEDUSA_CURR       (0xD0) :   14.10 Amps  | (ok)
BMC_SENSOR_MEDUSA_PWR        (0xD1) :  166.94 Watts | (ok)

Reviewed By: williamspatrick

Differential Revision: D21595531

Pulled By: benwei13

fbshipit-source-id: 45072580f5