harma: pldm-update: delete the software ID after the update is complete
Summary:
1. Delete the software ID after the update is complete to allow the UpdateManager to delete the previously updated image and enable it to trigger again when updating the same image repeatedly.
2. Abort the update process if an update is already in progress.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4472

Test Plan:
1. Build passed and update BMC on harma.
2. Update the MMC repeatedly.

Before:
```
root@bmc:~# pldm-update ag /tmp/pldm_ob-minerva-ag-2024.43.E0_test_event.bin
pldmd.service : xyz.openbmc_project.PLDM
pldm_update: /tmp/pldm_ob-minerva-ag-2024.43.E0_test_event.bin
softwareId: 142344108
Filesystem error: filesystem error: cannot copy: File exists [/tmp/pldm_ob-minerva-ag-2024.43.E0_test_event.bin] [/tmp/pldm_images/pldm_ob-minerva-ag-2024.43.E0_test_event.bin]
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Error: sd_bus_call: org.freedesktop.DBus.Error.UnknownObject: Unknown object '/xyz/openbmc_project/software/142344108'.
Time out : pldmd.service did not process image.
```

After
```
root@bmc:~# pldm-update ag /tmp/pldm_ob-minerva-ag-2024.43.E0_test_event.bin
pldmd.service : xyz.openbmc_project.PLDM
pldm_update: /tmp/pldm_ob-minerva-ag-2024.43.E0_test_event (1).bin
softwareId: 142344108
Current progress: 100/100 (31s)
Update of software ID 142344108: succeeded.
```

If the update is already in progress and perform the update process:
```
root@bmc:~# pldm-update ag /tmp/pldm_ob-minerva-ag-2024.43.E0_test_event.bin
pldmd.service : xyz.openbmc_project.PLDM
Update aborted: The same process is still ongoing.
```

Reviewed By: amithash

Differential Revision: D64956368

fbshipit-source-id: b63315a1210eba4922d654e23c127395abf0390a