kernel_fitimage: Remove KERNEL_IMAGETYPE from DTB_PATH
Summary:
The build system no longer builds a KERNEL_IMAGETYPE-DTB
file, hence this now causes an error like the following:

------------
FATAL ERROR: Couldn't open
"deploy/images/cmm/zImage-aspeed-bmc-facebook-cmm.dtb":
No such file or directory

mkimage: Can't open
tmp/deploy/images/cmm/fit-cmm-20190707051202.itb.tmp:
No such file or directory

ERROR: Function failed: do_image_cpio
-------------

Remove KERNEL_IMAGETYPE from the DTB_PATH variable so
it finds the correct device tree blob and allows the
cpio_image to be built correctly.

Signed-off-by: Alejandro Enedino Hernandez Samaniego <aehs29@gmail.com>

Test Plan: Build fbtp on both 4.1 and 5.0 and ensure it builds and boots fine.

Reviewed By: tomrepo

Differential Revision: D17635782

fbshipit-source-id: 7ee075ff15