netlakemtp: Fix event SEL for server power reset result (#2319)
Summary:
- When host power status is off, server power reset command should be blocked
 - Event SEL for server power reset successfully shouldn't be sent in this case

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/2319

Test Plan:
- Do server power reset when server power status off
root@bmc-oob:~# power-util server reset
Power reset fru 1...
Current Power is OFF, therefore cannot reset.
Power reset fail for fru 1
ERROR: power-util fru[1] [POWER_RESET] failed
root@bmc-oob:~# log-util all --print
2018 Mar 09 19:55:37 log-util: User cleared all logs

Reviewed By: GoldenBug

Differential Revision: D38921311

Pulled By: mikechoifb

fbshipit-source-id: 4ad350d4c471a823b27e8ad0ca54c3ac59b4a31c