fby3, ast1030 vernal falls: add retry for bic-recovery update (#3107)
Summary:
The IO-expander will enter an abnormal state when i2c master sent address without W/R data. (ex. BMC use i2cdetect)
Only the first i2c W/R command after i2cdetect will fail.
Add retry in update procedure in order to handle this case.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3107

Test Plan:
build and test on ast1030 VF pass

root@bmc-oob:/tmp# i2cdetect -y 4
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- 0f
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- 49 -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
root@bmc-oob:/tmp# i2cget -y 4 0x49 0x01
Error: Read failed
root@bmc-oob:/tmp# i2cget -y 4 0x49 0x01
0x04

before
 ---
root@bmc-oob:/tmp# i2cdetect -y 4
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- 0f
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- 49 -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
root@bmc-oob:/tmp# fw-util slot1 --update   1ou_bic_recovery  /tmp/oby3-vf-2022.30.01.bin
Error: Write failed
1ou_bic_recovery: bic_recovery_init process failed
Upgrade of slot1 : 1ou_bic_recovery failed

after
 ---
root@bmc-oob:/tmp# i2cdetect -y 4
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- 0f
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- 49 -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
root@bmc-oob:/tmp#   ./fw-util slot1  --update  1ou_bic_recovery /tmp/oby3-vf-2022.30.01.bin
Error: Write failed
Start transmission over UART
Transmission finish
slot_id: 1, comp: 7, intf: 0, img: /tmp/oby3-vf-2022.30.01.bin, force: 1
file size = 174436 bytes, slot = 1, intf = 0x5
updating fw on slot 1:
updated bic: 100 %
Elapsed time:  14   sec.

Upgrade of slot1 : 1ou_bic_recovery succeeded

Signed-off-by: Ken Chen <j220584470k@gmail.com>

Reviewed By: garnermic

Differential Revision: D38518185

fbshipit-source-id: 551260c7208cc95f14e252beaba92c3bb5376f1a