Prevent multiple instances of oob-eeprom-util.sh running at the same time (#152)
Summary:
Running multiple instances of the oob-eeprom-util.sh script at the same
time can potentially cause issues. In another product, this has been shown
to corrupt the OOB switch eeprom.

Prevent multiple instances by using flock, specifying a file descriptor
which is created by opening the script itself for read. This file descriptor
is guaranteed to be closed when the script ends for any reason.

Testing performed:
1. Ran oob-eeprom-util.sh dump. While this command was running, in another window,
tried to run oob-eeprom.util.sh dump. The following is printed:
ERROR: /usr/local/bin/oob-eeprom-util.sh already running

2. Ran oob-eeprom-util.sh dump. While this command was running, killed it with
a KILL(9) signal. Then ran the dump command again, ensuring that it is able
to run.

3. Ran the oob_eeprom CIT test:
python3 /usr/local/bin/tests2/cit_runner.py --platform elbert -r tests.elbert.test_oob_eeprom

Pull Request resolved: https://github.com/facebookexternal/openbmc.arista/pull/152

Reviewed By: tao-ren, binhuang00

Differential Revision: D26701197

fbshipit-source-id: 98bf90e1d0