fbep: Migrate mac-util to C++ (#1904)
Summary:
1. Migrate mac-util to C++
2. Change the order of setup-usbnet to S10 in RC5

Pull Request resolved: https://github.com/facebookexternal/openbmc.quanta/pull/1904

Test Plan:
Build pass and test on fbep

Setup dhclient for IPv6... done.
reloading rsyslogd ... done
Starting OpenBSD Secure Shell server: sshd
done.
[   32.070554] using random self ethernet address
[   32.079570] using random host ethernet address
[   32.088549] using host ethernet address: 02:00:00:00:00:02
[   32.088561] using self ethernet address: b4:a9:fc:ad:9c:9d
[   32.101112] usb0: HOST MAC 02:00:00:00:00:02
[   32.120978] usb0: MAC b4:a9:fc:ad:9c:9d
[   32.128739] using random self ethernet address
[   32.137731] using random host ethernet address
[   32.157940] g_ether gadget: Ethernet Gadget, version: Memorial Day 2008
[   32.171280] g_ether gadget: g_ether ready
[   32.795216] g_ether gadget: full-speed config https://github.com/facebookexternal/openbmc.quanta/issues/1: CDC Ethernet (ECM)
[   32.811948] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready

root@bmc-oob:~# mac-util
ERROR: RequiredError: At least 1 option from [--set,--get] is required
MAC Utility
[At least 1 of the following options are required]
Usage: mac-util [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --set TEXT                  Set MAC address
                              Example: 02:00:00:00:00:01
  --get                       Get MAC address

root@bmc-oob:~# mac-util --get
b4:a9:fc:ad:9c:9d

root@bmc-oob:~# mac-util --set fb:fb:fb:fb:fb:fb
Set MAC address to fb:fb:fb:fb:fb:fb
root@bmc-oob:~# mac-util --get
fb:fb:fb:fb:fb:fb

Reviewed By: benwei13

Differential Revision: D23427163

fbshipit-source-id: 5b7c7b090a