fbtp: check the type of vr f/w code when do vr update (#685)
Summary:
Summary
-Use board SKU to check a vr f/w code and see if the code can be used in this MB or not

TestPlan
-Build code(pass)
-Test in reality(pass)

-The log of SS/IFX MB
root@b1101:~ scp 192.168.88.1:/home/tony/OpenBMC_VR/MP_SS_3001_Fairchild.bin .
The authenticity of host '192.168.88.1 (192.168.88.1)' can't be established.
ECDSA key fingerprint is SHA256:jHocPK0cdtKOJTDQYRETaCljowovqf8NAZTRgv9u2gg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.88.1' (ECDSA) to the list of known hosts.
root@192.168.88.1's password:
Permission denied, please try again.
root@192.168.88.1's password:
MP_SS_3001_Fairchild.bin                                                                                                           100%   18KB  18.0KB/s   00:00
root@b1101:~ scp 192.168.88.1:/home/tony/OpenBMC_VR/MP_SS_3001_IFX.bin .
root@192.168.88.1's password:
MP_SS_3001_IFX.bin                                                                                                                 100%   18KB  18.0KB/s   00:00
root@b1101:~ cat /etc/issue
OpenBMC Release fbtp-2c96682

root@b1101:~ fw-util mb --update --vr MP_SS_3001_Fairchild.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@b1101:~ fw-util mb --update --vr MP_SS_3001_IFX.bin
Data Size: 18423 bytes!
Check Data...Done
Writing Data: 18360/18360 (100.00%)
Update VR Success!
Upgrade of mb : vr succeeded
root@b1101:~ fw-util all --version
BMC Version: fbtp-2c96682
Fan Speed Controller Version: fbtp-v1.1-20180129
TPM Version: 133.33
BIOS Version: TPP08
CPLD Version: 00000A01, CPLD DeviceID: 012BC043
ME Version: SPS_04.00.04.294.0
VR_PCH_[PVNN, PV1V05] Version: 01083000, Checksum: 1803FA9F, DeviceID: 0401
VR_CPU0_[VCCIN, VSA] Version: 01003000, Checksum: 4A1F49F9, DeviceID: 0415
VR_CPU0_VCCIO Version: 01063000, Checksum: 344D0C23, DeviceID: 0401
VR_CPU0_VDDQ_ABC Version: 01023000, Checksum: F996A21B, DeviceID: 0809
VR_CPU0_VDDQ_DEF Version: 01033000, Checksum: 8CFCF5A6, DeviceID: 0809
VR_CPU1_[VCCIN, VSA] Version: 01013000, Checksum: EFEAC451, DeviceID: 0415
VR_CPU1_VCCIO Version: 01073000, Checksum: 91B8818B, DeviceID: 0401
VR_CPU1_VDDQ_GHJ Version: 01043000, Checksum: 9DD8FD04, DeviceID: 0809
VR_CPU1_VDDQ_KLM Version: 01053000, Checksum: 0B877AB7, DeviceID: 0809
Broadcom NIC firmware version: 20.6.4.3
root@b1101:~ ^C
root@b1101:~ power-util sled-cycle
Write failed: Broken pipe
root@wangPC:/home/tony ssh 192.168.88.142
root@192.168.88.142's password:
root@b1101:~ fw-util all --version
BMC Version: fbtp-2c96682
Fan Speed Controller Version: fbtp-v1.1-20180129
TPM Version: 133.33
BIOS Version: TPP08
CPLD Version: 00000A01, CPLD DeviceID: 012BC043
ME Version: SPS_04.00.04.294.0
VR_PCH_[PVNN, PV1V05] Version: 01083001, Checksum: 3D2733C6, DeviceID: 0401
VR_CPU0_[VCCIN, VSA] Version: 01003001, Checksum: 813CEF44, DeviceID: 0415
VR_CPU0_VCCIO Version: 01063001, Checksum: 1169C57A, DeviceID: 0401
VR_CPU0_VDDQ_ABC Version: 01023001, Checksum: DCB26B42, DeviceID: 0809
VR_CPU0_VDDQ_DEF Version: 01033001, Checksum: NA, DeviceID: 0809
VR_CPU1_[VCCIN, VSA] Version: 01013001, Checksum: 0A0E3686, DeviceID: 0415
VR_CPU1_VCCIO Version: 01073001, Checksum: B49C48D2, DeviceID: 0401
VR_CPU1_VDDQ_GHJ Version: 01043001, Checksum: B8FC345D, DeviceID: 0809
VR_CPU1_VDDQ_KLM Version: 01053001, Checksum: 2EA3B3EE, DeviceID: 0809
Broadcom NIC firmware version: 20.6.4.3

root@b1101:~ fw-util mb --update --vr MP_SS_3001_IFX_checksum_err.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@b1101:~ fw-util mb --update --vr MP_SS_3001_Fairchild_checksum_err.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@b1101:~ cat /var/log/messages | grep fw-util
 2018 Jul 29 17:57:14 b1101.lab.lp user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 CRC not match !
 2018 Jul 29 17:57:14 b1101.lab.lp user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 CRC: e 15 e6 21!
 2018 Jul 29 17:57:14 b1101.lab.lp user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 Expected CRC: 81 3c ef 44!
 2018 Jul 29 17:57:22 b1101.lab.lp user.warning fbtp-2c96682: fw-util: [check_vr_fw_code_match_MB] VR fw code does not match MB!
 2018 Jul 29 17:57:22 b1101.lab.lp user.warning fbtp-2c96682: fw-util: [vr_fw_update_binary] Please Check vr fw code!

-The log of SS/Fairchaild MB
root@bmc-oob:/tmp scp 192.168.88.1:/home/tony/OpenBMC_VR/MP_SS_3001_Fairchild.bin .
The authenticity of host '192.168.88.1 (192.168.88.1)' can't be established.
ECDSA key fingerprint is SHA256:jHocPK0cdtKOJTDQYRETaCljowovqf8NAZTRgv9u2gg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.88.1' (ECDSA) to the list of known hosts.
root@192.168.88.1's password:
MP_SS_3001_Fairchild.bin                                                                                                           100%   18KB  18.0KB/s   00:00
root@bmc-oob:/tmp scp 192.168.88.1:/home/tony/OpenBMC_VR/MP_SS_3001_IFX.bin .
root@192.168.88.1's password:
MP_SS_3001_IFX.bin                                                                                                                 100%   18KB  18.0KB/s   00:00
root@bmc-oob:/tmp fw-util mb --updadte --vr MP_SS_3001_
MP_SS_3001_Fairchild.bin  MP_SS_3001_IFX.bin
root@bmc-oob:/tmp fw-util mb --update --vr MP_SS_3001_Fairchild.bin
Data Size: 18423 bytes!
Check Data...Done
Writing Data: 18360/18360 (100.00%)
Update VR Success!
Upgrade of mb : vr succeeded
root@bmc-oob:/tmp fw-util mb --update --vr MP_SS_3001_
MP_SS_3001_Fairchild.bin  MP_SS_3001_IFX.bin
root@bmc-oob:/tmp fw-util mb --update --vr MP_SS_3001_IFX.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@bmc-oob:/tmp ^C
root@bmc-oob:/tmp
root@bmc-oob:/tmp fw-util all --version
BMC Version: fbtp-2c96682
Fan Speed Controller Version: fbtp-v1.1-20180129
TPM Version: 133.32
BIOS Version: TPM03
CPLD Version: 00000A01, CPLD DeviceID: 012BC043
ME Version: SPS_04.00.04.340.0
VR_PCH_[PVNN, PV1V05] Version: 01083002, Checksum: 524A682D, DeviceID: 0401
VR_CPU0_[VCCIN, VSA] Version: 01003002, Checksum: 9FE58E42, DeviceID: 0415
VR_CPU0_VCCIO Version: 01063002, Checksum: 7E049E91, DeviceID: 0401
VR_CPU0_VDDQ_ABC Version: 01023002, Checksum: B3DF30A9, DeviceID: 0809
VR_CPU0_VDDQ_DEF Version: 01033002, Checksum: C6B56714, DeviceID: 0809
VR_CPU1_[VCCIN, VSA] Version: 01013002, Checksum: E80D71D7, DeviceID: 0415
VR_CPU1_VCCIO Version: 01073002, Checksum: DBF11339, DeviceID: 0401
VR_CPU1_VDDQ_GHJ Version: 01043002, Checksum: D7916FB6, DeviceID: 0809
VR_CPU1_VDDQ_KLM Version: 01053002, Checksum: 41CEE805, DeviceID: 0809
Broadcom NIC firmware version: 20.6.1.7
root@bmc-oob:/tmp power-util sled-cycle
Write failed: Broken pipe
root@wangPC:/home/tony ssh 192.168.88.159
root@192.168.88.159's password:
root@bmc-oob:~ power-util mb status
Power status for fru 1 : ON
root@bmc-oob:~ fw-util all --version
BMC Version: fbtp-2c96682
Fan Speed Controller Version: fbtp-v1.1-20180129
TPM Version: 133.32
BIOS Version: TPM03
CPLD Version: 00000A01, CPLD DeviceID: 012BC043
ME Version: SPS_04.00.04.340.0
VR_PCH_[PVNN, PV1V05] Version: 03083001, Checksum: 566191AB, DeviceID: 0401
VR_CPU0_[VCCIN, VSA] Version: 03003001, Checksum: 9BCE77C4, DeviceID: 0415
VR_CPU0_VCCIO Version: 03063001, Checksum: 7A2F6717, DeviceID: 0401
VR_CPU0_VDDQ_ABC Version: 03023001, Checksum: B7F4C92F, DeviceID: 0809
VR_CPU0_VDDQ_DEF Version: 03033001, Checksum: C29E9E92, DeviceID: 0809
VR_CPU1_[VCCIN, VSA] Version: 03013001, Checksum: EC268851, DeviceID: 0415
VR_CPU1_VCCIO Version: 03073001, Checksum: DFDAEABF, DeviceID: 0401
VR_CPU1_VDDQ_GHJ Version: 03043001, Checksum: D3BA9630, DeviceID: 0809
VR_CPU1_VDDQ_KLM Version: 03053001, Checksum: 45E51183, DeviceID: 0809
Broadcom NIC firmware version: 20.6.1.7

root@bmc-oob:~ fw-util mb --update --vr MP_SS_3001_IFX_checksum_err.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@bmc-oob:~ fw-util mb --update --vr MP_SS_3001_Fairchild_checksum_err.bin
Data Size: 18423 bytes!
Check Data...Error Occur at updating VR FW!
ERROR: VR Firmware update failed!
Upgrade of mb : vr failed
root@bmc-oob:~ cat /var/log/messages | grep fw-util
 2018 Jul 29 18:29:09 bmc-oob user.warning fbtp-2c96682: fw-util: [check_vr_fw_code_match_MB] VR fw code does not match MB!
 2018 Jul 29 18:29:09 bmc-oob user.warning fbtp-2c96682: fw-util: [vr_fw_update_binary] Please Check vr fw code!
 2018 Jul 29 18:29:47 bmc-oob user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 CRC not match !
 2018 Jul 29 18:29:47 bmc-oob user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 CRC: 2b 98 c 47!
 2018 Jul 29 18:29:47 bmc-oob user.warning fbtp-2c96682: fw-util: [check_integrity_of_vr_data] Slave: 90 Expected CRC: 9b ce 77 c4!
Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/685

Reviewed By: benwei13

Differential Revision: D9065177

Pulled By: amithash

fbshipit-source-id: f46e41643