libvr: mp2856: tps53688: Revise store remaining write on eeprom (#3584)
Summary:
Add read/write remaining write at MB eeprom for mp2856 and revise remaining write for tps53688, we do not want everything in libpal.

- move tps remaining_rw funtion to libvr from libpal,only keep platform related eeprom set/get functions at libbic, change to set function pointer to libvr instead of weak ref in libpal.
- remove non-common vr struct member 'slot_id'
- make platform TI remaining_rw related code also use on MPS.
- support read/write remaining_rw on MP2856.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3584

Test Plan:
Build and Test OK on Halfdome BOM3(MP2856) and BOM4(TPS53685)

Halfdome BOM3(MP2856) :
```
root@bmc-oob:~# fw-util slot1 --version vr
VDDCR_CPU0/VDDCR_SOC Version: MPS D1 (https://github.com/facebookexternal/openbmc.wiwynn/commit/0346413342c08038bdf032f9e1436526813b5d11)C3B9F2, Remaining Writes: 1000
VDDCR_CPU0/VDDCR_SOC Version after activation: MPS D1 (https://github.com/facebookexternal/openbmc.wiwynn/commit/0346413342c08038bdf032f9e1436526813b5d11)C3B9F2, Remaining Writes: 1000
VDDCR_CPU1/VDDIO Version: MPS 44346BD5 (https://github.com/facebookexternal/openbmc.wiwynn/commit/abea4bf7bf4164b69571fb220231a134115786f5), Remaining Writes: 992
VDDCR_CPU1/VDDIO Version after activation: MPS 44346BD5 (https://github.com/facebookexternal/openbmc.wiwynn/commit/abea4bf7bf4164b69571fb220231a134115786f5), Remaining Writes: 992
VDD11_S3 Version: MPS AE8F6E52, Remaining Writes: 3
VDD11_S3 Version after activation: MPS AE8F6E52, Remaining Writes: 3
```
Block update when remaining writes below threshold,only allow update by force update:
```
root@bmc-oob:~# fw-util slot1 --update vr_vdd11s3 /tmp/MP2856GUT-0023-rev2_4Bh_VDD11_S3_E91B_6E52_Jerry_1222y22.txt
Update VR: VDD11_S3
Remaining writes: 3
WARNING: the remaining writes is below the threshold value 3!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of slot1 : vr_vdd11s3 failed

root@bmc-oob:~# fw-util slot1 --force --update vr_vdd11s3 /tmp/MP2856GUT-0023-rev2_4Bh_VDD11_S3_E91B_6E52_Jerry_1222y22.txt
Update VR: VDD11_S3
Remaining writes: 3
updated: 100 %
Force upgrade of slot1 : vr_vdd11s3 succeeded

root@bmc-oob:~# power-util slot3 12V-cycle

root@bmc-oob:~# fw-util slot1 --version vr
VDDCR_CPU0/VDDCR_SOC Version: MPS D1 (https://github.com/facebookexternal/openbmc.wiwynn/commit/0346413342c08038bdf032f9e1436526813b5d11)C3B9F2, Remaining Writes: 1000
VDDCR_CPU0/VDDCR_SOC Version after activation: MPS D1 (https://github.com/facebookexternal/openbmc.wiwynn/commit/0346413342c08038bdf032f9e1436526813b5d11)C3B9F2, Remaining Writes: 1000
VDDCR_CPU1/VDDIO Version: MPS 44346BD5 (https://github.com/facebookexternal/openbmc.wiwynn/commit/abea4bf7bf4164b69571fb220231a134115786f5), Remaining Writes: 992
VDDCR_CPU1/VDDIO Version after activation: MPS 44346BD5 (https://github.com/facebookexternal/openbmc.wiwynn/commit/abea4bf7bf4164b69571fb220231a134115786f5), Remaining Writes: 992
VDD11_S3 Version: MPS E91B6E52, Remaining Writes: 2
VDD11_S3 Version after activation: MPS E91B6E52, Remaining Writes: 2

```
BOM4(TPS53685):
```
root@bmc-oob:~# fw-util slot3 --version vr
VDDCR_CPU0/VDDCR_SOC Version: Texas Instruments A9F7, Remaining Writes: 999
VDDCR_CPU0/VDDCR_SOC Version after activation: Texas Instruments A9F7, Remaining Writes: 999
VDDCR_CPU1/VDDIO Version: Texas Instruments 6776, Remaining Writes: 1000
VDDCR_CPU1/VDDIO Version after activation: Texas Instruments 6776, Remaining Writes: 1000
VDD11_S3 Version: Texas Instruments 996F, Remaining Writes: 3
VDD11_S3 Version after activation: Texas Instruments 996F, Remaining Writes: 3

root@bmc-oob:~# fw-util slot3 --update vr_vddcrcpu0 /tmp/TPS53685_256.0_Address_69_SMBusDataFlashScript_CPU0_SOC.csv
Update VR: VDDCR_CPU0/VDDCR_SOC
File CRC : D9 (https://github.com/facebookexternal/openbmc.wiwynn/commit/308dd1e1af723daaecf745231153bbc08eb4a89d)B1
updated: 100 %
Upgrade of slot3 : vr_vddcrcpu0 succeeded

root@bmc-oob:~# fw-util slot3 --update vr_vdd11s3 /tmp/TPS53685_256.0_Address_71_SMBusDataFlashScript_VDD11.csv Update VR: VDD11_S3
File CRC : 59B3
WARNING: the remaining writes is below the threshold value 3!
Please use "--force" option to try again.
ERROR: VR Firmware update failed!
Upgrade of slot3 : vr_vdd11s3 failed

root@bmc-oob:~# fw-util slot3 --force --update vr_vdd11s3 /tmp/TPS53685_256.0_Address_71_SMBusDataFlashScript_VDD11.csv Update VR: VDD11_S3
File CRC : 59B3
updated: 100 %
Force upgrade of slot3 : vr_vdd11s3 succeeded

root@bmc-oob:~# power-util slot3 12V-cycle

root@bmc-oob:~# fw-util slot3 --version vr
VDDCR_CPU0/VDDCR_SOC Version: Texas Instruments D9 (https://github.com/facebookexternal/openbmc.wiwynn/commit/308dd1e1af723daaecf745231153bbc08eb4a89d)B1, Remaining Writes: 998
VDDCR_CPU0/VDDCR_SOC Version after activation: Texas Instruments D9 (https://github.com/facebookexternal/openbmc.wiwynn/commit/308dd1e1af723daaecf745231153bbc08eb4a89d)B1, Remaining Writes: 998
VDDCR_CPU1/VDDIO Version: Texas Instruments 6776, Remaining Writes: 1000
VDDCR_CPU1/VDDIO Version after activation: Texas Instruments 6776, Remaining Writes: 1000
VDD11_S3 Version: Texas Instruments 59B3, Remaining Writes: 2
VDD11_S3 Version after activation: Texas Instruments 59B3, Remaining Writes: 2
```

Reviewed By: garnermic

Differential Revision: D43166684

fbshipit-source-id: e9fa13eb212ee7694d248288c0757c1dfd261722