fix error handling in ntp rest endoint test
Summary: fix UnboundLocalError: local variable 'handle' referenced before assignment

Test Plan:
## Before the fix:
```
ERROR: test_endpoint_api_sys (tests.minipack.test_rest_endpoint.RestEndpointTest) (item='ntp')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 88, in verify_endpoint_resource
    handle = urlopen(cmd)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 91, in verify_endpoint_resource
    self.assertIn(handle.getcode(), [200, 404])
UnboundLocalError: local variable 'handle' referenced before assignment
```

## After the fix:
 on this oob ntp endpoint is not yet deployed, test crashed before the fix
## PROOF:
```
root@fboss96703260-oob:/usr/local/bin/tests2# curl http://localhost:8080/api/sys/ntp
404: Not Found
```

## FIX:

(manually append ntp endpoint to cause 404 during test run, done on the oob to demonstrate fix):
```
    def verify_endpoint_resource(self, endpointname, resources):
        """
        Verify if the resources exposed from REST endpoint are accessible
        """
        resources.append("ntp") # Local change to enable testing the ntp endpoint
        for item in resources:
            with self.subTest(item=item):
                new_endpoint = endpointname + "/" + item
                cmd = BaseRestEndpointTest.CURL_CMD6.format(new_endpoint)
                try:
                    handle = urlopen(cmd)
                except HTTPError as err:
                    if item == "ntp":
                        self.assertIn(err.code, [200, 404])
                        return
                    else:
                        raise (err)
                self.assertIn(handle.getcode(), [200, 202])

```
## Test PASSES
```
root@fboss96703260-oob:/usr/local/bin/tests2# python cit_runner.py  --platform=wedge100 --run-test tests.wedge100.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys
test_endpoint_api_sys (tests.wedge100.test_rest_endpoint.RestEndpointTest) ...
ok

----------------------------------------------------------------------
Ran 1 test in 10.165s

OK
```

Differential Revision: D20695233

fbshipit-source-id: 4f2c1d5980