fbgc: fix error while loading shared libraries libnvme-mi.so (#1516)
Summary:
Fix loading shared libraries problem when using command at BMC console.

1. Built and test pass on Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and BMC SELs.

3. Check command can execute successful.
(1) Before applying this patch
- sensor-util
root@bmc-oob:~# sensor-util e1s_iocm
sensor-util: error while loading shared libraries: /data/sara/openbmc.wiwynn/build/tmp/work/armv7at2hf-vfp-fb-linux-gnueabi/libpal/0.2-r1/recipe-sysroot/usr/lib/libnvme-mi.so: cannot open shared object file: No such file or directory

- fw-util
root@bmc-oob:~# fw-util
fw-util: error while loading shared libraries: /data/sara/openbmc.wiwynn/build/tmp/work/armv7at2hf-vfp-fb-linux-gnueabi/libpal/0.2-r1/recipe-sysroot/usr/lib/libnvme-mi.so: cannot open shared object file: No such file or directory

- power-util
root@bmc-oob:~# power-util
power-util: error while loading shared libraries: /data/sara/openbmc.wiwynn/build/tmp/work/armv7at2hf-vfp-fb-linux-gnueabi/libpal/0.2-r1/recipe-sysroot/usr/lib/libnvme-mi.so: cannot open shared object file: No such file or directory

- log-util
root@bmc-oob:~# log-util
log-util: error while loading shared libraries: /data/sara/openbmc.wiwynn/build/tmp/work/armv7at2hf-vfp-fb-linux-gnueabi/libpal/0.2-r1/recipe-sysroot/usr/lib/libnvme-mi.so: cannot open shared object file: No such file or directory

- me-util
root@bmc-oob:~# me-util
me-util: error while loading shared libraries: /data/sara/openbmc.wiwynn/build/tmp/work/armv7at2hf-vfp-fb-linux-gnueabi/libpal/0.2-r1/recipe-sysroot/usr/lib/libnvme-mi.so: cannot open shared object file: No such file or directory

(2) After applying this patch
- sensor-util
root@bmc-oob:~# sensor-util e1s_iocm
E1S_B0_CUR                   (0x20) :    0.24 Amps  | (ok)
E1S_B1_CUR                   (0x21) :    0.24 Amps  | (ok)
E1S_B0_TEMP                  (0x22) :   28.00 C     | (ok)
E1S_B1_TEMP                  (0x23) :   28.00 C     | (ok)

- fw-util
root@bmc-oob:~# fw-util
USAGE: fw-util all|FRU --version [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
       fw-util FRU --update COMPONENT IMAGE_PATH --schedule now
       fw-util all --show-schedule
       fw-util all --delete-schedule TASK_ID

FRU        : Components
---------- : ----------
bmc        : bmc fscd tpm
nic        : nic
scc        : exp
server     : bic bicbl bios fpga me vr
uic        : fpga

- power-util
root@bmc-oob:~# power-util
Usage: power-util [ server ] [ status, graceful-shutdown, off, on, reset, cycle, 12V-off, 12V-on, 12V-cycle ]
Usage: power-util sled-cycle

- log-util
root@bmc-oob:~# log-util
ERROR: RequiredError: fru is required
OpenBMC System Event Log Management Utility
Usage: log-util [OPTIONS] fru

Positionals:
  fru TEXT:{all,bmc,dpb,e1s_iocm,nic,scc,server,sys,uic} REQUIRED

Options:
  -h,--help                   Print this help message and exit
  --json Needs: --print       Print SEL(s) in JSON format
[Option Group: Actions]
  Actions possible on the SEL(s)
  [Exactly 1 of the following options is required]
  Options:
    --print                     Print the SEL for the given FRU
    --clear                     Clear SEL(s) of the given FRU

- me-uilt
root@bmc-oob:~# me-util
Usage: me-util server <[0..n]data_bytes_to_send>
Usage: me-util server <cmd>
  cmd list:
    --get_dev_id      Get device ID
    --file <file>     Input commands from file

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1516

Reviewed By: benwei13

Differential Revision: D27240269

Pulled By: zhdaniel12

fbshipit-source-id: 3fd7b79c76