tools: fboss-lite: add cit rest_endpoint in template
Summary:
# Description
add cit rest_endpoint in template

# Motivation
to support rest_endpoing to the new project generated by template

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1823

Test Plan:
Validate on Janga DVT

need to custom add platform in /tests2/utils/platforms.py
```
 diff --git a/tests2/utils/platforms.py b/tests2/utils/platforms.py
index e56601d823e..965036d9576 100644
 --- a/tests2/utils/platforms.py
+++ b/tests2/utils/platforms.py
@@ -36,4 +36,5 @@ PLATFORMS = [
     "yamp",
     "yosemite",
     "yosemite4",
+    "new",
 ]
```

the result will show FAIIL on api_sys_mb_fruid, to notice developer need to custom for specific platform
```
root@bmc-oob:/run/tests2# python cit_runner.py -p new -r tests.new.test_rest_endpoint
test_endpoint_api (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api) ... ok
test_endpoint_api_sys (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys) ... ok
test_endpoint_api_sys_bmc (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc) ... ok
test_endpoint_api_sys_bmc_mtd (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_mtd) ... ok
test_endpoint_api_sys_bmc_secondary_boot (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_bmc_secondary_boot) ... ok
test_endpoint_api_sys_fc_present (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_fc_present) ... ok
test_endpoint_api_sys_firmware_info_all (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_firmware_info_all) ... skipped 'not available'
test_endpoint_api_sys_mb (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb) ... ok
test_endpoint_api_sys_mb_fruid (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid) ... FAIL
test_endpoint_api_sys_sensors (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_sensors) ... skipped 'not available'
test_endpoint_api_sys_server (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_server) ... skipped 'not available'
test_server_httperror_code_404 (tests.new.test_rest_endpoint.RestEndpointTest.test_server_httperror_code_404)
Test if REST server return 404 code when url is not accessible ... ok

======================================================================
FAIL: test_endpoint_api_sys_mb_fruid (tests.new.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_rest_endpoint_test.py", line 366, in test_endpoint_api_sys_mb_fruid
    self.set_endpoint_fruid_attributes()
  File "/run/tests2/tests/new/test_rest_endpoint.py", line 50, in set_endpoint_fruid_attributes
    self.fail('this test case needs to define the fru format')
AssertionError: this test case needs to define the fru format

----------------------------------------------------------------------
Ran 12 tests in 4.278s

FAILED (failures=1, skipped=3)
root@bmc-oob:/run/tests2#
`...

Reviewed By: mikechoifb

Differential Revision: D67506473

Pulled By: alandau

fbshipit-source-id: 3b530a782c2fb2977c01f5c7f026044e08adc2f2