fscd: Fix ValueError when sensor is not a numeric value
Summary:
Some sensors displayed by sensor-util (Especially PLDM)
tend to be non-numeric (Example: Normal).
Ensure we are not parsing these lines and only ones
which are numeric.

This fixes the ValueError exception thrown by FSCD:
```
Traceback (most recent call last):
File "/usr/bin/fscd.py", line 882, in <module>
   fscd.run()
 File "/usr/bin/fscd.py", line 859, in run
   self.update_zones(dead_fans, time_difference)
 File "/usr/bin/fscd.py", line 622, in update_zones
   sensors_tuples = self.machine.read_sensors(self.sensors, None)
 File "/usr/lib/python3.5/site-packages/fsc_bmcmachine.py", line 68, in re
   sensors[fru] = get_sensor_tuples(fru, self.nums[fru], sensor_sources, i
 File "/usr/lib/python3.5/site-packages/fsc_bmcmachine.py", line 193, in g
   sensor_sources[key].source.read(fru=fru_name, num=sensor_num, inf=inf)
 File "/usr/lib/python3.5/site-packages/fsc_bmcmachine.py", line 285, in p
   value = float(m.group(3))
 ValueError: could not convert string to float: 'Normal')
```

Test Plan: Load onto Y2 BMC and ensure we no longer see the exception.

Reviewed By: williamspatrick, zhdaniel12

Differential Revision: D29925680

fbshipit-source-id: f725fd4487