=?UTF-8?q?[openbmc.wiwynn][PR]=20common:=20redfish:=20fix?= =?UTF-8?q?=20error=20cases=20of=20sensor=20from=20Redfish=20Service=20Val?= =?UTF-8?q?id=E2=80=A6?= (#1898)
Summary:
…ator

1. Support to get sensor that the fru name contains "_".

2. The properties of "Thresholds" should be JSON object.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1898

Test Plan:
1. Build and test pass on Grand Canyon.

2. Check there are no unexpected error logs in BMC /var/log/messages and BMC SELs.

3. Get sensor URI of FRU: e1s_iocm successfully.
    - Before
    root@bmc-oob:~#:/usr/local/fbpackages/rest-api# curl -kvvvv http://127.0.0.1:8080/redfish/v1/Chassis/1/Sensors/e1s_iocm_32 | python3 -m json.tool
    ...
    {
        "Information": {
            "reason": "ValueError(\"invalid literal for int() with base 10: 'iocm'\")"
        },
        "Actions": [],
        "Resources": []
    }

    - After
    root@bmc-oob:~# curl -kvvvv http://127.0.0.1:8080/redfish/v1/Chassis/1/Sensors/e1s_iocm_32 | python3 -m json.tool
    ...
    {
        "odata.type": "#Sensor.v1_2_0.Sensor",
        "Id": "32",
        "Name": "e1s_iocm/e1s_iocm/E1S_B0_CUR",
        "Oem": {},
        "PhysicalContext": "Chassis",
        "Status": {
            "State": "Enabled",
            "Health": "OK"
        },
        "Reading": 0.23000000417232513,
        "ReadingUnits": "Amps",
        "ReadingRangeMin": -99999,
        "ReadingRangeMax": 99999,
        "Thresholds": {
            "UpperCaution": {
                "Reading": 0
            },
            "UpperCritical": {
                "Reading": 1
            },
            "UpperFatal": {
                "Reading": 0
            },
            "LowerCaution": {
                "Reading": 0
            },
            "LowerCritical": {
                "Reading": 0
            },
            "LowerFatal": {
                "Reading": 0
            }
        },
        "odata.id": "/redfish/v1/Chassis/1/Sensors/e1s_iocm_32"
    }

4. Run Redfish Service Validator for sensor successfully.

    - Before
    (1) E1S_B0_CUR
        root@guaigaui-Freedom:~/Ricky/OCP/service/Redfish-Service-Validator# python3.8 RedfishServiceValidator.py --ip http://192.168.88.46:8080 --payload Single /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Redfish Service Validator, version 2.0.3
        ...
        *** /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Attempt 1 of /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Response Time for GET to /redfish/v1/Chassis/1/Sensors/e1s_iocm_32: 0.009495147038251162 seconds.
        URI did not return resource /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Metadata: Namespaces missing from $metadata: set()

        Elapsed time: 0:02:01
        1 failGet errors in /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        failGet: 1
        metadataNamespaces: 2263
        Validation has failed: 1 problems found

    (2) BS_INLET_TEMP
        root@guaigaui-Freedom:~/Ricky/OCP/service/Redfish-Service-Validator# python3.8 RedfishServiceValidator.py --ip http://192.168.88.46:8080 --payload Single /redfish/v1/Chassis/1/Sensors/server_1
        Redfish Service Validator, version 2.0.3
        ...
        *** /redfish/v1/Chassis/1/Sensors/server_1
        Attempt 1 of /redfish/v1/Chassis/1/Sensors/server_1
        Response Time for GET to /redfish/v1/Chassis/1/Sensors/server_1: 0.015173589810729027 seconds.
        Unable to gather property info for URI /redfish/v1/Chassis/1/Sensors/server_1: AttributeError("'int' object has no attribute 'get'")
        Metadata: Namespaces missing from $metadata: set()

        Elapsed time: 0:02:00
        1 exceptionResource errors in /redfish/v1/Chassis/1/Sensors/server_1
        exceptionResource: 1
        metadataNamespaces: 2263
        Validation has failed: 1 problems found

    - After
    (1) E1S_B0_CUR
        root@guaigaui-Freedom:~/Ricky/OCP/service/Redfish-Service-Validator# python3.8 RedfishServiceValidator.py --ip http://192.168.88.46:8080 --payload Single /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Redfish Service Validator, version 2.0.3
        ...
        *** /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Attempt 1 of /redfish/v1/Chassis/1/Sensors/e1s_iocm_32
        Response Time for GET to /redfish/v1/Chassis/1/Sensors/e1s_iocm_32: 0.01086290180683136 seconds.
                 Type (Sensor.v1_2_0.Sensor), GET SUCCESS (time: 0:00:00.011411)
                 PASS
        Metadata: Namespaces missing from $metadata: set()

        Elapsed time: 0:02:01
        metadataNamespaces: 2263
        pass: 15
        passGet: 1
        skipOptional: 50
        Validation has succeeded.

    (2) BS_INLET_TEMP
        root@guaigaui-Freedom:~/Ricky/OCP/service/Redfish-Service-Validator# python3.8 RedfishServiceValidator.py --ip http://192.168.88.46:8080 --payload Single /redfish/v1/Chassis/1/Sensors/server_1
        Redfish Service Validator, version 2.0.3
        ...
        *** /redfish/v1/Chassis/1/Sensors/server_1
        Attempt 1 of /redfish/v1/Chassis/1/Sensors/server_1
        Response Time for GET to /redfish/v1/Chassis/1/Sensors/server_1: 0.008306454867124557 seconds.
                 Type (Sensor.v1_2_0.Sensor), GET SUCCESS (time: 0:00:00.008794)
                 PASS
        Metadata: Namespaces missing from $metadata: set()

        Elapsed time: 0:02:01
        metadataNamespaces: 2263
        pass: 15
        passGet: 1
        skipOptional: 50
        Validation has succeeded.

Reviewed By: williamspatrick

Differential Revision: D31822993

Pulled By: zhdaniel12

fbshipit-source-id: 62533944b1