Add support for accelerator cards in GPvX systems
Test Plan:
Manual tests:

redfish/v1/Chassis :  now includes accelerator cards P486954518
redfish/v1/Chassis/server1/Sensors?$expand=1 now contains cwc card if available: P486957247
redfish/v1/Chassis/accelerator0 P486957525
redfish/v1/Chassis/accelerator0/Sensors\?\$expand\=1 P486957382

Unit tests:
```
➜  openbmc git:(asicfish) ✗ ./tests2/ptest-runner rest-api
Found 521 recipes of which 15 define unit-tests
WARNING: /data/users/death0wl/openbmc/yocto/lf-dunfell/../../meta-facebook/recipes-utils/mac-util/mac-util_0.1.bb: Unable to get checksum for mac-util SRC_URI entry eeprom.h: file could not be found                                        | ETA:  --:--:--
Parsing recipes: 100% |########################################################################################################################################################################################################################| Time: 0:00:12
WARNING: No recipes available for:
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby3-image.bbappend
  /data/users/death0wl/openbmc/yocto/lf-dunfell/../../common/facebook/recipes-core/images/fby35-image.bbappend
Initialising tasks: 100% |#####################################################################################################################################################################################################################| Time: 0:00:07
START: ptest-runner
2022-03-16T07:21
BEGIN: /usr/lib/rest-api/ptest
[UNIT TESTS]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 405, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3.8/site-packages/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
/usr/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py:110: DeprecationWarning: "coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def handler_wrapper(*args, **kwargs):
/usr/lib/python3.8/site-packages/aiohttp/helpers.py:141: DeprecationWarning: Task.current_task() is deprecated, use asyncio.current_task() instead
  task = asyncio.Task.current_task(loop=loop)
.Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c36868>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c36970>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c36bb0>()]>>
./usr/local/fbpackages/rest-api/test_async_ratelimiter.py:87: RuntimeWarning: coroutine 'TestRatelimiterWorks.__assert_normal_request' was never awaited
  self.__assert_normal_request("GET", "agent2")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task was destroyed but it is pending!
task: <Task pending name='Task-40' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:60> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c367f0>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<AsyncRateLimiter._cleanup() running at /usr/local/fbpackages/rest-api/async_ratelimiter.py:60> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c36970>()]>>
.Task was destroyed but it is pending!
task: <Task pending name='Task-53' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c36910>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-55' coro=<AsyncRateLimiter._cleanup() done, defined at /usr/local/fbpackages/rest-api/async_ratelimiter.py:59> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xf5c365c8>()]>>
................./usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.........../usr/lib/python3.8/site-packages/aiohttp/web_server.py:44: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  yield from asyncio.gather(*coros, loop=self._loop)
...................s...../usr/lib/python3.8/traceback.py:359: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmpsv_rrj2p' mode='ab' closefd=True>
  result.append(FrameSummary(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
........................................................................
----------------------------------------------------------------------
Ran 128 tests in 2.569s

OK (skipped=1)
Name                                                                       Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------
/usr/local/fbpackages/rest-api/acl_config.py                                   3      0   100%
/usr/local/fbpackages/rest-api/acl_providers/__init__.py                       0      0   100%
/usr/local/fbpackages/rest-api/acl_providers/cached_acl_provider.py           39      3    92%   52-53, 62
/usr/local/fbpackages/rest-api/acl_providers/common_acl_provider_base.py      41      1    98%   61
/usr/local/fbpackages/rest-api/async_ratelimiter.py                           19      1    95%   61
/usr/local/fbpackages/rest-api/boardroutes.py                                  2      0   100%
/usr/local/fbpackages/rest-api/common_auth.py                                 56      5    91%   60-63, 152
/usr/local/fbpackages/rest-api/common_logging.py                              32      2    94%   62, 72
/usr/local/fbpackages/rest-api/common_middlewares.py                          76     12    84%   48, 68-69, 76-80, 89-90, 128-129
/usr/local/fbpackages/rest-api/common_utils.py                                57     36    37%   41-46, 50-65, 81-86, 94, 100-116
/usr/local/fbpackages/rest-api/common_webapp.py                               13      6    54%   9, 13-19
/usr/local/fbpackages/rest-api/redfish_account_service.py                     17      7    59%   25-34, 38-46
/usr/local/fbpackages/rest-api/redfish_base.py                                54     25    54%   98, 105, 124-128, 131-142, 161, 165, 169-172
/usr/local/fbpackages/rest-api/redfish_bios_firmware_dumps.py                218     36    83%   25-26, 35, 45, 59, 64, 167, 170, 245-246, 268, 271-272, 301-316, 329-335
/usr/local/fbpackages/rest-api/redfish_chassis.py                             35      3    91%   18-20
/usr/local/fbpackages/rest-api/redfish_chassis_helper.py                     210    133    37%   58-60, 64-65, 69-70, 74, 92-103, 109-116, 124-130, 134-186, 192-199, 203-222, 252-253, 259-301, 307, 311, 315-324, 348-349, 357, 367-376
/usr/local/fbpackages/rest-api/redfish_common_routes.py                       56      1    98%   29
/usr/local/fbpackages/rest-api/redfish_computer_system.py                     69     10    86%   12, 18, 21, 26-32
/usr/local/fbpackages/rest-api/redfish_log_service.py                         89      9    90%   32, 38, 45, 57, 88, 92, 116, 122, 143
/usr/local/fbpackages/rest-api/redfish_managers.py                           105     50    52%   23-32, 36-48, 52-57, 61-66, 71-93, 144-153
/usr/local/fbpackages/rest-api/redfish_powercycle.py                          60     10    83%   68, 79, 85, 93, 103, 125, 130, 132, 140, 145
/usr/local/fbpackages/rest-api/redfish_sensors.py                            128     38    70%   14-15, 24-25, 29, 65, 98-101, 109-110, 128, 145, 204, 206, 208, 210, 212, 214, 220-243
/usr/local/fbpackages/rest-api/redfish_service_root.py                        27      8    70%   39, 41-42, 49-71, 75-2526
/usr/local/fbpackages/rest-api/redfish_session_service.py                     12      7    42%   7-21, 25-34
/usr/local/fbpackages/rest-api/rest_config.py                                 37      1    97%   103
/usr/local/fbpackages/rest-api/rest_fruid.py                                  18     15    17%   28-44
/usr/local/fbpackages/rest-api/rest_fscd_sensor_data.py                       30      3    90%   59-62
/usr/local/fbpackages/rest-api/rest_fwinfo.py                                 47      1    98%   78
/usr/local/fbpackages/rest-api/rest_gpios.py                                  22      4    82%   33-59
/usr/local/fbpackages/rest-api/rest_mmc.py                                    25      0   100%
/usr/local/fbpackages/rest-api/rest_modbus_cmd.py                             86     10    88%   105, 125-128, 133, 137-141, 172
/usr/local/fbpackages/rest-api/rest_pal_legacy.py                            171    141    18%   32-33, 55-70, 74-82, 86-94, 99-107, 111-118, 126-147, 152-199, 203-218, 222-232, 236-238, 242-247, 251-259
/usr/local/fbpackages/rest-api/rest_utils.py                                   4      0   100%
--------------------------------------------------------------------------------------------------------
TOTAL                                                                       1858    578    69%
[Flake8]
[MYPY]
Success: no issues found in 76 source files
DURATION: 34
END: /usr/lib/rest-api/ptest
2022-03-16T07:22
STOP: ptest-runner

```

Reviewed By: GoldenBug

Differential Revision: D34897530

fbshipit-source-id: 97046472d9863021463fe602b2a6ab27b3449e02