cit: wedge400: remove TRVDD0P8_TH3(0.8V) from sensor list (#1371)
Summary:
In Wedge400 respin remove TRVDD0P8_TH3(0.8V),
to fix the cit fail need to remove it out from sensor list in CIT

```
FAIL: test_endpoint_api_sys_sensors (tests.wedge400.test_rest_endpoint.RestEndpointTest) (attrib='TRVDD0P8_TH3(0.8V)')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/common/base_rest_endpoint_test.py", line 156, in verify_endpoint_attributes
    self.assertIn(
AssertionError: 'TRVDD0P8_TH3(0.8V)' not found in '{"Information": [{"Adapter": "scm", "name": "scm", "present": true, "SCM_OUTLET_TEMP": "28.12", "SCM_HSC_VOLT": "12.04", "SCM_HSC_CURR": "1.18", "MB_OUTLET_TEMP": "28.00", "MB_INLET_TEMP": "26.00", "PCH_TEMP": "31.00", "VCCIN_VR_TEMP": "32.00", "1V05COMB_VR_TEMP": "32.00", "SOC_TEMP": "35.00", "SOC_THERM_MARGIN_TEMP": "-69.00", "VDDR_VR_TEMP": "28.00", "SOC_DIMMA_TEMP": "26.00", "SOC_DIMMB_TEMP": "26.00", "SOC_PACKAGE_POWER": "9.00", "VCCIN_VR_OUT_POWER": "6.00", "VDDR_VR_OUT_POWER": "0.75", "SOC_TJMAX_TEMP": "104.00", "P3V3_MB_VOLT": "3.28", "P12V_MB_VOLT": "12.01", "P1V05_PCH_VOLT": "1.04", "P3V3_STBY_MB_VOLT": "3.28", "P5V_STBY_MB_VOLT": "4.96", "PV_BAT_VOLT": "3.12", "PVDDR_VOLT": "1.23", "P1V05_COMB_VOLT": "1.05", "1V05COMB_VR_CURR": "1.88", "VDDR_VR_CURR": "0.88", "VCCIN_VR_CURR": "3.50", "VCCIN_VR_VOLT": "1.80", "VDDR_VR_VOLT": "1.21", "1V05COMB_VR_VOLT": "1.05", "1V05COMB_VR_OUT_POWER": "1.88", "INA230_POWER": "12.00", "INA230_VOLT": "12.01"}, {"Adapter": "smb", "name": "smb", "present": true, "XP12R0V(12V)": "11.95", "XP5R0V(5V)": "4.97", "XP3R3V_BMC(3.3V)": "3.30", "XP2R5V_BMC(2.5V)": "2.49", "XP1R2V_BMC(1.2V)": "1.20", "XP1R15V_BMC(1.15V)": "1.15", "XP1R2V_TH3(1.2V)": "1.21", "PVDD0P8_TH3(0.8V)": "0.80", "XP3R3V_TH3(3.3V)": "3.29", "VDD_CORE_TH3(0.75~0.9V)": "0.81", "POWR1220_VCCA(3.3V)": "3.30", "POWR1220_VCCINP(3.3V)": "3.31", "TH3_SERDES_IN_VOLT(PVDD)": "11.97", "TH3_SERDES_IN_CURR(PVDD)": "0.00", "TH3_SERDES_IN_POWER(PVDD)": "0.00", "TH3_SERDES_OUT_VOLT(PVDD)": "0.80", "TH3_SERDES_OUT_CURR(PVDD)": "0.00", "TH3_SERDES_OUT_POWER(PVDD)": "0.00", "TH3_SERDES_TEMP1(PVDD)": "26.00", "TH3_SERDES_IN_VOLT(TRVDD)": "11.97", "TH3_SERDES_IN_CURR(TRVDD)": "0.03", "TH3_SERDES_IN_POWER(TRVDD)": "0.50", "TH3_SERDES_OUT_VOLT(TRVDD)": "0.79", "TH3_SERDES_OUT_CURR(TRVDD)": "0.25", "TH3_SERDES_OUT_POWER(TRVDD)": "0.00", "TH3_SERDES_TEMP1(TRVDD)": "25.00", "XP3R3V_LEFT_IN_VOLT": "11.94", "XP3R3V_LEFT_IN_CURR": "0.62", "XP3R3V_LEFT_IN_POWER": "7.50", "XP3R3V_LEFT_OUT_VOLT": "3.31", "XP3R3V_LEFT_OUT_CURR": "2.00", "XP3R3V_LEFT_OUT_POWER": "7.00", "XP3R3V_LEFT_TEMP": "26.00", "XP3R3V_RIGHT_IN_VOLT": "11.97", "XP3R3V_RIGHT_IN_CURR": "0.19", "XP3R3V_RIGHT_IN_POWER": "1.50", "XP3R3V_RIGHT_OUT_VOLT": "3.31", "XP3R3V_RIGHT_OUT_CURR": "0.50", "XP3R3V_RIGHT_OUT_POWER": "2.00", "XP3R3V_RIGHT_TEMP": "25.00", "TH3_CORE_VOLT": "0.80", "TH3_CORE_CURR": "24.90", "TH3_CORE_POWER": "19.00", "TH3_CORE_TEMP1": "0.00", "SMB_LM75B_U28_TEMP": "25.31", "SMB_LM75B_U55_TEMP": "25.00", "SMB_TMP421_U62_TEMP": "25.75", "SMB_TMP421_Q9_TEMP": "25.56", "SMB_TMP421_U63_TEMP": "25.38", "SMB_TMP421_Q10_TEMP": "25.62", "TH3_DIE_TEMP1": "33.38", "TH3_DIE_TEMP2": "35.00", "DOM_FPGA1_MAX_TEMP": "0.00", "DOM_FPGA2_MAX_TEMP": "0.00", "FCM_LM75B_U1_TEMP": "25.00", "FCM_LM75B_U2_TEMP": "25.12", "FCM_HSC_VOLT": "12.03", "FCM_HSC_CURR": "2.15", "XP1R0V_FPGA": "0.99", "XP1R8V_FPGA": "1.79", "XP3R3V_FPGA": "3.20", "XP3R3V_RIGHT": "3.26", "XP3R3V_LEFT": "3.28"}, {"Adapter": "psu1", "name": "psu1", "present": true, "PSU1_IN_VOLT": "225.00", "PSU1_12V_VOLT": "11.98", "PSU1_STBY_VOLT": "3.27", "PSU1_IN_CURR": "0.42", "PSU1_12V_CURR": "6.41", "PSU1_STBY_CURR": "0.01", "PSU1_IN_POWER": "88.25", "PSU1_12V_POWER": "75.38", "PSU1_STBY_POWER": "0.08", "PSU1_FAN_SPEED": "7680.00", "PSU1_TEMP1": "34.00", "PSU1_TEMP2": "34.00", "PSU1_TEMP3": "38.00"}, {"Adapter": "psu2", "name": "psu2", "present": false}, {"Adapter": "pem1", "name": "pem1", "present": false}, {"Adapter": "pem2", "name": "pem2", "present": true, "PEM2_IN_VOLT": "12.05", "PEM2_OUT_VOLT": "12.06", "PEM2_FET_BAD": "0.00", "PEM2_FET_SHORT": "0.00", "PEM2_CURR": "0.00", "PEM2_POWER": "0.00", "PEM2_FAN1_SPEED": "8228.00", "PEM2_FAN2_SPEED": "8228.00", "PEM2_HOT_SWAP_TEMP": "25.69", "PEM2_AIR_INLET_TEMP": "24.38", "PEM2_AIR_OUTLET_TEMP": "24.58"}], "Actions": [], "Resources": ["scm", "smb", "psu1", "psu2", "pem1", "pem2"]}' : endpoint /api/sys/sensors missing attrib TRVDD0P8_TH3(0.8V)

======================================================================
FAIL: test_smb_sensor_keys (tests.wedge400.test_sensor.SmbSensorTest) (key='TRVDD0P8_TH3(0.8V)')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/wedge400/test_sensor.py", line 150, in test_smb_sensor_keys
    self.assertIn(
AssertionError: 'TRVDD0P8_TH3(0.8V)' not found in dict_keys(['present', 'XP12R0V(12V)', 'XP5R0V(5V)', 'XP3R3V_BMC(3.3V)', 'XP2R5V_BMC(2.5V)', 'XP1R2V_BMC(1.2V)', 'XP1R15V_BMC(1.15V)', 'XP1R2V_TH3(1.2V)', 'PVDD0P8_TH3(0.8V)', 'XP3R3V_TH3(3.3V)', 'VDD_CORE_TH3(0.75~0.9V)', 'POWR1220_VCCA(3.3V)', 'POWR1220_VCCINP(3.3V)', 'TH3_SERDES_IN_VOLT(PVDD)', 'TH3_SERDES_IN_CURR(PVDD)', 'TH3_SERDES_IN_POWER(PVDD)', 'TH3_SERDES_OUT_VOLT(PVDD)', 'TH3_SERDES_OUT_CURR(PVDD)', 'TH3_SERDES_OUT_POWER(PVDD)', 'TH3_SERDES_TEMP1(PVDD)', 'TH3_SERDES_IN_VOLT(TRVDD)', 'TH3_SERDES_IN_CURR(TRVDD)', 'TH3_SERDES_IN_POWER(TRVDD)', 'TH3_SERDES_OUT_VOLT(TRVDD)', 'TH3_SERDES_OUT_CURR(TRVDD)', 'TH3_SERDES_OUT_POWER(TRVDD)', 'TH3_SERDES_TEMP1(TRVDD)', 'XP3R3V_LEFT_IN_VOLT', 'XP3R3V_LEFT_IN_CURR', 'XP3R3V_LEFT_IN_POWER', 'XP3R3V_LEFT_OUT_VOLT', 'XP3R3V_LEFT_OUT_CURR', 'XP3R3V_LEFT_OUT_POWER', 'XP3R3V_LEFT_TEMP', 'XP3R3V_RIGHT_IN_VOLT', 'XP3R3V_RIGHT_IN_CURR', 'XP3R3V_RIGHT_IN_POWER', 'XP3R3V_RIGHT_OUT_VOLT', 'XP3R3V_RIGHT_OUT_CURR', 'XP3R3V_RIGHT_OUT_POWER', 'XP3R3V_RIGHT_TEMP', 'TH3_CORE_VOLT', 'TH3_CORE_CURR', 'TH3_CORE_POWER', 'TH3_CORE_TEMP1', 'SMB_LM75B_U28_TEMP', 'SMB_LM75B_U55_TEMP', 'SMB_TMP421_U62_TEMP', 'SMB_TMP421_Q9_TEMP', 'SMB_TMP421_U63_TEMP', 'SMB_TMP421_Q10_TEMP', 'TH3_DIE_TEMP1', 'TH3_DIE_TEMP2', 'DOM_FPGA1_MAX_TEMP', 'DOM_FPGA2_MAX_TEMP', 'FCM_LM75B_U1_TEMP', 'FCM_LM75B_U2_TEMP', 'FCM_HSC_VOLT', 'FCM_HSC_CURR', 'XP1R0V_FPGA', 'XP1R8V_FPGA', 'XP3R3V_FPGA', 'XP3R3V_RIGHT', 'XP3R3V_LEFT']) : Missing key TRVDD0P8_TH3(0.8V) in SMB sensor data

----------------------------------------------------------------------
Ran 238 tests in 2474.195s

FAILED (failures=2, errors=24, skipped=32)
```

#### TestPlan:
Test CIT related sensor.
```
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p wedge400 --run-test tests.wedge400.test_rest_endpoint.RestEndpointTest
test_endpoint_api (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_fan_present (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_psu_present (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_scm_present (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc_mtd (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_bmc_secondary_boot (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fc_present (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_all (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_cpld (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_fpga (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_firmware_info_scm (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan1 (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan2 (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan3 (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fan4 (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_fcm (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_fruid_scm (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_mb (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_mb_fruid (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_sensors (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_server (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_seutil_fruid (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... ok
test_endpoint_api_sys_switch_reset (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... skipped 'Skip vddcore test on Wedge400 platform'
test_endpoint_api_sys_vddcore_get (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... skipped 'Skip vddcore test on Wedge400 platform'
test_endpoint_api_sys_vddcore_post (tests.wedge400.test_rest_endpoint.RestEndpointTest) ... skipped 'Skip vddcore test on Wedge400 platform'
test_server_httperror_code_404 (tests.wedge400.test_rest_endpoint.RestEndpointTest)
Test if REST server return 404 code when url is not accessible ... ok

----------------------------------------------------------------------
Ran 28 tests in 91.595s

OK (skipped=3)
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p wedge400 --run-test tests.wedge400.test_sensor
test_fan1_sensor_keys (tests.wedge400.test_sensor.Fan1SensorTest) ... ok
test_fan2_sensor_keys (tests.wedge400.test_sensor.Fan2SensorTest) ... ok
test_fan3_sensor_keys (tests.wedge400.test_sensor.Fan3SensorTest) ... ok
test_fan4_sensor_keys (tests.wedge400.test_sensor.Fan4SensorTest) ... ok
test_pem1_sensor_keys (tests.wedge400.test_sensor.Pem1SensorTest) ... skipped 'pem1 is not present'
test_pem2_sensor_keys (tests.wedge400.test_sensor.Pem2SensorTest) ... ok
test_psu1_sensor_keys (tests.wedge400.test_sensor.Psu1SensorTest) ... ok
test_psu2_sensor_keys (tests.wedge400.test_sensor.Psu2SensorTest) ... skipped 'psu2 is not present'
test_scm_sensor_keys (tests.wedge400.test_sensor.ScmSensorTest) ... ok
test_scm_temp_sensor_range (tests.wedge400.test_sensor.ScmSensorTest) ... ok
test_smb_sensor_keys (tests.wedge400.test_sensor.SmbSensorTest) ... ok

----------------------------------------------------------------------
Ran 11 tests in 27.075s

OK (skipped=2)
root@bmc-oob:/usr/local/bin/tests2#
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1371

Reviewed By: GoldenBug

Differential Revision: D37407184

fbshipit-source-id: 6d897915d90aa8f12a9a1c010f6dd95d9c56c345