fix the size check of symblink file
Summary:
U-boot recipe image size checking script did not taking consideration of the symlink. Thus the image size checking is not checking the real binary size.

this fix this issue, let the stat command following symlink.

Test Plan:
Verify the issue via change the MAX_SPL to be 100 bytes and try to build, it will pass the check and success
```

[zhdaniel@devvm30589.prn1 ~/openbmc/build-fbtp] git diff
 diff --git a/meta-aspeed/classes/kernel_fitimage.bbclass b/meta-aspeed/classes/kernel_fitimage.bbclass
index 6ea25ee0117..b099be5524d 100644
 --- a/meta-aspeed/classes/kernel_fitimage.bbclass
+++ b/meta-aspeed/classes/kernel_fitimage.bbclass
@@ -39,7 +39,7 @@ UBOOT_MAX_SIZE = "389120"
 FIT_MAX_SIZE = "28442624"
 RECOVERY_MAX_SIZE = "303104"
 SIGNED_UBOOT_MAX_SIZE = "393216"
-SPL_MAX_SIZE = "86016"
+SPL_MAX_SIZE = "100"

 UBOOT_SOURCE ?= "${DEPLOY_DIR_IMAGE}/u-boot-${MACHINE}.${UBOOT_SUFFIX}"
 FIT_SOURCE ?= "${STAGING_DIR_HOST}/etc/fit-${MACHINE}.its"
@@ -128,7 +128,7 @@ flash_image_generate() {
     dd if=${FIT_DESTINATION} of=${FLASH_IMAGE_DESTINATION} bs=1k seek=${FLASH_FIT_OFFSET} conv=notrunc

     if [ "x${VERIFIED_BOOT}" != "x" ] ; then
-      if [ $(stat -L -c%s ${UBOOT_SPL_SOURCE}) -gt ${SPL_MAX_SIZE} ]; then
+      if [ $(stat -c%s ${UBOOT_SPL_SOURCE}) -gt ${SPL_MAX_SIZE} ]; then
           echo "SPL is too large to fit into the partition"
           return 1
       fi

[zhdaniel@devvm30589.prn1 ~/openbmc/build-fbtp] bitbake fbtp-image

... snip unrelated building log

NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 3436 tasks of which 3044 didn't need to be rerun and all succeeded.
```

Add the -L to let stat following symlink to check the real binary size, the build will fail to detect the SPL size is exceeding size limitation.

```
 diff --git a/meta-aspeed/classes/kernel_fitimage.bbclass b/meta-aspeed/classes/kernel_fitimage.bbclass
index 6ea25ee0117..91072515181 100644
 --- a/meta-aspeed/classes/kernel_fitimage.bbclass
+++ b/meta-aspeed/classes/kernel_fitimage.bbclass
@@ -39,7 +39,7 @@ UBOOT_MAX_SIZE = "389120"
 FIT_MAX_SIZE = "28442624"
 RECOVERY_MAX_SIZE = "303104"
 SIGNED_UBOOT_MAX_SIZE = "393216"
-SPL_MAX_SIZE = "86016"
+SPL_MAX_SIZE = "100"

 UBOOT_SOURCE ?= "${DEPLOY_DIR_IMAGE}/u-boot-${MACHINE}.${UBOOT_SUFFIX}"
 FIT_SOURCE ?= "${STAGING_DIR_HOST}/etc/fit-${MACHINE}.its"

[zhdaniel@devvm30589.prn1 ~/openbmc] bitbake fbtp-image

...snip unrelated building log

| 20826358 bytes (21 MB) copied, 0.0792498 s, 263 MB/s
| **SPL is too large to fit into the partition**
| WARNING: /data/users/zhdaniel/workspaces/openbmc/build-fbtp/tmp/work/fbtp-fb-linux-gnueabi/fbtp-image/1.0-r0/temp/run.flash_image_generate.805029:1 exit 1 from 'return 1'

ERROR: fbtp-image-1.0-r0 do_image_complete: Function failed: flash_image_generate (log file is located at /data/users/zhdaniel/workspaces/openbmc/build-fbtp/tmp/work/fbtp-fb-linux-gnueabi/fbtp-image/1.0-r0/temp/log.do_image_complete.805029)
ERROR: Logfile of failure stored in: /data/users/zhdaniel/workspaces/openbmc/build-fbtp/tmp/work/fbtp-fb-linux-gnueabi/fbtp-image/1.0-r0/temp/log.do_image_complete.805029
```

Reviewed By: amithash

Differential Revision: D15323818

fbshipit-source-id: 9bed9f4990